common/json.go, common/types.go, salesforce/write.go, test/salesforce.go
There were some linter errors which I fixed.
=> fix: Fix linter errors

common/parse.go, common/types.go, hubspot/parse.go, hubspot/read.go, hubspot/search.go, hubspot/types.go, salesforce/parse.go, salesforce/read.go
Read more: https://ampersand.slab.com/posts/read-action-result-format-3pzumqrr
The ReadResult now returns fields and the raw response for each row. The server then map these fields agonistic of the structure of the provider response.
* Updates ReadResult.Data
* Refactors `ParseResult` into common package
* Adds provider specific ParseResult functions
```
{
"rows": 2,
"data": [
{
"fields": {
"firstname": "Maria"
},
"raw": {
"archived": false,
"createdAt": "2023-10-26T17:55:48.301Z",
"id": "1",
"properties": {
"createdate": "2023-10-26T17:55:48.301Z",
"firstname": "Maria",
"hs_object_id": "1",
"lastmodifieddate": "2023-10-26T17:56:14.834Z"
},
"updatedAt": "2023-10-26T17:56:14.834Z"
}
},
{
"fields": {
"firstname": "Ryan"
},
"raw": {
"archived": false,
"createdAt": "2023-10-26T17:55:48.691Z", …
```
=> [ENG-472] Update ReadResult.Data to return typed rows

hubspot/read.go, hubspot/search.go
This allows us to use the exported functions in our server
=> chore: export hubspot helper functions

go.mod, go.sum, test/hubspot/main.go, test/utils/close.go, test/utils/creds.go, test/utils/dump.go, test/utils/fail.go, test/utils/hubspot.go, test/utils/logging.go
I forgot to add these tests to the write PR. These tests actually validate that hubspot writes work.
See https://github.com/amp-labs/connectors/pull/41 for an example run.
=> [ENG-459] feat: Add hubspot write tests

common/types.go, hubspot/write.go, salesforce/metadataApi.go, test/hubspot/main.go
no more wrapping everything in 'properties'. This will ensure a consistent experience for our users.
=> fix: Make the data format for hubspot more consistent

common/types.go, go.mod, go.sum, hubspot/write.go, salesforce/metadata.go, salesforce/write.go, test/hubspot/main.go
In code, we are mixing object and record. Object should refer to record type (account, contact etc) and actual data should be record. 
Relate Server PR: https://github.com/amp-labs/server/pull/565
These PR's should be merged in order
1. Connectors PR should be merged first.
2. Update server with new commit, then merge server PR.
=> [ENG-549] chore: change object to record

utils/credentials.go, utils/credentials_test.go, utils/testcred1.json, utils/testcred2.json
This is Part 1 for consolidation of credential getting mechanism. 
Created Credential getting struct and methods that support multi-source value getting ( currently from env var , and json file). 
Part 2 will do clean-up of current code base test examples to use these methods and consolidate and reduce redundant code.
=> [ENG-522] Create credential getter. 

providers/catalog.go, providers/catalog_test.go
No catalog variables
Supports batching requests and offers App component API as well as REST API.
Requesting a page with pagination properties
Using the next page details to go to the next page:
=> [ENG-821] feat: Add Asana connector

providers/catalog.go, providers/catalog_test.go
No catalog variables
localhost:4444/api/v1/contact/
localhost:4444/api/v1/contact/
localhost:4444/api/v1/contact/cont_4fWk9sSGSSUBbKKT42bdmoskEXZiV1N5ojp5vbHqlKr - failed with error 403 
while the direct request to https://api.close.com/api/v1/contact/cont_Zgz6xgtpLEELtYdABl4rHO3RvJjW4hmEWiKVPcY4ujr
worked just fine
###DEL
localhost:4444/api/v1/contact/cont_4fWk9sSGSSUBbKKT42bdmoskEXZiV1N5ojp5vbHqlKr
localhost:4444/api/v1/contact?_skip=0&_limit=2
This request failed with error Error: write EPROTO 12884924564552:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../../../src/third_party/boringssl/src/ssl/tls_record.cc:242
While direct request works fine - https://api.close.com/api/v1/contact?skip=0&_limit=2
=> [ENG-792] feat: Add Close CRM connector 

providers/catalog.go, providers/catalog_test.go
Dropbox    Provider = "dropbox"
Supports batching requests and pagination as well
URL: http://localhost:4444/file_requests/get
URL: http://localhost:4444/file_requests/create
URL: http://localhost:4444/file_requests/update
=> [ENG-825] feat: Add Dropbox connector

providers/catalog.go, providers/catalog_test.go
- Ran Linter
+ Catalog tests passing
+ Created PR from non-main branch 
No additional variables
URL: <localhost:4444/v2/companies> 
URL: <http://localhost:4444/v2/companies/52655458/addresses>
=> [ENG-799] feat: Add Sellsy connector 

basic/string.go, common/oauth.go, salesforce/bulkwrite.go, salesforce/read.go, salesforce/write.go, test/metadata/main.go
Does as the title says, makes the linter errors go away
=> chore: Fix linter errors

providers/catalog.go, providers/catalog_test.go
Zoom       Provider = "zoom"
Supports pagination and no batching support
URL: http://localhost:4444/v2/meetings/87526499441
URL: http://localhost:4444/v2/users/me/meetings
URL: http://localhost:4444/v2/meetings/87526499441
URL: http://localhost:4444/v2/meetings/87526499441
=> [ENG-849] feat: Add Zoom connector

providers/catalog.go, providers/catalog_test.go
URL: <localhost:4444/account> 
URL: <localhost:4444/people>
URL: <localhost:4444/people/160213588>
URL: <localhost:4444/people/160213590>
=> [ENG-793] feat: Add Copper connector

providers/catalog.go, providers/catalog_test.go
None
Have a custom rate limit error.
Retrive accounts
Create a subscriber
Update name of a subscriber
Retrieving a paginated list of subscribers
Using the `next_collection_link` to retrieve the next page subscribers.
=> [ENG-886] feat:Add AWeber connector

providers/catalog.go, providers/catalog_test.go
None
Scopes are explicitly required in the Authorization call.
Requesting a list of contacts. Paginated.
Requesting the next page
=> [ENG-894] feat: Add ConstantContact connector

providers/catalog.go, providers/catalog_test.go
Dynamics365BusinessCentral Provider = "dynamics365BusinessCentral"
Supports batching requests and pagination as well
URL: http://localhost:4444/v2.0/2a909abc-d594-408f-bfa0-cffbe67bc4bf/Production/api/v2.0/companies(7ace90d9-b3d3-ee11-904f-6045bde9c6f5)/projects(f30643f2-91e7-ee11-a1fd-6045bda565d9)
URL: http://localhost:4444/v2.0/2a909abc-d594-408f-bfa0-cffbe67bc4bf/Production/api/v2.0/companies(7ace90d9-b3d3-ee11-904f-6045bde9c6f5)/projects
URL: http://localhost:4444/v2.0/2a909abc-d594-408f-bfa0-cffbe67bc4bf/Production/api/v2.0/companies(7ace90d9-b3d3-ee11-904f-6045bde9c6f5)/projects(f30643f2-91e7-ee11-a1fd-6045bda565d9)
URL: http://localhost:4444/v2.0/2a909abc-d594-408f-bfa0-cffbe67bc4bf/Production/api/v2.0/companies(7ace90d9-b3d3-ee11-904f-6045bde9c6f5)/projects(f30643f2-91e7-ee11-a1fd …
=> [ENG-881] feat: Add Microsoft dynamic365-business-central connector

salesforce/bulk.go, test/salesforce/bulkquery/main.go
Simple Saleforce Bulkquery
```
jaehyunlim@Jaehyuns-MacBook-Pro connectors % go run test/salesforce/bulkquery/main.go
time=2024-03-27T15:52:17.021-07:00 level=INFO msg="Query Info"
{
"id": "750Dp0000090sPOIAY",
"object": "Account",
"createdById": "005Dp000003Cd1SIAS",
"state": "UploadComplete",
"operation": "query",
"columnDelimiter": "COMMA",
"lineEnding": "LF",
"numberRecordsFailed": 0,
"numberRecordsProcessed": 0,
"errorMessage": "",
"apiVersion": 59,
"concurrencyMode": "Parallel",
"contentType": "CSV",
"createdDate": "2024-03-27T22:52:16.000+0000",
"systemModstamp": "2024-03-27T22:52:16.000+0000"
} <nil>
..
time=2024-03-27T15:52:19.376-07:00 level=INFO msg="Job completed... fetching results"
time=2024-03-27T15:52:19.552-07:00 level=INFO msg="Query results"
"Id","Name" …
```
=> [ENG-878] Feat: Bulkquery

common/http.go, common/json.go, salesforce/bulk.go, salesforce/bulkwrite.go, salesforce/methods.go, test/salesforce/bulkdelete/main.go, test/salesforce/bulkdelete/touchpoints_for_bulkdelete_20240325.csv, test/salesforce/bulkquery/main.go, test/salesforce/bulkwrite/main.go, test/utils/connector.go, utils/format.go
Tested as below
```
jaehyunlim@Jaehyuns-MBP connectors % go run test/salesforce/bulkdelete/main.go
time=2024-03-26T16:03:05.571-07:00 level=INFO msg="Bulk write job created" res="&{State:UploadComplete JobId:750Dp0000090pptIAA}"
.time=2024-03-26T16:03:07.906-07:00 level=INFO msg="Bulk write job done"
time=2024-03-26T16:03:08.798-07:00 level=INFO msg="Bulk delete job created" res="&{State:UploadComplete JobId:750Dp0000090pcEIAQ}"
.time=2024-03-26T16:03:11.137-07:00 level=INFO msg="Bulk delete job done"
{
"jobId": "750Dp0000090pcEIAQ",
"state": "JobComplete",
"jobInfo": {
"id": "750Dp0000090pcEIAQ",
"object": "Touchpoint__c",
"createdById": "005Dp000003Cd1SIAS",
"externalIdFieldName": "",
"state": "JobComplete",
"operation": "delete",
"columnDelimiter": "COMMA",
"lineEnding": "LF", …
```
=> [ENG-878] feat: bulk delete

providers/catalog.go, providers/catalog_test.go, scripts/oauth/token.go
Gainsight Provider = "gainsight"
Workspace = "sb-ampersand.us2"
Supports batching requests and pagination as well
URL: http://localhost:4444/v1/users/services/list
URL: http://localhost:4444/v1/users/services?notify=false
URL: http://localhost:4444/v1/users/services?key=SFDCUserName
=> [ENG-850] feat: Add Gainsight connector

providers/catalog.go, providers/catalog_test.go
Closes [#143](https://github.com/amp-labs/connectors/issues/143)
Box Provider = "box"
Supports batching requests and pagination as well
URL: http://localhost:4444/2.0/users/32911837763
URL: http://localhost:4444/2.0/users
URL: http://localhost:4444/2.0/users/32911837763
URL: http://localhost:4444/2.0/users/32911837763
=> feat: Add Box connector

providers/catalog.go, providers/catalog_test.go
Closes #148 
WordPress Provider = "wordPress"
URL: http://localhost:4444/rest/v1.1/sites/ampersand73.wpcomstaging.com/posts/21
URL: http://localhost:4444/rest/v1.1/sites/ampersand73.wpcomstaging.com/posts/new
URL: http://localhost:4444/rest/v1.1/sites/ampersand73.wpcomstaging.com/posts/21
URL: http://localhost:4444/rest/v1.1/sites/ampersand73.wpcomstaging.com/posts/21/delete
=> feat: Add WordPress connector #148

providers/catalog.go, salesforce/bulk.go, scripts/oauth/token.go
adding "delete" mode and some linting and clean up
=> [ENG-878] Add delete mode in bulk operation

providers/catalog.go, providers/catalog_test.go
Closes #177
Webflow Provider = "webflow"
URL: http://localhost:4444/v2/sites/660e39ec0ea3bb08db545b0b/collections
URL: http://localhost:4444/v2/sites/660e39ec0ea3bb08db545b0b/collections
URL: http://localhost:4444/v2/collections/6613c6a269ff186a1a71131f/fields/3b44092395a3042b0a8231647b457a54
URL: http://localhost:4444/v2/collections/6613c6a269ff186a1a71131f/fields/3b44092395a3042b0a8231647b457a54
=> feat: Add webflow auth connector

providers/catalog.go, providers/catalog_test.go
=> fix: Rename MS D365 (Sales) to (CRM)

providers/catalog.go, providers/catalog_test.go
+ Tests
+ Linter
+ Branch
No parameters required
explicit scopes are required
localhost:4444/lists - get
localhost:4444/lists - post
localhost:4444/lists/Rq4BgM/ - patch
localhost:4444/lists/Rq4BgM/ - del
closes #180
=> Add Klavyio connector

providers/catalog.go, providers/catalog_test.go
Rajat, as discussed, here is the PKCE grant type addition for Sellsy
=> Sellsy grant type_fix

providers/catalog.go, providers/catalog_test.go
Closes #209 
GoogleMail Provider = "googleMail"
URL: http://localhost:4444/gmail/v1/users/me/labels/Label_1
URL: http://localhost:4444/gmail/v1/users/me/labels
URL: http://localhost:4444/gmail/v1/users/me/labels/Label_1
URL: http://localhost:4444/ex/jira/0bf9b1a5-eebb-4385-ab8c-8cda58854c8e/rest/api/3/dashboard/10002
=> feat: Add Google Mail connector

providers/catalog.go, providers/catalog_test.go
Update the TokenURL to wrap the response in JSON format
=> StackExchange: Update TokenURL

providers/catalog.go, providers/catalog_test.go
Closes #190 
Google Provider = "google"
URL: http://localhost:4444/calendar/v3/calendars/c_73ef30966d3d36a36d98b4c162339bd3c959658adb861906ec1ff78dc92f90f3@group.calendar.google.com
URL: http://localhost:4444/calendar/v3/calendars
URL: http://localhost:4444/calendar/v3/calendars/c_73ef30966d3d36a36d98b4c162339bd3c959658adb861906ec1ff78dc92f90f3@group.calendar.google.com
URL: http://localhost:4444/calendar/v3/calendars/c_73ef30966d3d36a36d98b4c162339bd3c959658adb861906ec1ff78dc92f90f3@group.calendar.google.com
=> feat: Add Google connector

providers/catalog.go, providers/catalog_test.go
+tests
+branch
+linter
localhost:4444/public/v1/rooms/1713361535377
localhost:4444/public/v1/rooms
localhost:4444/public/v1/rooms/1713361535377
localhost:4444/public/v1/rooms/1713361535377
##Pagination GET
localhost:4444/public/v1/workspaces/ampersanddemo0613/rooms
To navigate to next screen, add &next=<the next token> from the current page
Closes #214
=> Add Mural Connector

providers/catalog.go, providers/catalog_test.go
+ branch
+ tests
+ linter
localhost:4444/invitations
localhost:4444/invitations?email=example11@example.com
localhost:4444/invitations/IEAGFBRFJEART6U3?role=Collaborator
localhost:4444/invitations/IEAGFBRFJEARVAB4
Closes #213
=> Add Wrike Connector

providers/catalog.go, providers/catalog_test.go
+ branch
+ tests
+ linter
localhost:4444/team-messaging/v1/events/25272334
localhost:4444/team-messaging/v1/events
localhost:4444/team-messaging/v1/events/25272334
localhost:4444/team-messaging/v1/events/25288718
localhost:4444/team-messaging/v1/events?recordCount=1&pageToken=eyJ2IjoxLCJkIjoxLCJ0cyI6MTcxMzUyNTE4MjA5NywicmMiOjF9
Closes #183
=> Add RingCentral connector

providers/catalog.go, providers/catalog_test.go
Closes #212 
None
URL: http://localhost:4444/v2/boards
Get Boards
URL: https://proxy.withampersand.com/v2/boards
Create Board
URL: htts://proxy.withampersand.com/v2/boards/<board-id>
Update Board
URL: https://proxy.withampersand.com/v2/boards/<board-id>
Delete Board
Get Boards from offset to limit
=> enable proxy: Miro

providers/catalog.go, providers/catalog_test.go
Closes #155 
URL: <https://proxy.withampersand.com/conversations.list> 
URL: <https://proxy.withampersand.com/chat.postMessage> 
Postman screenshot (must show the request URL, the response status code & body clearly)
**Invalid path**
**invalid method**
URL:<https://proxy.withampersand.com/conversations.list?limit=1>
With limit
With cursor
=> Slack: Enable proxy

.github/PULL_REQUEST_TEMPLATE/proxy_connector.md
=> git PR template: Proxy Connector

go.mod, providers/catalog.go, providers/catalog_test.go
* {{scope}}
Resolves #235 
Since the version is included in the base URL it should not be added when making an API call.
URL: <localhost:4444/users> 
**Get all users**
URL: <localhost:4444/users> 
**Create a user**
URL: <localhost:4444/users/1292061> 
**Update a user**
URL: <localhost:4444/users/1292061> 
**Delete a user**
URL:<localhost:4444/users?page=3&per_page=1>
**Get all users with pagination**
=> Aircall: add connector

providers/catalog.go, providers/catalog_test.go
URL: https://proxy.withampersand.com/v2/activities/emails
URL: https://proxy.withampersand.com/v2/imports
URL: https://proxy.withampersand.com/v2/people/164510523
URL: https://proxy.withampersand.com/v2/people/164509523
Retrieving paginated requests:
Requesting the next page:
closes #323
=> feat: enable proxy in salesloft

providers/catalog.go, providers/catalog_test.go
+ Branch
+ Tests
Proxying request: GET api.createsend.com/api/v3.3/clients.json
Proxying request: POST api.createsend.com/api/v3.3/lists/248bee0be2c423140f7345fc29108c17.json
Proxying request: GET api.createsend.com/api/v3.3/campaigns/1b6bc4603793034d640812aa5817b697/clicks.json
closes #303
=> Add Campaign Monitor Auth Connector

providers/catalog.go, providers/catalog_test.go
URL: https://proxy.withampersand.com/v3/contacts
URL: https://proxy.withampersand.com/v3/emails
URL: https://proxy.withampersand.com/v3/emails/activities/7c523ce0-4acf-4fa9-bcee-f6f6174be46d
URL: https://proxy.withampersand.com/v3/emails/8c34cb7c-526d-4b8b-9160-b3582273971f
URL: https://proxy.withampersand.com/v3/contacts
Requesting a paginated list of contacts
Requesting the next page
Closes #343
=> feat: Update proxy support for ConstantContact

providers/catalog.go, scripts/proxy/proxy.go, test/utils/mockutils/readResult.go, test/utils/mockutils/writeResult.go
=> chore: Ran gofumpt

microsoftdynamicscrm/connector.go, providers/catalog.go, providers/catalog_test.go
=> [ENG-1141] Rename DynamicsCRM

common/interpreter/statusCode.go, common/jsonquery/queries.go, connectors.go, go.mod, go.sum, intercom/client.go, intercom/connector.go, intercom/errors.go, intercom/errors_test.go, intercom/methods.go, intercom/params.go, intercom/parse.go, intercom/read.go, intercom/read_test.go, intercom/test/media-not-acceptable.json, intercom/test/page-req-too-large.json, intercom/test/read-contacts-1-first-page.json, intercom/test/read-contacts-2-second-page.json, intercom/test/read-contacts-3-last-page.json, intercom/test/read-conversations.json, intercom/test/read-notes-1-first-page.json, intercom/test/read-notes-2-last-page.json, intercom/url.go, intercom/url_test.go, test/intercom/connector.go, test/intercom/read/main.go, test/salesloft/read/main.go, utils/credentials.go
Closes #347 
Sample of getting notes on a contact (temporal request, not part of code):
From `test/intercom/read/main.go` reading conversations:
=> feat: Deep connector Intercom (Read)

providers/catalog.go, providers/catalog_test.go
Closes #176 
URL: <https://proxy.withampersand.com/v2/conversations> 
URL: <https://proxy.withampersand.com/v2/conversations> 
URL:<https://proxy.withampersand.com/v2/conversations/2587049198>
URL:<https://proxy.withampersand.com/v2/conversations/2587049201>
**Wrong path**
Please add screenshots that show successful pagination using the connector. 
token request came back with 403 if called via proxy
No issues requesting it directly
=> Feat: HelpScoutMailbox: Enable Proxy

providers/catalog.go, providers/catalog_test.go
URL:  https://proxy.withampersand.com/1.0/projects
URL:  https://proxy.withampersand.com/1.0/projects
URL:  https://proxy.withampersand.com/1.0/teams/1206661566061887
URL:  https://proxy.withampersand.com/1.0/projects/1206808188647461
Requesting a paginated list of projects
Requesting the next page of projects
Closes #354
=> feat: Enable support for asana

providers/catalog.go, providers/catalog_test.go
**SCRIPT:**
**POSTMAN:**
URL: https://proxy.withampersand.com/ex/jira/0bf9b1a5-eebb-4385-ab8c-8cda58854c8e/rest/api/3/dashboard
URL:https://proxy.withampersand.com/ex/jira/0bf9b1a5-eebb-4385-ab8c-8cda58854c8e/rest/servicedeskapi/organization
URL: https://proxy.withampersand.com/ex/jira/0bf9b1a5-eebb-4385-ab8c-8cda58854c8e/rest/api/3/dashboard/10005
URL: https://proxy.withampersand.com/ex/jira/0bf9b1a5-eebb-4385-ab8c-8cda58854c8e/rest/api/3/dashboard/10005
Requesting a paginated list of dashboards using startAt and maxResults:
URL:  https://proxy.withampersand.com/ex/jira/0bf9b1a5-eebb-4385-ab8c-8cda58854c8e/rest/api/3/dashboard?startAt=0&maxResults=1
Requesting the next page using the startAt and …
=> feat: enable Atlassian Proxy support

providers/catalog.go
Remove TokenMetadaFields as these are not expected in the token response
=> Smartsheet remove TokenMetadataFields

providers/catalog.go
Remove tokenMetadatafields as those are not returned with token response
=> Aircall: Remove TokenMetadataFields

providers/catalog.go
None
Retrieving recent files in my personal drive
Retrieving the next page
Closes #236
=> feat: Add oneDrive auth connector

providers/catalog.go
Smartsheet only allows 1 redirect URI, therefore to run token.go, the redirect_uri was switched to localhost and then back to test the proxy.
Fixes #205 
URL: <https://proxy.withampersand.com/2.0/sheets> 
**List sheets**
URL: <https://proxy.withampersand.com/2.0/folders/3384993222289284/sheets> 
**Create a sheet**
URL:<https://proxy.withampersand.com/2.0/sheets/2811605947469700>
**Update the sheet**
URL:<https://proxy.withampersand.com/2.0/sheets/2811605947469700>
**Wrong path**
**List sheets with the amended page size and land on page 3**
=> feat: Enable proxy: Smartsheet

providers/catalog.go
No variables.
Resolves #192 
URL: <localhost:4444/v2/form.json> 
Get all forms in your account
URL: <localhost:4444/v2/form.json> 
Create a new form in your account
URL:<localhost:4444/v2/form/5737097.json>
Update the details of the specified form
URL:<localhost:4444/v2/form/5737097.json>
Delete the specified form
Please add screenshots that show successful pagination using the connector. 
Before pagination, data starts with a form with different ID number
For pagination, selected 10 items per page (minimum) and start with page 2. Form list starts with a different id
=> feat: Add Formstack Connector

providers/catalog.go
Sets proper Grant Type, Token Metadata fields and Explicit Scopes Required fields
fixes #366
=> CloseCRM auth connector update

providers/catalog.go
Added grant_type and token metadata fields to the connector definition. 
fixes #366
=> Zoho CRM auth connector update

providers/catalog.go
URL: <https://proxy.withampersand.com/crm/v6/users/6172731000000476010> 
URL: <https://proxy.withampersand.com/crm/v6/users/6172731000000476010> 
fixes #366
=> feat: Enable proxy: ZohoCRM 

providers/catalog.go
None
URL: http://localhost:4444/v1/organizations/5cf59a25-5063-40e1-826b-5ceaf369b207/fundingsources 
URL: http://localhost:4444/v1/organizations/5cf59a25-5063-40e1-826b-5ceaf369b207/billingcenters
URL:   http://localhost:4444/v1/organizations/5cf59a25-5063-40e1-826b-5ceaf369b207/billingcenters
URL: http://localhost:4444/v1/roles/56f75a35-dbcd-4881-9d79-a3ece51c62c4
Requesting a list of billing-centers
Requesting the next page:
Raw tokens:
Closes #296
=> feat: Add Snapchat Ads Auth connector

providers/catalog.go
URL:  https://proxy.withampersand.com/v1.0/me
URL: https://proxy.withampersand.com/v1.0/me/drive/root/children
URL: https://proxy.withampersand.com/v1.0/me/drive/items/01G350H7R2|GE2VKOUNRD3RYLUJX75X5Y6 
URL: https://proxy.withampersand.com/v1.0/sites/root/yui
Requesting a paginated result of files:
URL: https://proxy.withampersand.com/v1.0/me/drive/root/children?$top=1
URL: https://proxy.withampersand.com/v1.0/me/drive/root/children?$top=1&$skiptoken=UGFnZWQ9VFJVRSZwX1NvcnRCZWhhdmlvcj0xJnBfRmlsZUxlYWZSZWY9QXBwcyZwX0lEPTE
Closes #406
=> feat: Enable Microsoft proxy connector 

providers/catalog.go
URL: <https://proxy.withampersand.com/crm/rest/v1/tasks> 
URL: <https://proxy.withampersand.com/crm/rest/v1/tasks/5>
URL: <https://proxy.withampersand.com/crm/rest/v1/tasks/5>
fixes #366
=> feat: Enable proxy: Keap

providers/catalog.go
Fixes #235 
Could not get a token via script as the redirect_uri is not set to localhost. Obtained the token using https://proxy.withampersand.com
No PATCH method is available
URL: <https://proxy.withampersand.com/v1/users> 
**List users**
URL: <https://proxy.withampersand.com/v1/users> 
**Create a user**
URL: <https://proxy.withampersand.com/v1/users/1304084>
**Update the user**
URL: <https://proxy.withampersand.com/v1/users/1304084>
**DELETE the user**
**Wrong path**
**List users with page and per_page params, next_page_link is indicating more results**
=> Aircall: Enable Proxy

providers/catalog.go
URL: <https://proxy.withampersand.com/v1/account> 
URL: <https://proxy.withampersand.com/v1/people/search?page_size=2&page_number=3> 
URL: <https://proxy.withampersand.com/v1/people/163065117> 
URL: <https://proxy.withampersand.com/v1/people/163065117> 
fixes #366
=> feat: Enable proxy: Copper CRM

common/paramsbuilder/params.go, intercom/params.go
=> tidy up params, add Module description

providers/catalog.go
=> release: enable Intercom read support

providers/catalog.go
* {{scope}}
POST method only supported for /oauth/access_token
Fixes #263 
URL: <localhost:4444/17841466265938546/media?fields=caption,media_type,media_url&access_token={{access_token}}> 
URL<localhost:4444/17841466265938546/media?fields=caption,media_type,media_url&access_token={{access_token}}&limit=1&after=QVFIUmFJcGFmMUtTOG5UZAjhDVVJIb0ZADaGVkQ3djSFVHX2V4aEV6cEFXRkNFcWtIWFhlR0QtMWZAaNmgzUklCZAjFfajg5YU95MGttWmFVaUVLMkpvblM0MExR>
=> Feat/Add Instagram Connector

providers/catalog.go
forgot to enable this when I enabled read.
=> intercom: enable proxy support

providers/catalog.go
Added Grant Type and changed explicit scopes to not required
fixes #366
=> Attio auth connector update 

providers/catalog.go
Grant type was added
fixes #366
=> Keap auth connector update

providers/catalog.go
Added Grant type as requested
fixes #366
=> Pipedrive auth connector update

providers/catalog.go
**SCRIPT:**
**POSTMAN:**
URL: https://proxy.withampersand.com/v5/user_account
URL:https://proxy.withampersand.com/v5/ad_accounts/549767715102/ads
URL: https://proxy.withampersand.com/v5/ad_accounts/549767715102/ads
URL: https://proxy.withampersand.com/v5/pins/1054334962754985321
Requesting a paginated list of ads using page_size:
URL: https://proxy.withampersand.com/v5/ad_accounts/549767715102/ads?page_size=2
Requesting the next page using the bookmark:
URL: https://proxy.withampersand.com/v5/ad_accounts/549767715102/ads?bookmark=P3A2ODcyNjcxOTUzNjd8MHwwfDEsMnwwfDY5NzEwODQ4ODA2NDkyMDgqR1FMKnw1N2JkNTFjZDI5ZDhlMjU3ZjIwMTE1NDYwYmFkYTE3YTVkM2Q1YWVlMmQ0ZDc1NGMwYzZiZGUzOTNlYmMwN2RkfE5FV3w%3D
closes #298
=> feat: enable Pinterest proxy support

providers/catalog.go
=> CapsuleCRM auth connector update

providers/catalog.go
URL: <https://proxy.withampersand.com/v1/contact>
URL: <https://proxy.withampersand.com/v1/contact/>
URL: <https://proxy.withampersand.com/v1/contact/cont_WL4euwSWS4ZeLAmpuwOpAJT6hS8nU1ZY52cSsYcfiTw>
Put failed with the following error message: 
`{
"error": "Referer checking failed: https://proxy.withampersand.com/v1/contact/cont_WL4euwSWS4ZeLAmpuwOpAJT6hS8nU1ZY52cSsYcfiTw does not match https://api.close.com/."
}`
URL: <https://proxy.withampersand.com/v1/contact/cont_WL4euwSWS4ZeLAmpuwOpAJT6hS8nU1ZY52cSsYcfiTw>
URL: <https://proxy.withampersand.com/v1/contact?_skip=0&_limit=2> 
has_more flag is true, navigating to the last page
Last page
URL: <https://proxy.withampersand.com/v1/contact?_skip=5&_limit=2>
fixes #366
=> feat: Enable proxy: CloseCRM

providers/catalog.go
TeamleaderCRM Provider = "teamleaderCRM"
**SCRIPT:**
**POSTMAN:**
URL: http://localhost:4444/contacts.info
URL: http://localhost:4444/contacts.add
URL: http://localhost:4444/contacts.update
URL: http://localhost:4444/contacts.delete
Requesting a paginated list of contacts using the size and number field in the page object in the request body:
URL: http://localhost:4444/contacts.list
Requesting the next page using size as 5 and number as 2
Closes #440
=> feat: Add TeamleaderCRM Auth connector

providers/catalog.go
Closes https://github.com/amp-labs/connectors/issues/382
List users.
```
curl --location --request GET 'https://proxy.withampersand.com/v1/users' \
--header 'x-amp-installation-id: 39c27908-1e76-414f-b4e5-5e7e4514c1cb' \
--header 'x-api-key: <API_KEY>' 
```
Create competitor.
```
curl --location --request POST 'https://proxy.withampersand.com/v1/products/7369704810818432305/competitors' \
--header 'x-amp-installation-id: 39c27908-1e76-414f-b4e5-5e7e4514c1cb' \
--data-raw '{
"name": "Rival",
"color": "Purple" …
```
=> feat: Enable proxy: Aha!

providers/catalog.go
Closes #446 
"workspace": "ampersanddemo"
"scopes": "offline_access seismic.self.view seismic.self.manage seismic.user.view seismic.user.manage seismic.planner.view seismic.planner.manage"
Token endpoint to acquire Refresh token differs from the one used to exchange auth code for Access Token.
However, it doesn't look critical. Removing URI fragment of `#a` has no impact and I still can generate the access token.
Maybe docs, add this fragment just to be explicit but no functional difference happens. I have set expiry date to be stale and Oauth2 golang library indeed invokes refresh using this AuthURL and proxy functions as expected. So refresh also doesnt need `#r` URI gragment.
```
Docs:
https://auth.seismic.com/tenants/{{.workspace}}/connect/token#a        AuthCode grant type …
```
=> feat: Add Seismic auth connector

providers/catalog.go
=> chore: rename Dynamics Business Central connector

providers/catalog.go
URL: https://proxy.withampersand.com/v2/users
URL: https://proxy.withampersand.com/v2/calls
URL: https://proxy.withampersand.com/v2/meetings/3565421440941204730
URL: https://proxy.withampersand.com/v2/meetings/3565421440941204730
Requesting paginated list of calls
URL: https://proxy.withampersand.com/v2/calls
URL: https://proxy.withampersand.com/v2/calls?cursor=eyJhbGciOiJIUzI1NiJ9.eyJjYWxsSWQiOjQ5NTM3MDc2MDE3NzYyMzgzNjAsInRvdGFsIjoxNzksInBhZ2VOdW1iZXIiOjAsInBhZ2VTaXplIjoxMDAsInRpbWUiOiIyMDIyLTA5LTEzVDA5OjMwOjAwWiIsImV4cCI6MTcxNjcyOTE3N30.SnUBs549FQzluSJ8k0aJ4XPzkKePGkFc98cHAkSKGbQ
Closes #433
=> feat: enable proxy: gong

providers/catalog.go
Slugs are also supported by the connector, i.e. https://proxy.withampersand.com/v2/lists/new_test_list_2/entries/1c4b7652-3305-44f9-b911-60370f02025f works, the **new_test_list_2** is replaced with the ID, it also works, i.e. https://proxy.withampersand.com/v2/lists/cff6cab2-0184-4730-9735-4bc60985fc24/entries/1c4b7652-3305-44f9-b911-60370f02025f works just fine. 
URL: <https://proxy.withampersand.com/v2/lists> 
URL: <https://proxy.withampersand.com/v2/lists/cff6cab2-0184-4730-9735-4bc60985fc24/entries> 
URL: <https://proxy.withampersand.com/v2/lists/cff6cab2-0184-4730-9735-4bc60985fc24/entries/1c4b7652-3305-44f9-b911-60370f02025f> 
URL: <https://proxy.withampersand.com/v2/lists/cff6cab2-0184-4730-9735-4bc60985fc24/entries/1c4b7652-3305-44f9-b911-60370f02025f>
token.go script fails as …
=> feat: Enable proxy: Attio

providers/catalog.go
URL: <https://proxy.withampersand.com/v4/invitations> 
URL: <https://proxy.withampersand.com/v4/invitations?email=example7@example.com> 
URL: <https://proxy.withampersand.com/v4/invitations/IEAGGK6OJEAR3RVY?role=Collaborator> 
URL: <https://proxy.withampersand.com/v4/invitations/IEAGGK6OJEAR3RVY> 
closes #366
=> feat: Enable proxy: Wrike

providers/catalog.go
URL: <https://proxy.withampersand.com/v1/deals?start=0&limit=5> 
URL: <https://proxy.withampersand.com/v1/deals> 
URL: <hhttps://proxy.withampersand.com/v1/deals/2> 
URL: <hhttps://proxy.withampersand.com/v1/deals/2> 
Trying to delete a record that was already deleted
First page, offset pagination, 2 parameters
Last page will contain the following code in the response
fixes #366
=> feat: Enable proxy: Pipedrive

providers/catalog.go
Requesting paginated list of subscribers
Requesting the next page of results.
Closes #418
=> feat: enable AWeber proxy connector

providers/catalog.go
Closes #314 
URL: https://proxy.withampersand.com/contacts
create contact
URL: https://proxy.withampersand.com/contacts?email=<email>
get contacts sharing the same email
URL: https://proxy.withampersand.com/contacts/<id>
update contact
URL: https://proxy.withampersand.com/contacts/<id>
delete contact
URL: https://proxy.withampersand.com/contacts?email=<email>&limit=2 
limit number of contacts retrieved to 2
URL: https://proxy.withampersand.com/conversations/3976878541/messages
get messages - first page
###GET 
URL: https://proxy.withampersand.com/conversations/3976878541/messages?next=16482381378
get messages - second page
=> feat: Enable proxy: Drift

providers/catalog.go
All proxy endpoint fail with 502 Bad Gateway error
URL: <https://proxy.withampersand.com/v2/kases/4827250> 
URL: <https://proxy.withampersand.com/v2/kases/4827250> 
N/A
N/A
fixes #366
=> feat: Enable proxy: CapsuleCRM 

providers/catalog.go
URL: <https://proxy.withampersand.com/v2/kases/4827250> 
URL: <https://proxy.withampersand.com/v2/kases/4827250> 
URL: <https://proxy.withampersand.com/v2/kases/4827250> 
URL: <https://proxy.withampersand.com/v2/kases/4827250> 
fixes #366
=> feat: Enable proxy: CapsuleCRM

providers/catalog.go
See comment in the code for more context.
=> chore: temporarily set DynamicsCRM ExplicitWorkspaceRequired to true

providers/catalog.go
URL: <https://proxy.withampersand.com/v19.0/act_1387578721957903/adsets> 
URL: <https://proxy.withampersand.com/v19.0/act_1387578721957903/adsets> 
URL: <https://proxy.withampersand.com/v19.0/search?location_types=["country1"]&type=adgeolocation&access_token={{access_token}}&limit=25&offset=25> 
fixes #283
=> feat: Enable proxy: Facebook Ads Manager

scripts/bash/pr_options.sh
PR links are generated for development via `Fork` or `Directly` on this repo.
=> chore: Edit PR-template script; URLs for Fork/Local dev

providers/catalog.go
Closes #445 
The baseURL requires `account.Id` value. It's represented by the variable `workspace`
The AuthURL and TokenURLs requires params that I have added manually in the URLs.
URL:  http://localhost:4444/buckets/37715752/todosets/7448733309.json
URL: http://localhost:4444/buckets/37715752/todolists/7448734530/todos.json
URL: http://localhost:4444/buckets/37715752/todos/7448736622.json
URL: http://localhost:4444/buckets/37715752/todos/7448857223.json
Requesting a paginated list of todos.
URL: http://localhost:4444/buckets/37715752/todolists/7448734530/todos.json
Using the Link header response to fetch the next page responses.
URL: http://localhost:4444/buckets/37715/52/todolists/7448734530/todos.json?page=2>;
=> feat: Add Basecamp auth connector

providers/catalog.go
Workspace represents the tenant-name.  
Requesting for a paginated data:
Using the `@odata.nextLink` to access the next page data
As observed we are in the last page, no more pages.
Closes  #245
=> feat: Add sharePoint auth connector

gong/parse.go, gong/read.go, gong/read_test.go, providers/utils.go, test/gong/read/read.go
fixing linter issues on main branch
=> lint: making Linter happy

README.md, common/types.go
The basic package have been renamed to connector.
=> docs: Update naming

dynamicscrm/connector.go, dynamicscrm/params.go, providers/catalog.go, test/dynamicscrm/connector.go
Linter: https://github.com/amp-labs/connectors/pull/480
=>  fix: remove Module support DynamicsCRM

salesloft/connector.go, salesloft/params.go, salesloft/read_test.go, test/salesloft/connector.go
Linter: https://github.com/amp-labs/connectors/pull/480
=> fix: remove Module support Salesloft

providers/catalog.go
Fixes #192 
Could not get the token through token.go as localhost URI is not supported.
URL: <https://proxy.withampersand.com/v2/form.json> 
**Get all forms in your account**
URL: <https://proxy.withampersand.com/v2/form.json> 
**Create a new form in your account**
URL: <https://proxy.withampersand.com/v2/form/5784133.json>
**Update the form**
URL: <https://proxy.withampersand.com/v2/form/5784133.json> 
**Delete the form**
**Wrong path**
**After pagination. The forms array starts with a different form id**
=> Feat/ Formstack: Enable Proxy

providers/catalog.go
Closes #396 
use v3 in the API call
URL: <localhost:4444/v3/contacts>
URL: <localhost:4444/v3/contacts> 
URL:<localhost:4444/v3/contacts/6703796936>
URL:<localhost:4444/v3/contacts/6703796936>
URL:<localhost:4444/v3/contacts/6703796936>
2 items per page, land on page 2,links for the previous/next/first/last pages are displayed at the bottom
=> SurveyMonkey: add connector

.github/workflows/generate-json-catalog.yaml, scripts/catalog/json.go
Whenever a catalog change goes in, this will generate a JSON file that we can then refer to for our usage, without having to update dependencies on this repo.
=> [ENG-1232] Create a JSON catalog when the catalog changes

providers/catalog.go
fix #377 
correcting GitHub connectors ExplicitScopesRequired field
=> fix: set Github ExplicitScopesRequired to true

providers/catalog.go
Update the connector as it has a 2-legged authentication type.
=> Zuora: Update the connector

providers/catalog.go
Closes #508 
None
Requesting first page of campaigns
Requesting next page using both `pere_page` and `page`
=> feat: Add Blueshift auth connector

providers/catalog.go
Closes #522 
use /v1/ in the API call
Token cannot be printed as it is generated on the platform
URL: <localhost:4444/v1/insightsreports> 
URL: <localhost:4444/v1/insightsreports> 
URL: <localhost:4444/v1/insightsreports/666e563ed85060476150c3ef> 
URL: <localhost:4444/v1/insightsreports/666e563ed85060476150c3ef> 
**GET Without pagination**
**GET With pagination using the limit and next parameters**
=> Mixmax: Add a connector

providers/catalog.go
Context: The latest PR merge #553 was uncleanly rebased.This adds the truncated code.
=> fix: Re-adds BlueshiftEU

providers/catalog.go, scripts/proxy/proxy.go
Closes #540 
URL: http://localhost:4444/v2/leads
URL: http://localhost:4444/v2/leads/<id>
URL: http://localhost:4444/v2/leads/<id>
URL: http://localhost:4444/v2/leads/<id>
URL: http://localhost:4444/v2/domain-search?domain=<domain>&limit=2
URL: http://localhost:4444/v2/domain-search?domain=<domain>&limit=2&offset=2
=> feat: Add Hunter connector

providers/catalog.go
URL: <https://proxy.withampersand.com/rest/adAccounts/513164457/adCampaignGroups?q=search&search=(status:(values:List(ACTIVE)))&pageSize=2> 
URL: <https://proxy.withampersand.com/rest/adAccounts/513164457/adCampaignGroups> 
fixes #284
=> feat: enable LinkedIn Ads Manager proxy connector 

providers/amplitude.go, scripts/proxy/proxy.go
Closes #541 
- Amplitude has different sets APIs that are exclusively accessible via Basic Auth or API Key. This connector only support the Basic Auth APIs.
- Among the basic Auth API, this connector only support those with base url https://amplitude.com/api
Find a complete list here https://ampersand.slab.com/posts/amplitude-connector-1dahs0op#hnus0-list-of-api-modules-objects-or-api-categories
- This connectors API do not support pagination or batching 
URL: http://localhost:4444/api/2/taxonomy/category
URL: http://localhost:4444/api/2/taxonomy/category
URL: http://localhost:4444/api/2/taxonomy/category/<id>
URL: http://localhost:4444/api/2/taxonomy/category/<id>
URL: http://localhost:4444/api/2/annotations
URL: http://localhost:4444/api/2/annotations?app_id=<id>=<date>&label=<label>&det …
=> feat: Add Amplitude connector

providers/messageBird.go
This was removed incorrectly in here #550
=> fix: Update messageBird connector

providers/blueshift.go
This was removed incorrectly in here #550
=> fix: Update Blueshift connector

providers/chartMogul.go
Closes #558 
use v1 in the endpoint when making an API call
URL: <localhost:4444/v1/data_sources> 
URL: <localhost:4444/v1/customers> 
URL: <localhost:4444/v1/customers/cus_571b56c4-2e2b-11ef-8252-df4b97ded2be> 
URL: <localhost:4444/v1/customers/cus_571b56c4-2e2b-11ef-8252-df4b97ded2be>
Please add screenshots that show successful pagination using the connector. 
**List Customers without pagination. Shows that it has more pages to show**
**List customers with cursor pagination. The screenshot of the last page**
Could not print the token as it is generated on the platform.
=> Add ChartMogul connector

providers/recurly.go
Closes #520 
include version in the headers `Accept: application/vnd.recurly.v2021-02-25`
Not possible to print out the token as it is generated in platform.
URL: <localhost:4444/accounts> 
URL: <localhost:4444/accounts> 
URL: <localhost:4444/accounts/code-2> 
URL: <localhost:4444/accounts/code-2> 
**After pagination with limit and cursor params included**
=> Add Recurly Connector

providers/freshdesk.go
Closes #593 
When adding the API key to the username, the password is not required.
URL: <localhost:4444/v2/contacts> 
URL: <localhost:4444/v2/contacts> 
URL: <localhost:4444/v2/contacts/154019070798> 
URL: <localhost:4444/v2/contacts/154019070798> 
**After pagination with `page` and `per_page` params added. In headers response the link to the next page is shown**
=> Feat add Freshdesk connector

providers/stripe.go
Closes #583 
URL: http://localhost:4444/v1/payment_intents
URL: http://localhost:4444/v1/payment_intents/id
URL: http://localhost:4444/v1/payment_intents/id
page 1
URL: http://localhost:4444/v1/payment_intents
URL: http://localhost:4444/v1/payment_intents
=> feat: Add Stripe  connector

providers/freshsales.go
Closes #592 
<Please mention any variables you had to use for the provider's info>
No API version in end endpoint
URL: <localhost:4444/api/sales_accounts/view/28003422472>
URL: <localhost:4444/api/sales_accounts> 
URL: <localhost:4444/v2/28002327739> 
URL: <localhost:4444/v2/28002327739> 
**Before pagination, showing that the total number of pages is 2**
**After pagination, with `page` parameter**
=> Feat: add Freshsales connector

providers/gorgias.go
Closes #378 
URL: http://localhost:4444/api/customers/id/
URL: http://localhost:4444/api/customers 
URL: http://localhost:4444/api/customers/id/
URL: http://localhost:4444/api/customers/id/
=> feat: Add Gorgias connector

providers/freshservice.go
Closes #591 
<Please mention any variables you had to use for the provider's info>
URL: <localhost:4444/api/v2/tickets> 
URL: <localhost:4444/v2/tickets> 
URL: <localhost:4444/v2/tickets/6> 
URL: <localhost:4444/api/v2/tickets/6> 
**After pagination with `per_page` and `page` parameter. The response header includes link to the next page**
=> Feat: add Freshservice connector

providers/redditAds.go
Adding the configuration as is for now. Will be tested in the future.
Closes #286
=> feat: Add RedditAds auth connector

examples/auth_connectors/salesforce/salesforce.go, providers/shopify.go
Closes #611 
version is 2024-04
URL: <localhost:4444/admin/api/2024-04/customers/count.json> 
URL: <localhost:4444/admin/api/2024-04/customers.json> 
URL: <localhost:4444/admin/api/2024-04/customers/7440405528792.json>
URL: <localhost:4444/admin/api/2024-04/customers/7440405528792.json> 
**After pagination with `limit`, `page_info` and `rel` parameters**
=> Feat/Add Shopify Connector

outreach/README.md
This adds all supported Objects in the deep connector, Together with the methods supported.
=> docs: update outreach documentation

providers/powerBI.go
Closes #628 
None
Requesting A paginated list of groups.
Using the query parameters ` $skip ` and ` $top ` to retrieve next page records
=> feat: Add Power BI auth connector

providers/google.go, providers/redditAds.go
Adds extra auth URL params that these connectors need to return a refresh token.
=> [ENG-1268] Add auth URL options for reddit ads and google

providers/rebilly.go
- [] Ran Linter
- [] Created PR from non-main branch
Rebilly Provider = "rebilly"
It supports pagination. 
URL: http://localhost:4444/organizations/org_01J21N29CQQBY091TFSAT2BYJ7/customers
URL: http://localhost:4444/organizations/org_01J21N29CQQBY091TFSAT2BYJ7/customers
URL: http://localhost:4444/organizations/org_01J21N29CQQBY091TFSAT2BYJ7/customers/cus_01J2988GXMSB76JVME8XDEZXMY
URL: http://localhost:4444/organizations/org_01J21N29CQQBY091TFSAT2BYJ7/customers/cus_01J28H630K6AF9DT2JQ1C7Q05M?targetCustomerId=cus_01J28F3G3FXJQTS9RBKYG9WG7X
Requesting a paginated list of customers using limit:
URL: http://localhost:4444/organizations/org_01J21N29CQQBY091TFSAT2BYJ7/customers?limit=3
Requesting a paginated list of customers using limit and offset:
URL: …
=> feat: Add Rebilly Connector

providers/maxio.go
Closes #641 
* {{workspace}} 
URL: <localhost:4444/customers.json> 
URL: <localhost:4444/customers.json> 
URL: <localhost:4444/customers/80924414.json> 
URL: <localhost:4444/customers/80924414.json> 
**After pagination with `page` and `per_page` parameters**
=> Feat/Add Maxio Connector

providers/coda.go, scripts/proxy/proxy.go
Closes #637 
URL: http://localhost:4444/v1/docs
URL: http://localhost:4444/v1/docs/id
URL: http://localhost:4444/v1/docs/id
URL: http://localhost:4444/v1/docs/id
URL: http://localhost:4444/v1/docs?limit=2
URL: http://localhost:4444/v1/docs?limit=2&pageToken=pageToken
=> feat: Add Coda connector

providers/paddle.go
PaddleSandbox Provider = "paddleSandbox"
Paddle        Provider = "paddle"
It supports pagination and Batching.
URL: http://localhost:4444/customers/ctm_01j20svcdtqv6dkejgqk6d93qr
URL: http://localhost:4444/customers
URL: http://localhost:4444/customers/ctm_01j20svcdtqv6dkejgqk6d93qr
Requesting a paginated list of customers using per_page:
URL: http://localhost:4444/customers?per_page=2
Requesting a paginated list of customers using per_page and after:
URL: http://localhost:4444/customers?after=ctm_01j20szmkbt2j1j204t8g03wyz&per_page=2
Closes #642
=> feat: Add Paddle Connector

providers/chargeOver.go
Closes #667 
* {{.workspace}}
URL: http://localhost:4444/api/v3/customer
URL: http://localhost:4444/api/v3/customer/id
URL: http://localhost:4444/api/v3/customer/id
URL: http://localhost:4444/api/v3/customer/id
URL: http://localhost:4444/api/v3/customer?limit=2&offset=0
URL: http://localhost:4444/api/v3/customer?limit=2&offset=2
=> feat: Add ChargeOver connector

providers/acuityScheduling.go
AcuityScheduling Provider = "acuityScheduling"
Acuity Scheduling doesn't support pagination currently. Some of the APIs have a max query param which is used to limit the number of results. Batch Processing is not supported.
**SCRIPT:**
**POSTMAN:**
URL: https://proxy.withampersand.com/api/v1/clients
URL: https://proxy.withampersand.com/api/v1/clients
URL: https://proxy.withampersand.com/api/v1/clients?firstName=ampersand&lastName=connector03
URL: https://proxy.withampersand.com/api/v1/clients?firstName=ampersand&lastName=connector03
closes #442
=> feat: enable acuityScheduling proxy support

test/utils/mockutils/checks.go, test/zendesksupport/write-delete/main.go, zendesksupport/delete.go, zendesksupport/delete_test.go, zendesksupport/errors.go, zendesksupport/read_test.go, zendesksupport/test/create-brand.json, zendesksupport/test/duplicate-error.json, zendesksupport/test/missing-parameter.json, zendesksupport/test/record-validation.json, zendesksupport/test/server-error.json, zendesksupport/write.go, zendesksupport/write_test.go
Closes https://github.com/amp-labs/connectors/issues/616
=> feat: Deep connector Zendesk Support (Write)

providers/callRail.go
Closes #684 
URL: http://localhost:4444/v3/a/account-id/companies.json
URL: http://localhost:4444/v3/a/account-id/companies/company-id.json
URL: http://localhost:4444/v3/a/account-id/companies/company-id.json
URL: http://localhost:4444/v3/a/account-id/companies/company-id.json
URL: http://localhost:4444/v3/a/account-id/companies.json?page=1&per_page=2
URL: http://localhost:4444/v3/a/account-id/companies.json?page=2&per_page=2
=> feat: Add CallRail connector

providers/atlassian.go, providers/chargebee.go
=> docs: displayname for Chargebee and Atlassian connectors

test/pipeliner/connector.go, test/salesforce/connector.go, tools/fileconv/files.go, tools/scrapper/files.go
=> tidy: Metadata locator becomes general locator

common/paramsbuilder/params.go, connector/connector.go, connector/params.go, docusign/connector.go, docusign/params.go, dynamicscrm/connector.go, dynamicscrm/params.go, gong/connector.go, gong/params.go, hubspot/connector.go, hubspot/params.go, intercom/connector.go, intercom/params.go, outreach/connector.go, outreach/params.go, salesforce/connector.go, salesforce/params.go, salesloft/connector.go, salesloft/params.go, tools/connectorgen/template/base/connector.go.tmpl, tools/connectorgen/template/base/params.go.tmpl, zendesksupport/connector.go, zendesksupport/params.go
This adds simple generics constructor/builder for connector options.
It figures out the parameters type, performs validation and applies any parameter modifications.
=> add: Create connector options, genrics

common/scanning/credscanning/fields.go, common/scanning/credscanning/provider.go, scripts/proxy/proxy.go, test/dynamicscrm/connector.go, test/salesforce/connector.go, test/utils/creds.go, test/zendesksupport/connector.go
https://github.com/amp-labs/connectors/pull/714
=> fix: Workspace check toggle, creds scanning

pipeliner/delete.go, pipeliner/delete_test.go, pipeliner/errors.go, pipeliner/test/create-entity-validation.json, pipeliner/test/create-invalid-body.json, pipeliner/test/create-note.json, pipeliner/test/delete-note.json, pipeliner/test/update-note.json, pipeliner/write.go, pipeliner/write_test.go, test/pipeliner/write-delete/main.go
=> feat: Deep connector Pipeliner (Write)

common/handy/lists.go, common/handy/maps.go, common/handy/set.go, test/pipeliner/connector.go, tools/fileconv/files.go, tools/scrapper/files.go
Simplistic version of Set data structure.
=> add: Set data structure

providers/dynamics.go
Webhook recieved data.
Create contact.
Create account.
Create lead.
Update lead.
=> feat: Enable Read+Write: Dynamics CRM

providers/google.go
=> add: Logo - Google

providers/webflow.go
Add Icon and Logo URLs to webflow connector
=> feat: Add media to webflow

providers/zoom.go
Add Icon and Logo URLs to zoom connector
=> feat: Add media to zoom

providers/docusign.go
Add Icon and Logo URLs to docusign connector
=> feat: Add media to docusign

providers/figma.go
Add Icon and Logo URLs to figma connector
=> feat: Add media to figma

providers/gainsight.go
Add Icon and Logo URLs to gainsight connector
=> Add gainsight media

providers/clari.go
Add Icon and Logo URLs to Clari connector
=> Feat: Add media to Clari

providers/getResponse.go
Add Icon and Logo URLs to Getresponse connector
=> feat: Add media to getresponse

providers/discord.go
Add Icon and Logo URLs to discord connector
=> feat: Add media to discord

providers/adobe.go
Add Icon and Logo URLs to Adobe Experience Platform
=> Feat: Add media to Adobe Experience Platform

providers/aircall.go
Add Icon and Logo URLs to Aircall connector
=> Feat: Add media to Aircall

providers/chartMogul.go
Add Icon and Logo URLs to ChartMogul connector
=> Feat: Add media to ChartMogul

providers/formstack.go
Add Icon and Logo URLs to Formstack connector
=> Feat: Add media to Formstack

providers/front.go
Add Icon and Logo URLs to Front connector
=> Feat: Add media to Front

providers/geckoboard.go
Add Icon and Logo URLs to Geckoboard connector
=> Feat: Add media URLs to Geckoboard

providers/helpScoutMailbox.go
Add Icon and Logo URLs to Help Scout Mailbox connector
=> Add media for HelpScoutMailbox

providers/instagram.go
Add Icon and Logo URLs to Instagram connector
=> Add media to Instagram

providers/iterable.go
Add Icon and Logo URLs to Iterable connector
=> Feat: Add media to Iterable

providers/mailgun.go
Feat: Add Icon and Logo URLs to Mailgun connector
=> Feat: Add media URLs to Mailgun

providers/smartsheet.go
Add media URLs for Smartsheet connector
=> Add Icon and Logo to Smartsheet

providers/stackExchange.go, providers/surveyMonkey.go
Add Icon and Logo URL's to Survey Monkey
=> Feat: Add media URLs for Survey Monkey

providers/stackExchange.go, providers/zuora.go
Add media URLs for Zuora and StackExchange
=> Feat: Add Icon and Logo for Zuora and StackExchange

providers/slack.go
Add icon and logo URLs to Slack connector
=> Add media to Slack

providers/wordPress.go
Add Icon and Logo URLs to WordPress connector
=> feat: Add media to wordpress

providers/sugarCRM.go
=> add: Logo - Sugar

providers/seismic.go
=> add: Logo - Seismic

providers/monday.go
=> add: Logo - Monday

providers/mailgun.go
Just adds a docs URL for mailgun authn
=> feat: Add Mailgun docs URL

providers/openAI.go
=> add: Logo - OpenAI

providers/anthropic.go
=> add: Icon - Anthropic

providers/aha.go
=> add: Logo - Aha

providers/typeform.go
=> add: Logo - Typeform

providers/calendly.go
=> add: Logo - Calendly

providers/dynamics.go
Bussiness central and dynamics share the same Media.
=> add: Logo - DynamicsCRM

providers/customer.go
3 connectors share the same Media.
=> add: Logo - Customer

providers/serviceNow.go
Add Icon and Logo URLs to Servicenow connector.
=> feat: Add media to Servicenow

providers/teamwork.go
Add Icon and Logo URLs to Teamwork connector.
=> feat: Add media to Teamowrk

providers/box.go
Add Icon and Logo URLs to Box connector
=> feat: Add media to Box

providers/insightly.go
Add Icon and Logo URLs to Insightly connector.
=> feat: Add media to Insightly

providers/drift.go, test/utils/mockutils/metadataResult.go
Add Icon and Logo URLs to Drift connector.
=> Add drift media

providers/github.go, test/utils/mockutils/metadataResult.go
Add Icon and Logo URLs to Gtihub connector.
=> feat: Add media to Github

providers/miro.go, test/utils/mockutils/metadataResult.go
=> feat: Add media to Miro

providers/paddle.go
Add Icon and Logo URLs to Paddle connector.
=> feat: Add media to paddle

providers/hive.go
Add Icon and Logo URLs to Hive connector.
=> feat: Add media to hive

providers/domo.go, test/utils/mockutils/metadataResult.go
Add Icon and Logo URLs to Miro connector
=> feat: Add media to Domo

providers/stripe.go, test/utils/mockutils/metadataResult.go
=> feat: Add media to Stripe

providers/hunter.go, test/utils/mockutils/metadataResult.go
Add Icon and Logo URLs to Hunter connector.
=> feat: Add media to Hunter

providers/amplitude.go, test/utils/mockutils/metadataResult.go
=> feat: Add media to Amplitude

providers/gorgias.go
Add Icon and Logo URLs to Gorgias connector.
=> feat: Add media to Gorgias

providers/coda.go
=> feat: Add media to Coda

providers/acuityScheduling.go
Add Icon and Logo URLs to Acuity Scheduling connector
=> feat: Add media to Acuity Scheduling

providers/rebilly.go
Add Icon and Logo URLs to Rebilly connector.
=> feat: Add media to rebilly

providers/nutshell.go
Add Icon and Logo URLs to nutshell connector.
=> feat: Add media to nutshell

providers/apollo.go
Add Icon and Logo URLs to Apollo connector.
=> feat: Add media to Apollo

providers/callRail.go
Add Icon and Logo URLs to CallRail connector.
=> feat: Add media to CallRail

providers/zoho.go
Add Icon and Logo URLs to Zoho connector.
=> feat: Add media to Zoho

providers/wrike.go
Add Icon and Logo URLs to Wrike connector.
=> feat: Add media to wrike

providers/salesforce.go
Add Icon and Logo URLs to Salesforce connector.
=> feat: Add media to Salesforce

providers/ringCentral.go
Add Icon and Logo URLs to RingCentral connector.
=> feat: Add media to RingCentral

providers/mural.go
Add Icon and Logo URLs to Mural connector.
=> feat: Add media to Mural

providers/types.gen.go
I just ran `cd providers && make gen/catalog`
=> chore: update from latest OpenAPI definitions

providers/close.go
Add Icon and Logo URLs to Close connector.
=> feat: Add media to close connector

providers/capsule.go
Add Icon and Logo URLs to Capsule connector.
=> feat: Add media to Capsule connector

providers/attio.go
Add Icon and Logo URLs to Attio connector.
=> feat: Add media to Attio

providers/dropbox.go
Add Icon and Logo URLs to Dropbox connector.
=> Add dropbox media

providers/atlassian.go
Add Icon and Logo URLs to Atlassian connector.
=> feat: Add media to Atlassian

providers/linkedIn.go
Add Icon and Logo URLs to LinkedIn connector
=> Feat: Add media to LinkedIn connector

providers/hubspot.go
Add Icon and Logo URLs to Hubspot.
=> Feat: Add media to hubspot

providers/facebook.go
Add Icon and Logo URLs media to Facebook.
=> Feat: Add media to Facebook

providers/clickup.go
=> media: add logo for Clickup

atlassian/delete.go, atlassian/delete_test.go, atlassian/errors.go, atlassian/test/create-issue-invalid-project.json, atlassian/test/create-issue-invalid-type.json, atlassian/test/create-issue.json, atlassian/test/delete-issue-not-found.json, atlassian/write.go, atlassian/write_test.go, test/atlassian/write-delete/main.go
Closes #709
Implementation of Write/Delete Jira issues.
=> feat: Deep connector Jira (Write)

providers/outreach.go
Used this configuration [file](https://github.com/amp-labs/testdata/blob/main/outreach/amp.yaml) to create the integration.
Reading `accounts`:
Reading `mailings`:
Reading `sequences`:
=> feat: enable outreach read

providers/seismic.go
Closes #446 
List spaces.
```
GET 'https://proxy.withampersand.com/planner/v2/spaces'
```
Create task.
```
curl --location --request POST 'https://proxy.withampersand.com/planner/v2/spaces/nkARs04q9U6mZu1tHJ3U2A/tasks' \
--data-raw '{
"title": "[Task] Finish integration testing"
}'
```
Update task.
```
curl --location --request PUT 'https://proxy.withampersand.com/planner/v2/spaces/nkARs04q9U6mZu1tHJ3U2A/tasks/lGbpFDbIy0CKWXR2ijNdUg' \
--data-raw '{
"title": "Brand new task title"
}'
```
Remove task.
```
DELETE 'https://proxy.withampersand.com/planner/v2/spaces/nkARs04q9U6mZu1tHJ3U2A/tasks/JzrUpM7QAE-8mQ3msAM4Bw'
```
Post on singular resource:
Get projects.
```
GET …
```
=> feat: Enable proxy: Seismic

.github/PULL_REQUEST_TEMPLATE/new_connector.md
Update PR template to include:
* Logo, icons section
* Raw token response for Oauth2
=> tidy: Update New auth connector PR template

providers/sendGrid.go
Closes #510 
List templates.
```
curl --location --request GET 'https://proxy.withampersand.com/v3/templates?generations=dynamic' \
--header 'x-amp-installation-id: 0424a8a3-bd49-4f62-8cb3-6231372d7426' \
--header 'x-api-key: <API_KEY>'
```
Create a template.
```
curl --location --request POST 'https://proxy.withampersand.com/v3/templates' \
--header 'x-amp-installation-id: 0424a8a3-bd49-4f62-8cb3-6231372d7426' \
--data-raw '{
"name": "Wonderful Template",
"generation": "dynamic",
"version": ["1.2"]
}'
``` …
=> feat: Enable proxy: SendGrid

providers/pipeliner.go
Closes #580
List profiles.
```
curl --location --request GET 'https://proxy.withampersand.com/api/v100/rest/spaces/fr_myself1/entities/Profiles' \
--header 'x-amp-installation-id: c8138442-f32d-4d0e-a86d-bf58a6ce8435' \
--header 'x-api-key: <API_KEY>'
```
Create a note.
```
curl --location --request POST 'https://proxy.withampersand.com/api/v100/rest/spaces/fr_myself1/entities/Notes' \
--header 'x-amp-installation-id: c8138442-f32d-4d0e-a86d-bf58a6ce8435' \
--header 'x-api-key: <API_KEY>'
```
Update a note.
```
curl --location --request PATCH …
```
=> feat: Enable proxy: Pipeliner

providers/bird.go
invalid path.
Retrieving a paginated list of channelscontacts.
Using the `pageToken` query parameter to retrieve the next page contacts.
=> feat: enable proxy bird

providers/front.go
Closes #344 
URL: <https://proxy.withampersand.com/conversations> 
URL: <https://proxy.withampersand.com/inboxes> 
URL: <https://proxy.withampersand.com/conversations/cnv_1alzn15o/assignee> 
URL: <https://proxy.withampersand.com/inboxes/inb_e5vfg> 
URL: <https://proxy.withampersand.com/conversations/cnv_1alzn15o/tags> 
**Wrong path**
Get request with `limit` and `page_token` parameters
Not applicable as the connector supports ApiKey type of authentication
=> Feat: Front enable proxy

providers/brevo.go
Wrong verb applied 
invalid path.
Using `limit` and `offset` for pagination.
Retrieving the next page data.
We have reached the last page as `count` < `offset` + `limit`
=> feat: enable proxy brevo

providers/chartMogul.go
Closes #558 
Note: Post request was not successful due to the expiration of the subscription
URL: <https://proxy.withampersand.com/v1/customers> 
URL: <https://proxy.withampersand.com/v1/data_sources> 
URL: <https://proxy.withampersand.com/v1/customers/cus_811bf4f0-2e2c-11ef-a4e
3-3beb15f0df73> 
URL: <https://proxy.withampersand.com/v1/customers/cus_811bf4f0-2e2c-11ef-a4e3-3beb15f0df73> 
**Invalid method**
**Invalid path**
Get request with `per_page` and `cursor` parameters
Token response is not available as the connector supports Basic authentication
=> Feat: Enable proxy for chartMogul

providers/clari.go
Closes #559 
URL: <https://proxy.withampersand.com/v4/audit/events> 
URL: <https://proxy.withampersand.com/v4/export/audit/events> 
**Invalid path**
**Invalid method**
**Get request with `limit` and `offset` parameters**
Not available as the connector supports ApiKey authentication
=> Feat: Enable proxy for Clari

providers/dixa.go
Close #638 
URL: <https://proxy.withampersand.com/v1/agents> 
URL: <https://proxy.withampersand.com/v1/agents> 
URL: <https://proxy.withampersand.com/v1/agents/ea5142c4-e097-4ea0-a2f5-13bfed8685a4> 
URL: <https://proxy.withampersand.com/v1/agents/ea5142c4-e097-4ea0-a2f5-13bfed8685a4> 
URL: <https://proxy.withampersand.com/v1/agents/ea5142c4-e097-4ea0-a2f5
-13bfed8685a4> 
**Invalid path**
**Invalid endpoint**
Get request with `pageKey` param
Not applicable as the connector has the API Key authentication
=> Feat: Enable proxy for Dixa

providers/g2.go
Closes #462 
URL: http://localhost:4444/api/v2/products
URL: http://localhost:4444/api/v2/products?page[size]=5&page[number]=1
URL: http://localhost:4444/api/v2/products?page[size]=5&page[number]=2
=> feat: Add G2 connector

providers/iterable.go
Closes #458 
URL: <https://proxy.withampersand.com/api/catalogs/catalogName/items> 
URL: <https://proxy.withampersand.com/api/catalogs/catalogName1> 
URL: <https://proxy.withampersand.com/api/catalogs/catalogName/items/5> 
URL: <https://proxy.withampersand.com/api/catalogs/catalogName/items/5> 
URL: <https://proxy.withampersand.com/api/catalogs/catalogName/items/5> 
**Wrong path**
Get request with `pageSize` and `page` parameters
Not applicable as the connector supports Api key authentication
=> Feat: Enable proxy for Iterable

providers/atlassian.go
Create issue.
Update issue.
https://github.com/amp-labs/testdata/pull/11
=> feat: Enable read+write: Atlassian

providers/anthropic.go
Closes #512 
Only one endpoint exists. Refer to auth-connector testing PR: https://github.com/amp-labs/connectors/pull/537
Send a message.
```
curl --location --request POST 'https://proxy.withampersand.com/v1/messages' \
--header 'x-amp-installation-id: fd6c5ef0-3501-4526-a5f3-94752f0e129b' \
--header 'anthropic-version: 2023-06-01' \
--data-raw '{
"model": "claude-3-opus-20240229",
"max_tokens": 1024,
"messages": [
{
"role": "user",
"content": "Hello, world"
}
]
}'
```
Wrong verb applied.
Invalid path.
Missing header.
=> feat: Enable proxy: Anthropic

providers/openAI.go
Closes #515 
List AI modules.
```
curl --location --request GET 'https://proxy.withampersand.com/v1/models' \
--header 'x-amp-installation-id: ae4e3daa-e195-4d2a-8e6f-a2ffced5da40' \
--header 'x-api-key: <API_KEY>'
```
```
curl --location --request POST 'https://proxy.withampersand.com/v1/images/generations' \
--header 'x-amp-installation-id: ae4e3daa-e195-4d2a-8e6f-a2ffced5da40' \
--data-raw '{
"prompt": "cats",
"quality": "standard",
"size": "256x256",
"model": "dall-e-2"
}'
```
```
curl --location …
```
=> feat: Enable proxy: OpenAI

providers/crunchbase.go
Wrong verb applied, invalid path.
Using the last `uuid` to fetch next page data.
=> feat: enable proxy crunchbase

providers/zendesk.go
Create issue.
Update issue.
Create brand.
Validated that brand was created using Proxy:
https://github.com/amp-labs/testdata/pull/12
=> feat: Enable read+write: Zendesk Support

providers/smartlead.go
Closes #889
None
URL: http://localhost:4444/v1/campaigns
URL: http://localhost:4444/v1/campaigns/create
URL: http://localhost:4444/v1/campaigns/549744
N/A
=> feat: Add Smartlead connector

providers/smartlead.go
Closes #889 
```
curl --location --request GET 'https://proxy.withampersand.com/v1/campaigns' \
--header 'x-amp-installation-id: 69b62489-5b76-4e78-9b2e-62064f0494e2'
```
```
curl --location --request POST 'https://proxy.withampersand.com/v1/campaigns/create' \
--header 'x-amp-installation-id: 69b62489-5b76-4e78-9b2e-62064f0494e2' \
--data-raw '{
"name": "Black Friday prep"
}'
```
```
curl --location --request DELETE 'https://proxy.withampersand.com/v1/campaigns/552628' \ …
```
=> feat: Enable proxy: Smartlead

salesloft/metadata/index.json, salesloft/metadata/schemas.json, salesloft/metadata_test.go, scripts/scrapper/salesloft/metadata/main.go
Display names are preprocessed before saving to the file.
```
Account Stages
Account Tiers
Accounts
Actions
Bulk Jobs
Cadence Memberships
Cadences
Calendar Events
Call Data Records
Call Dispositions
Call Instructions
Call Sentiments
Caller Ids
Calls
Crm Activities
Crm Activity Fields
Crm Users
Custom Fields
Custom Roles
Email Template Attachments
Email Templates
Emails
Groups
Imports
Job Data for a Bulk Job
Job Data for a Completed Bulk Job.
Meetings
Notes
Past Activities
Pending Emails
People
Person Stages
Phone Number Assignments
Play Registrations
Requests
Saved List Views
Signal Registrations
Steps
Successes
Tasks
Team Configurations
Team Mappings
Team Tags
Team Template Attachments
Team Templates
Users
Webhook Subscriptions
```
=> fix: DisplayNames for Salesloft schemas.json

salesloft/metadata/queryParamStats.json, salesloft/metadata/schemas.json, scripts/scrapper/intercom/metadata/main.go, scripts/scrapper/pipeliner/metadata/main.go, scripts/scrapper/salesloft/metadata/main.go, scripts/scrapper/zendesksupport/metadata/main.go, tools/scrapper/models.go
Same as https://github.com/amp-labs/connectors/pull/906.
=> feat: Add Docs URLs to static Metadata schemas

providers/smartlead.go
Create campaign.
Create client.
https://github.com/amp-labs/testdata/pull/13
=> feat: Enable read+write: Smartlead

providers/types.gen.go
This updates the dependency to version [838ca20784eec4379f3a42ac8320a2512ac24018](https://github.com/amp-labs/openapi/commit/838ca20784eec4379f3a42ac8320a2512ac24018) from [main](https://github.com/amp-labs/openapi/tree/main)
=> [auto] Update openapi dependency

examples/auth_connectors/adobe/adobe.go, providers/adobe.go
=> Rename the connector

providers/customer.go
Closes #514 
List segments.
```
curl --location --request GET 'https://proxy.withampersand.com/v1/segments' \
--header 'x-amp-installation-id: 0c3f30b1-2b27-47ff-a5f0-9d7e72e64146'
```
Create segment.
```
curl --location --request POST 'https://proxy.withampersand.com/v1/segments' \
--header 'x-amp-installation-id: 0c3f30b1-2b27-47ff-a5f0-9d7e72e64146' \
--data-raw '{
"segment": {
"name": "finished",
"description": "a segment that will be removed"
}
}'
```
Update broadcast …
=> feat: Enable proxy: Customer Journeys App

providers/snapchatAds.go
=> feat: enable snapchatAds connector

providers/customer.go
Closes #514 
Get account region.
```
curl --location --request GET 'https://proxy.withampersand.com/api/v1/accounts/region' \
--header 'x-amp-installation-id: a3bc6509-0b48-4578-ace1-5c7aad85cf32' \
--header 'x-api-key: <API_KEY>'
```
Add customer to the segment.
```
curl --location --request POST 'https://proxy.withampersand.com/api/v1/segments/212/add_customers' \
--header 'x-amp-installation-id: a3bc6509-0b48-4578-ace1-5c7aad85cf32' \
--data-raw '{
"ids": ["123"]
}'
```
Update customer.
```
curl …
```
=> feat: Enable proxy: Customer Journeys Track

providers/mixmax.go
URL: <https://proxy.withampersand.com/v1/insightsreports> 
URL: <https://proxy.withampersand.com/v1/insightsreports> 
URL: <https://proxy.withampersand.com/v1/insightsreports/66c46e9ad1c29a82e3c8c198> 
URL: <https://proxy.withampersand.com/v1/insightsreports/66c46e9ad1c29a82e3c8c198> 
**Wrong path**
**Without pagination** 
**With pagination using `limit` and `next` parameters**
Can't print the token as the connector supports API key type of authentication
=> Feat: Enable Mixmax proxy

providers/smartlead.go
=> Update smartlead.go icon update

providers/mural.go
Update the URL's for Mural connector
=> Mural: Update URL's

providers/intercom.go
=> Update intercom.go icon update

providers/instantly.go
Closes #892
None.
List campagins.
URL: http://localhost:4444/v1/campaign/list
Create tag.
URL: http://localhost:4444/v1/custom-tag
Update tag.
URL: http://localhost:4444/v1/custom-tag/f560a82c-1fba-4b4d-8661-8c0242742f50
Remove tag.
URL: http://localhost:4444/v1/custom-tag/f560a82c-1fba-4b4d-8661-8c0242742f50
Attempt to remove one more time.
List tags, 2 per page.
URL: http://localhost:4444/v1/custom-tag?limit=2
List tags, next 2.
URL: http://localhost:4444/v1/custom-tag?limit=2&skip=2
=> feat: Add Instantly connector

providers/zendesk.go
=> Update zendesk.go icon update

providers/copper.go
=> Update copper.go icon and logo update

providers/iterable.go
Uploading better dark mode logos manually per Ayan
=> Update iterable.go logo for app library

providers/discord.go
=> Update discord.go logo for app library

providers/chartMogul.go
=> Update chartMogul.go logo for app library

providers/attio.go
=> Update attio.go icon update

providers/serviceNow.go
=> Update serviceNow.go Logo update

providers/brevo.go
=> Update brevo.go logo update

providers/dynamics.go
=> Update dynamics.go icon change

providers/webflow.go
=> Update webflow.go icon change

providers/pipeliner.go
=> Update pipeliner.go icon update

providers/paddle.go
=> Update paddle.go icon update

providers/stripe.go
URL: <https://proxy.withampersand.com/v1/payment_intents> 
URL: <https://proxy.withampersand.com/v1/customers> 
URL: <https://proxy.withampersand.com/v1/customers/cus_QhW2YwOt5kGHDA> 
**Wrong path**
**Without pagination**
**With pagination using `limit` and `starting_after` parameters**
The connector supports API Key type auth, therefore raw token printout is not available
=> Feat: Enable stripe proxy

connectors.go, providers/aircall.go, providers/attio.go, providers/brevo.go, providers/chartMogul.go, providers/docusign.go, providers/dropbox.go, providers/dynamics.go, providers/front.go, providers/geckoboard.go, providers/iterable.go, providers/keap.go, providers/linkedIn.go, providers/notion.go, providers/paddle.go, providers/pipeliner.go, providers/podium.go, providers/rebilly.go, providers/slack.go, providers/wordPress.go, providers/zoho.go
=> Update logos for providers

providers/domo.go
const Domo Provider = "domo"
It supports pagination.
URL: https://proxy.withampersand.com/v1/datasets
URL: https://proxy.withampersand.com/v1/datasets
URL: https://proxy.withampersand.com/v1/datasets/0d98be68-6504-441c-9d8e-bcf73de37c9b
URL:https://proxy.withampersand.com/v1/datasets/0d98be68-6504-441c-9d8e-bcf73de37c9b
Requesting a paginated list of dataset using limit:
URL: https://proxy.withampersand.com/v1/datasets?limit=3
Requesting the next page using the offset and limit
URL: https://proxy.withampersand.com/v1/datasets?limit=5&offset=2
closes https://github.com/amp-labs/connectors/issues/376
=> feat: Enable proxy: Domo

providers/coda.go
const Coda Provider = "coda"
It supports pagination.
URL: https://proxy.withampersand.com/v1/docs
URL: https://proxy.withampersand.com/v1/docs
URL: https://proxy.withampersand.com/v1/docs/p4TkY3lNT1
URL: https://proxy.withampersand.com/v1/docs/p4TkY3lNT1
Requesting a paginated list of docs using limit:
URL: https://proxy.withampersand.com/v1/docs?limit=2
Requesting the next page using the pageToken and limit
URL: https://proxy.withampersand.com/v1/docs?limit=4&pageToken=eyJsaW1pdCI6Miwib2Zmc2V0IjoyfQ
=> feat: Enable proxy: Coda

common/http.go, marketo/connnector.go, marketo/metadata.go, marketo/url.go, test/marketo/metadata/metadata.go
=> feat: Add ListMetadata Marketo connector

providers/gladly.go
Closes #935 
Pagination is not supported
**Media:**
Icon is in png format and has a white background
Logo is jpeg format and has a white background
No dark mode options are available
URL: <localhost:4444/v1/agents> 
URL: <localhost:4444/v1/answers> 
URL: <localhost:4444/v1/answers/Pun0k4oxTA2CI_NeX4TixQ/languages/en-us/type/public> 
URL: <localhost:4444/v1/answers/VNEbRnbFR4Sb5YlWz5leuw> 
URL: <localhost:4444/v1/answers/VNEbRnbFR4Sb5YlWz5leuw> 
Pagination is not supported
=> Feat: Add Gladly connector

providers/salesflare.go
```
curl --location --request GET 'https://proxy.withampersand.com/accounts' \
--header 'x-amp-installation-id: b5143d47-9498-43c0-9904-31f66ecf4286'
```
```
curl --location --request POST 'https://proxy.withampersand.com/accounts' \
--header 'x-amp-installation-id: b5143d47-9498-43c0-9904-31f66ecf4286' \
--data-raw '{
"owner": 277017156,
"name": "ampersand account",
"domain":"withampersand.com",
"email":"support@withampersand.com"
}'
```
```
curl --location --request PUT …
```
=> feat: Enable proxy: Salesflare

providers/customer.go
Closes #514
N/A
Identify user.
```
curl --location --request POST 'https://proxy.withampersand.com/identify' \
--header 'x-amp-installation-id: 971a2f64-4cef-4695-8190-bb7224cfb79f' \
--data-raw '{
"userId": "123"
}'
```
Invalid path.
N/A
=> feat: Enable proxy: Customer Data Pipelines

providers/gorgias.go
URL: <https://proxy.withampersand.com/api/customers> 
URL: <https://proxy.withampersand.com/api/customers> 
URL: <https://proxy.withampersand.com/api/customers/509491878> 
URL: <https://proxy.withampersand.com/api/customers/509491878> 
**Wrong path**
**After pagination using `limit` and `cursor` parameters**
Note: token API call requires Basic auth
=> Feat: enable Gorgias proxy

scripts/proxy/proxy.go
This may have been incorrectly changed.
=> feat: update script

providers/zuora.go
URL: <localhost:4444/v1/catalog/products> 
URL: <https://proxy.withampersand.com/v1/object/product> 
URL: <https://proxy.withampersand.com/v1/object/product/8a8aa3ee917505cd01917908839d6369> 
URL: <https://proxy.withampersand.com/v1/object/product/8a8aa3ee917505cd01917908839d6369> 
**Wrong path**
**After pagination with page and pageSize parameters**
=> Feat: Enable Zuora proxy

providers/marketo.go
This enables read and write for marketo
=> feat: Enable read and write for marketo

providers/github.go
URL: <https://proxy.withampersand.com/user/repos> 
URL: <https://proxy.withampersand.com/user/repos> 
URL: <https://proxy.withampersand.com/repos/ampersandintegrationuser/new-repo> 
**Wrong path**
**Without pagination**
**With pagination using `page` and `per_page` parameters**
=> Feat: Add Github proxy

providers/salesforceMarketing.go
Closes #883 #683 
Notes:
Requires sub domainvariable,  mapped to workspace.
Retrieving a paginated list of categories
As observed above the `pagesize=50` and `count=62` and we are currently in `page`=1,  to retrieve the next page records we add a query parameter `page=2`
=> feat: Add Salesforce Marketing Cloud

providers/instantly.go
Closes #892
```
curl --location --request GET 'https://proxy.withampersand.com/v1/campaign/list' \
--header 'x-amp-installation-id: cebcc727-9724-4032-bb79-273856c0c567'
```
```
curl --location --request POST 'https://proxy.withampersand.com/v1/custom-tag' \
--header 'x-amp-installation-id: cebcc727-9724-4032-bb79-273856c0c567' \
--data-raw '{
"label": "Tag label",
"description": "Some description goes here"
}'
```
```
curl --location --request PATCH …
```
=> feat: Enable proxy: Instantly

providers/braintree.go
```
curl --location --request POST 'https://proxy.withampersand.com' \
--header 'x-amp-installation-id: f4b9b6ca-e8c2-46e0-9252-e8e14d5d6f7f' \
--header 'Braintree-Version: 2019-01-01' \
--data-raw '{
"query": "query { ping }"
}'
```
Wrong verb applied.
Invalid GraphQL.
GET without query.
N/A
As you can see all requests despite the result return 200 OK.
=> feat: Enable Proxy: Braintree

providers/mural.go
URL: <https://proxy.withampersand.com/public/v1/workspaces/ampersand9122/rooms> 
URL: <https://proxy.withampersand.com/public/v1/rooms> 
URL: <https://proxy.withampersand.com/public/v1/rooms/1724479956625394> 
URL: <https://proxy.withampersand.com/public/v1/rooms/1724479956625394> 
**Wrong path**
**After pagination with `limit` and `next` parameters**
=> Feat: Enable Mural proxy

providers/amplitude.go
Closes #541 
Wrong verb applied,
invalid path.
Pagination is not supported.
=> feat: enable Amplitude connector

test/atlassian/metadata/main.go, test/dynamicscrm/connector.go, test/dynamicscrm/metadata/main.go, test/dynamicscrm/read/main.go, test/dynamicscrm/write-delete/main.go, test/marketo/write/write.go, test/pipeliner/metadata/main.go, test/pipeliner/read/main.go, test/pipeliner/write-delete/main.go, test/salesforce/metadata-read/main.go, test/smartlead/metadata/main.go, test/smartlead/read/main.go, test/smartlead/write-delete/main.go, test/zendesksupport/metadata/main.go, test/zendesksupport/read/main.go, test/zendesksupport/write-delete/main.go
=> chore: Fix formatting

common/parse.go, providers/gong/parse.go, providers/gong/read.go, providers/zendesksupport/parse.go, providers/zendesksupport/read.go
Refactoring GetRecords for providers with JSON response
=> tidy: Create common.GetRecords

providers/apollo/metadata.go, providers/apollo/url.go, test/apollo/metadata/metadata.go
Uses reading of the object to generate the metadata.
=> feat: Add Apollo ListMetadata connector

providers/instantly/delete.go, providers/instantly/delete_test.go, providers/instantly/objectNames.go, providers/instantly/read.go, providers/instantly/test/delete-tag-missing.json, providers/instantly/test/delete-tag.json, providers/instantly/test/write-blocklist-entry.json, providers/instantly/test/write-lead-bad-request.json, providers/instantly/test/write-lead.json, providers/instantly/test/write-tag-bad-request.json, providers/instantly/test/write-tag.json, providers/instantly/test/write-unibox-reply.json, providers/instantly/write.go, providers/instantly/write_test.go, test/instantly/write-delete/main.go
Closes #912
Write endpoints are hard coded to the list of object names associated with them.
There is a second commit with minor tidy things. They are not significant to be in the independent PR but they are not related to current.
=> feat: Deep connector Instantly (Write)

providers/instantly.go
Create tag.
Update tag.
https://github.com/amp-labs/testdata/pull/14
=> feat: Enable read+write: Instantly

providers/apollo.go
The dashboard:
Webhook Responses:
Sample file: https://github.com/amp-labs/testdata/pull/15
=> feat: enable Read, Write Apollo

common/header.go
This adds a new way to attach headers, via a dynamic callback
=> feat: Add dynamic headers

common/oauth.go
Some providers (cough, Salesforce) will invalidate OAuth access tokens under certain circumstances (e.g., the refresh token being used by another IP address). If this happens, it will return a 401. Right now, we treat that 401 as fatal, when really it needs to be seen as a chance to forcefully refresh the OAuth token.
This PR provides a new hook which the server code can use to intercept the 401, and call out to the token manager service with `force=true` to obtain a new token.
=> feat: Add an option for handling 401 errors

common/header.go, common/query.go
This adds a 401 hook for the other types of clients. This is necessary because even though we use the OAuth client in some places (which already has this hook), in other places we use the Header client (TO DO OAUTH, when used in conjunction with the token manager service), and we need to handle that client receiving a 401 too. This is a consistency+correctness thing, in other words.
=> feat: Add unauthorized hook for other client types

test/utils/mockutils/mockcond/body.go
There is a stack of PRs that improve mock utilities.
This implementation adds better comparison of expected request body and what deep connector sends. It does either text comparison (which is not ideal for all json cases) or deep equals on parsed JSON.
=> feat(mockutils): Response body comparison

providers/kit.go
[x] Created PR from non-main branch 
URL: http://localhost:4444/v4/custom_fields
URL: http://localhost:4444/v4/custom_fields
URL: http://localhost:4444/v4/custom_fields/723620
URL: http://localhost:4444/v4/custom_fields/723602
Requesting a paginated list of custom fields using per_page param
URL: http://localhost:4444/v4/custom_fields?per_page=3
Request the next paginated list of custom fields using the token from the end_cursor field in the response, and pass the token in the after parameter.
URL: http://localhost:4444/v4/custom_fields?after=WzcyMzU5OV0=
Request the previous paginated list of custom fields using the token from the start_cursor field in the response, and pass the token in the before parameter.
URL: …
=> feat: Add Kit connector

providers/kit.go
=> feat: Add media to Kit

providers/dovetail.go
Dovetail Provider = "dovetail"
URL: https://proxy.withampersand.com/v1/notes
get by note ID
URL: https://proxy.withampersand.com/v1/notes/2EbWcGFjGXMqBTlrCSj5k1
URL: https://proxy.withampersand.com/v1/note
URL: https://proxy.withampersand.com/v1/notes/2EbWcGFjGXMqBTlrCSj5k1
URL: https://proxy.withampersand.com/v1/notes/2EbWcGFjGXMqBTlrCSj5k1
Requesting a paginated list of notes using **page[limit]** parameter
URL: https://proxy.withampersand.com/v1/notes?page[limit]=2
Request the next paginated list of notes by using the token from the **next_cursor** field in the response and passing it in the **page[start_cursor]** parameter …
=> feat: Enable proxy: Dovetail

providers/zoho.go, providers/zohocrm/client.go, providers/zohocrm/connector.go, providers/zohocrm/metadata.go, providers/zohocrm/params.go, test/zohocrm/connector.go, test/zohocrm/metadata/metadata.go
This adds the zohocrm ListMetadata connector.
Uses specific object endpoint for retrieving metadata fields.
Test Output:
=> feat: Add ZohoCRM ListMetadata connnector

providers/close.go, providers/closecrm/client.go, providers/closecrm/connector.go, providers/closecrm/metadata.go, providers/closecrm/params.go, test/close/connector.go, test/close/metadata/metadata.go
Adds CloseCRM Metadata connector
Test Outputs:
=> feat: Add CloseCRM Metadata connector

providers/closecrm/parse.go, providers/closecrm/write.go, test/closecrm/write/write.go
This Adds the Write connector.
Test Outputs:
=> feat: Add CloseCRM write connector

providers/zendesk.go, providers/zendesksupport/connector.go, test/closecrm/write/write.go, test/zohocrm/read/read.go
Reverts amp-labs/connectors#1119
=> Revert "fix: Revert Zendesk BaseURL"

providers/timely.go
404
Request pages, until you get an empt response.
=> feat: Enable Timely proxy connector

common/interpreter/error.go, common/interpreter/error_test.go, test/utils/mockutils/mockserver/handlers.go
Error handling may be done for customly defined Media Types.
=> feat: Handle custom mime error response

providers/productBoard.go
ProductBoard Provider = "productBoard"
URL:  https://proxy.withampersand.com/users
URL:  https://proxy.withampersand.com/users
URL:  https://proxy.withampersand.com/users/3c02846a-b36d-4373-bfa0-43a0950f8df9
URL:  https://proxy.withampersand.com/users/3c02846a-b36d-4373-bfa0-43a0950f8df9
Requesting a paginated list of users using pageLimit param
URL:  https://proxy.withampersand.com/users?pageLimit=2
Requesting the next page using the pageOffset param
URL:  https://proxy.withampersand.com/users?pageLimit=2&pageOffset=2
Invalid endpoint
Invalid method
=> feat: Enable proxy: Productboard

providers/klaviyo/connector.go, providers/klaviyo/delete.go, providers/klaviyo/delete_test.go, providers/klaviyo/errors.go, providers/klaviyo/objectNames.go, providers/klaviyo/read.go, providers/klaviyo/test/README.md, providers/klaviyo/test/delete-tag-not-found.json, providers/klaviyo/test/invalid-auth.json, providers/klaviyo/test/write-tag-bad-request.json, providers/klaviyo/test/write-tag-conflict.json, providers/klaviyo/test/write-tag.json, providers/klaviyo/write.go, providers/klaviyo/write_test.go, test/klaviyo/write-delete/main.go
Manually went over API documentation and recorded objects that relatively fit into "write object" category.
There are maybe at most ~5 POST methods omited that are "actions".
=> feat: Klaviyo (Write)

providers/klaviyo.go
This PR enables the klaviyo proxy
=> feat: Enable klaviyo proxy

providers/hubspot/record.go, test/hubspot/record/main.go
```
jaehyunlim@Jaehyuns-MBP connectors % go run test/hubspot/record/main.go                
time=2024-11-24T17:08:40.711-08:00 level=DEBUG msg="loading credentials file" path=./hubspot-creds.json
{
"fields": null,
"raw": {
"archived": false,
"createdAt": "2024-11-25T01:08:41.212Z",
"id": "79982634859",
"properties": {
"createdate": "2024-11-25T01:08:41.212Z",
"email": "shanelgislason@wehner.org",
"firstname": "Rene",
"hs_object_id": "79982634859",
"lastmodifieddate": "2024-11-25T01:08:41.212Z",
"lastname": "Romaguera"
},
"updatedAt": "2024-11-25T01:08:41.212Z"
}
}
[
{
"fields": null,
"raw": {
"archived": false,
"createdAt": "2024-11-25T01:08:41.212Z",
"id": "79982634859",
"properties": {
"createdate": "2024-11-25T01:08:41.212Z",
"email": "shanelgislason@wehner.org",
"firstname": "Rene", …
```
=> [ENG-1652] Get Records with ids

providers/goToWebinar.go
None
Pagination uses the query paramters `page` and `size`
Going the next page.
=> feat: Add GoToWebinar connector

providers/constantcontact/read_test.go
This just fixes a linter error which was checked in to main
=> fix: Linter errors

common/types.go, providers/hubspot/record.go, providers/hubspot/webhook.go
This pr creates connector method to extract id from a raw hubspot record. This will be used for subscribe action.
=> [ENG-1652] Implement method to extract id from raw record

providers/constantcontact/metadata.go, providers/constantcontact/metadata_test.go, providers/constantcontact/objectNames.go, providers/constantcontact/openapi/file.go, providers/constantcontact/openapi/swagger.yaml, providers/constantcontact/read.go, scripts/openapi/constantcontact/metadata/main.go, test/constantcontact/metadata/main.go
Metadata is coming from OpenAPI file.
It is downloaded from official docs: https://developer.constantcontact.com/api_guide/v3api_schema.html
=> feat: ConstantContact (Metadata)

providers/hubspot/parse.go, providers/hubspot/webhook.go
Previous PR adding Id to records missed the called function that parses result Row.
=> Feat - extract Id for getMarshalledData for hubspot

providers/lemlist.go
Weird behaviour, any invalid request responds with 200 OK. 
Retrieving the first 2 campaigns:
Going to page 2.
=> feat: Add Lemlist connector

internal/staticschema/core.go, providers/keap/connector.go, providers/keap/delete.go, providers/keap/delete_test.go, providers/keap/objectNames.go, providers/keap/read.go, providers/keap/test/delete-missing-contact.json, providers/keap/test/write-contacts-missing-fields.json, providers/keap/test/write-contacts.json, providers/keap/write.go, providers/keap/write_test.go, test/keap/read/main.go, test/keap/write-delete/main.go, test/utils/searcher/search.go
=> feat: Keap (Write)

providers/constantContact.go
Create contact
Update contact
https://github.com/amp-labs/testdata/pull/23
=> [CON-106] Enable read+write: ConstantContact

providers/monday.go
Get boards.
```
curl --location --request POST 'https://proxy.withampersand.com/v2' \
--header 'x-amp-installation-id: d6507260-cdb9-40b8-b33e-afdc0df24267' \
--data-raw '{
"query":"query { boards {id name type communication board_kind creator {name}}}"
}'
```
Create item on a board.
```
curl --location --request POST 'https://proxy.withampersand.com/v2' \
--header 'x-amp-installation-id: d6507260-cdb9-40b8-b33e-afdc0df24267' \ …
```
=> [CON-280] Enable proxy: Monday

providers/customerapp/read.go, test/customerio/journeysapp/read/main.go
Customer Journeys App is to use NextPage. Enables pagination.
=> fix: CustomerApp use pagination

providers/lemlist.go
As observed while testing the API, Invalid request responds with 200 OK
Pagination is only supported in the campaigns resource.
=> [CON-603] feat: enable Lemlist proxy

providers/lever.go
It supports Pagination.
Lever        Provider = "lever"
LeverSandbox Provider = "leverSandbox"
URL: http://localhost:4444/v1/requisitions
URL: http://localhost:4444/v1/requisitions/1857b09e-410c-4502-949f-35047310bb52
URL: http://localhost:4444/v1/requisitions
URL: http://localhost:4444/v1/requisitions/1857b09e-410c-4502-949f-35047310bb52
URL: http://localhost:4444/v1/requisitions/1857b09e-410c-4502-949f-35047310bb52
Requesting a paginated list of requisitions using limit:
URL: http://localhost:4444/v1/requisitions?limit=1
Requesting the next page using the offset
URL: http://localhost:4444/v1/requisitions?offset=%5B%22a585d99a-941a-4642-8f45-86d3fa0db8e5%22%5D
=> [CON-239] feat: Add lever connector

providers/goToWebinar.go
Requesting the first page( uses zero based index)
Next Page:
And then last page:
=> [CON-174] feat: enable goToWebinar proxy

providers/customer.go
Create segment.
https://github.com/amp-labs/testdata/pull/22
=> [CON-123] Enable read+write: CustomerJourneysApp

providers/hubspot/record.go
=> fix: Plurality insensitive search with Ids for webhooks

providers/sellsy.go
- No fishy behaviour was observed. All the requests/responses were parsed correctly.
- It supports pagination and batching
URL: https://proxy.withampersand.com/v2/contacts
URL: https://proxy.withampersand.com/v2/contacts
URL: https://proxy.withampersand.com/v2/contacts/37
URL: https://proxy.withampersand.com/v2/contacts/37
URL: https://proxy.withampersand.com/v2/contacts/37
Requesting a paginated list of contacts using the limit parameter to set the record limit.
URL: https://proxy.withampersand.com/v2/contacts?limit=30
Request the next paginated list of contacts by using the token from the offset field in the previous URL response and passing it in the offset parameter.
URL: https://proxy.withampersand.com/v2/contacts?limit=30&offset=WyIzMiJd
**Note:** For Batching, we need to use the …
=> [CON-547] feat: Enable Proxy: Sellsy

providers/talkdesk.go
URL: localhost:4444/prompts
URL: localhost:4444/prompts-requests
URL: localhost:4444/prompts/7191380e8e1d455d9a073fcac69f66fa
URL: localhost:4444/prompts/7191380e8e1d455d9a073fcac69f66fa
URL:  localhost:4444/prompts/7191380e8e1d455d9a073fcac69f66fa
Pagination uses URLs to navigate between the next and previous pages.
Next page:
=> [CON-727] feat: Add Talkdesk connector

providers/close.go, providers/kit/connector.go
Read, Write Sample files: https://github.com/amp-labs/testdata/pull/20
Installation:
=> [CON-81] feat: enable read+write closeCRM

providers/pipedrive.go
Installation:
Sample files: https://github.com/amp-labs/testdata/pull/19
=> [CON-313] feat: enable read+write:Pipedrive

providers/delighted.go
URL: localhost:4444/v1/people.json
URL: localhost:4444/v1/people.json
URL:  localhost:4444/v1/people/1659447232
- PATCH and PUT Method endpoints not available.
Pagination is cursor based. Within each response, a Link header will provide access to the next page of results. If missing, there are no more results to be returned.
Next page Link is in the header : 
Next page:
=> [CON-759] feat: Add Delighted proxy

providers/drip.go
- No fishy behaviour was observed. All the requests/responses were parsed correctly.
- It supports pagination and batching
URL: https://proxy.withampersand.com/v2/5425884/subscribers
URL: https://proxy.withampersand.com/v2/5425884/subscribers/sci35hnbzflgm13pq7ha
URL: https://proxy.withampersand.com/v2/5425884/subscribers
URL: https://proxy.withampersand.com/v2/5425884/subscribers/sci35hnbzflgm13pq7ha
Requesting a paginated list of subscribers using the per_page param
URL: https://proxy.withampersand.com/v2/5425884/subscribers?per_page=1
Requesting a paginated list of subscribers go to the next page by using the page param
URL: https://proxy.withampersand.com/v2/5425884/subscribers?per_page=1&page=2
URL: https://proxy.withampersand.com/v2/5425884/subscribers/batches
Invalid endpoint …
=> [CON-132] feat: Enable proxy: Drip

providers/zohoDesk.go
URL: localhost:4444/api/v1/organizations
URL: localhost:4444/api/v1/contacts
URL: localhost:4444/api/v1/contacts/1060099000000334001
URL:  localhost:4444/api/v1/organizations/872965074/logo
Pagination  is done by using **from** (starting point) and **limit** (number of records). By default, it starts from record 1 and fetches 10 at a time, with a maximum of 50 per request.
Attempting to delete a profile picture when there is none.
Invalid ticket id used
Invalid OrgId provided in the header
Invalid payload provided
=> [CON-743] feat: Add ZohoDesk Connector

providers/ashby.go
API [docs](https://developers.ashbyhq.com/reference/apikeyinfo)
- All endpoints accept POST requests, even those that typically handle GET requests.
URL: localhost:4444/department.list
URL: localhost:4444/department.create
URL: localhost:4444/opening.update
URL: localhost:4444/department.info
Pagination uses the “moreDataAvailable” flag and the “nextCursor” in the response to indicate whether the next page is available.
Next page:
Input invalid data
Input wrong cursor data
provide incorrect departmentId
Enter incorrect url path
=> [CON-751] feat: Add Ashby connector

.github/workflows/build.yml, .github/workflows/linter.yml, common/types.go, providers/hubspot/metadata.go, providers/hubspot/read.go, providers/hubspot/record.go, providers/hubspot/search.go, providers/hubspot/subscriptionEvent.go, providers/hubspot/url.go, providers/hubspot/write.go, test/hubspot/record/main.go
This adds associations to Hubspot's read action, as well as the GetRecordsWithIds method
=> feat: Add associations options to HubSpot connector

providers/hubspot/record.go
=> [ENG-1754] Fix Hubspot GetRecordsWithIds to get properties correctly

internal/datautils/maps.go, providers/discourse.go
URL: localhost:4444/posts.json
URL: localhost:4444/posts.json
URL: localhost:4444/posts/10.json
URL: localhost:4444/posts/10.json
Pagination is implemented by passing the page number as a query parameter. Each page returns 30 items.
Next page:
Input duplicate data
provide invalid data
provide an incorrect dynamic ID in the URL.
=> [CON-793] feat: Add Discourse connector

providers/ashby.go
- All endpoints accept POST requests, even those that typically handle GET requests.
Pagination uses the “moreDataAvailable” flag and the “nextCursor” in the response to indicate whether the next page is available.
Next page :
provide invalid cursor value in the payload
Input invalid payload
provide incorrect api url path
Incorrect http method
=> [CON-753] feat: Enable Ashby proxy

providers/zoho.go, test/zohocrm/write/write.go
Installation:
Ampersand Dashboard:
Test-Data Sample: https://github.com/amp-labs/testdata/pull/25
=> [CON-426] feat: Enable ZohoCRM Read & Write

providers/kit.go
After creating a webhook object in Kit, a purchase object creation event was triggered, and I received a webhook delivery response
=> [CON-215] feat: Enable read+write: Kit

providers/emailBison.go
It supports Pagination and Batching.
EmailBison Provider = "emailBison"
URL: http://localhost:4444/api/leads
URL: http://localhost:4444/api/leads/776220
URL: http://localhost:4444/api/leads
URL: http://localhost:4444/api/leads/776220
Requesting a paginated list of leads using the **page** parameter. Each page displays **15 records by default**.
URL: http://localhost:4444/api/leads?page=2
=> [CON-821] feat: Add EmailBison connector

providers/outplay.go
URL: localhost:4444/api/v1/me
URL: localhost:4444/api/v1/prospect
URL: localhost:4444/api/v1/prospect/18229218
URL: localhost:4444/api/v1/prospect/18229218
Pagination is implemented by passing the page number as a PageIndex query parameter. Each page returns 50 items. For some APIs, we are required to pass an offset value as a query parameter to fetch the next page.
Next page:
Input duplicate data
provide invalid data
provide an incorrect dynamic ID in the URL.
=> [CON-925] feat: Add Outplay connector

providers/heyreach.go
None
No Other Methods apart from `GET` and `POST`
=> [CON-933] feat: Add HeyReach Connector

providers/heyreach.go
=> [CON-935] feat: enable HeyReach connector

common/parse.go, providers/iterable/client.go, providers/iterable/connector.go, providers/iterable/errors.go, providers/iterable/metadata/metadata.go, providers/iterable/metadata/schemas.json, providers/iterable/objectNames.go, providers/iterable/params.go, providers/iterable/parse.go, providers/iterable/read.go, providers/iterable/read_test.go, providers/iterable/test/error-wrong-method.html, providers/iterable/test/read-catalogs-1-first-page.json, providers/iterable/test/read-catalogs-2-second-page.json, providers/iterable/test/read-templates-invalid-since.html, providers/iterable/test/read-templates-since.json, test/iterable/connector.go, test/iterable/read/main.go
=> [CON-807] Iterable: Read

providers/iterable/metadata.go, providers/iterable/metadata_test.go, providers/iterable/openapi/README.md, providers/iterable/openapi/api-docs.json, providers/iterable/openapi/file.go, scripts/openapi/iterable/metadata/main.go, test/iterable/metadata/main.go
=> [CON-806] Iterable: Metadata

providers/iterable.go
https://github.com/amp-labs/testdata/pull/28
=> [CON-811] Enable Iterable Read/Write

providers/closecrm/parse.go
=> fix: make next-page key optional in Close Connector

providers/groove.go
It supports Pagination
Groove Provider = "groove"
URL: http://localhost:4444/v1/kb/6905201123/articles/search
URL: http://localhost:4444/v1/kb/6905201123/articles/1851925880
URL: http://localhost:4444/v1/kb/6905201123/articles
URL: http://localhost:4444/v1/kb/6905201123/articles/1851925880
URL: http://localhost:4444/v1/kb/6905201123/articles/1851925880
Requesting a paginated list of users using **per_page** parameter:
URL: http://localhost:4444/v1/kb/6905201123/articles/search?per_page=1
Requesting the next page using the **per_page** and **page** parameter:
URL: http://localhost:4444/v1/kb/6905201123/articles/search?per_page=1&page=3
=> [CON-609] feat: Add Groove connector

providers/groove.go
URL: https://proxy.withampersand.com/v1/kb/6905201123/articles/search
URL: https://proxy.withampersand.com/v1/kb/6905201123/articles/5113289980
URL: https://proxy.withampersand.com/v1/kb/6905201123/articles
URL: https://proxy.withampersand.com/v1/kb/6905201123/articles/3028851921
URL: https://proxy.withampersand.com/v1/kb/6905201123/articles/3028851921
Requesting a paginated list of articles using the **page** parameter and limited the count with **per_page** parameter ( default per page count - 25)
URL: https://proxy.withampersand.com/v1/kb/6905201123/articles/search?page=1&per_page=5
Requesting the next page using the **page** parameter and limiting the count with the **per_page** parameter:
URL: https://proxy.withampersand.com/v1/kb/6905201123/articles/search?page=2&per_page=5
=> [CON-611] feat: Enable proxy: Groove

providers/hubspot/metadata.go
=> [CON-986] feat(Hubspot): Aggregate Pipeline stages for enum

providers/highlevel.go
HighLevelStandard   Provider = "highLevelStandard"
HighLevelWhiteLabel Provider = "highLevelWhiteLabel"
1. In HighLevel, there are two authentication flows: Standard and White-Label. While they use different Auth URLs, they share the same Token URL. Regardless of whether you use Standard or White-Label, you can access all APIs in HighLevel because the scopes of each token are determined by the account level (Agency or Sub-Account) you select during authorization. Some scopes are restricted to sub-accounts, others to agency-level accounts, while certain scopes are available for both.
2. It supports pagination and batching
URL: http://localhost:4444/contacts/?locationId=iV1BEzddaWWLqU2kXhcN
URL: http://localhost:4444/contacts/
URL: http://localhost:4444/contacts/h5kmy9BM9Bxyby7BVop4
URL: …
=> [CON-977] feat: Add HighLevel connector

common/types.go
- Defining types for subscription and registration for the action.
=> [ENG-1892] Define subscribe action connector types and interface

providers/serviceDeskPlus.go
const ServiceDeskPlusUS Provider = "serviceDeskPlusUS"
1. Service Desk Plus comes in two primary deployment options: On-Premises and Cloud.
2. It is hosted at multiple data centers, and therefore available on different domains.
- United States - https://sdpondemand.manageengine.com/ (API Endpoint Base URL)
- Europe - https://sdpondemand.manageengine.eu/
- India - https://sdpondemand.manageengine.in/
- China - https://servicedeskplus.cn/
- Australia - https://servicedeskplus.net.au/
- Japan - https://servicedeskplus.jp/
- Canada - https://servicedeskplus.ca/
- United Kingdom - https://servicedeskplus.uk/
- Saudi Arabia - https://servicedeskplus.sa/
3. Pagination is supported. Bulk process is also supported
REF - 
URL: http://localhost:4444/app/itdesk/api/v3/requests
URL: …
=> [CON-1017] feat: Add ServiceDesk Plus connector

providers/stripe/openapi/README.md, providers/stripe/openapi/file.go, scripts/openapi/stripe/metadata/main.go
In order to shrink other PRs adding open api file and the script to parse it is added as part of this PR.
=> [CON-883] feat(Stripe): Add OpenAPI file

providers/stripe/metadata.go, providers/stripe/metadata_test.go, test/stripe/metadata/customers/main.go
=> [CON-883] feat(Stripe): ListObjectMetadata

providers/chilipiper.go
=> [CON-1001] feat: Enable Chilipiper connector

providers/stripe/connector.go, providers/stripe/delete.go, providers/stripe/delete_test.go, providers/stripe/objectNames.go, providers/stripe/test/delete/err-not-found.json, providers/stripe/test/general-errors/error-setup-payment-intent.json, providers/stripe/test/write/customers/new.json, providers/stripe/write.go, providers/stripe/write_test.go, scripts/openapi/keap/endpoints/main.go, scripts/openapi/stripe/endpoints/main.go, scripts/openapi/utils/writeEndpoints.go, test/stripe/write-delete/main.go, test/utils/mockutils/mockcond/header.go
Creates, updates and finally removes customer record.
=> [CON-885] feat(Stripe): Write

providers/chilipiper/client.go, providers/chilipiper/connector.go, providers/chilipiper/metadata.go, providers/chilipiper/metadata_test.go, providers/chilipiper/params.go, providers/chilipiper/test/unsupported.txt, providers/chilipiper/test/workspace.json, providers/chilipiper/url.go, test/chilipiper/connector.go, test/chilipiper/metadata/metadata.go
=> [CON-988] feat: Add ChiliPiper Metadata Connector

providers/chilipiper/metadata.go, providers/chilipiper/metadata_test.go, providers/chilipiper/parse.go, providers/chilipiper/read.go, providers/chilipiper/read_test.go, providers/chilipiper/test/empty.json, providers/chilipiper/test/team.json, providers/chilipiper/types.go, providers/chilipiper/url.go, test/chilipiper/read/read.go
Tests:
This Adds Read Connector:
- To support more objects, I have created a map of objects to their paths.
=> [CON-989] feat: Add ChiliPiper Read Connector

providers/asana.go
=> [CON-953] feat: enable read + write (asana)

providers/google/metadata/schemas.go, providers/google/metadata/schemas.json, providers/google/modules.go, providers/google/openapi/README.md, providers/google/openapi/calendar.json, providers/google/openapi/file.go, scripts/openapi/google/metadata/calendar/objects.go, scripts/openapi/google/metadata/main.go, tools/fileconv/api3/models.go
OpenAPI file for calendar is acquired by running a forked script https://github.com/Cobalt0s/google-discovery-to-openapi.
See README in this PR.
=> feat(google): Add calendar openapi

.github/PULL_REQUEST_TEMPLATE/deep_connector.md, providers/stripe.go
API key.
Duplicate creation with the same id produces a very nice error that write connector returns.
Link pull request to testdata repo which contains installation file: https://github.com/amp-labs/testdata/pull/32
=> [CON-888] feat(Stripe): Enable read, write

providers/chilipiper/metadata.go, providers/chilipiper/metadata/metadata.go, providers/chilipiper/metadata/schemas.json, providers/iterable/write.go, scripts/openapi/chilipiper/docs.yaml, scripts/openapi/chilipiper/openapi/main.go, test/chilipiper/metadata/metadata.go
Created a custom script as the OpenAPI tool uses a package (https://github.com/getkin/kin-openapi) that currently does not support version 3.1.0
Tests:
=> feat: Add fallback to OpenAPI ChiliPiper Metadata Connector

providers/solarWindsServiceDesk.go
URL: https://proxy.withampersand.com/categories.json
URL: https://proxy.withampersand.com/categories/4259049.json
URL: https://proxy.withampersand.com/categories.json
URL: https://proxy.withampersand.com/categories/4259049.json
URL: https://proxy.withampersand.com/categories/4259049.json
1. Requesting the paginated list of hardwares using per_page and page parameter. 
URL: https://proxy.withampersand.com/hardwares.json?per_page=1&page=1
2. Requesting the next paginated list of hardwares using per_page and page parameter. 
URL: https://proxy.withampersand.com/hardwares.json?per_page=1&page=2
2.a) Incase of using only the page 2 param
URL: https://proxy.withampersand.com/hardwares.json?page=2
API key Authorization
=> [CON-1029] feat: Enable proxy: Solarwinds Service Desk

common/types.go, providers/salesforce/events.go, providers/salesforce/register.go, scripts/oauth/token.go, test/salesforce/subscribe/register.go, test/zoom/read/main.go, test/zoom/write/main.go
I messed up while rebasing https://github.com/amp-labs/connectors/pull/1346
This is just clean branch for the PR that was already approved
```
jaehyunlim@Jaehyuns-MacBook-Pro connectors % go run test/salesforce/subscribe/register.go            
time=2025-02-19T14:01:33.940-08:00 level=DEBUG msg="loading credentials file" path=./salesforce-creds.json
time=2025-02-19T14:01:33.942-08:00 level=DEBUG msg="HTTP request" method=POST url=https://ampersand-c-dev-ed.develop.my.salesforce.com/services/data/v59.0/tooling/sobjects/PlatformEventChannel headers="[{Key:Accept Value:application/json}]" bodySize=97
time=2025-02-19T14:01:34.454-08:00 level=DEBUG msg="HTTP request" method=POST url=https://ampersand-c-dev-ed.develop.my.salesforce.com/services/data/v59.0/tooling/sobjects/NamedCredential …
```
=> [ENG-1888] Salesforce DeleteRegistration method <<redo after merge conflict>>

providers/joinMe.go
It supports batching process.
URL: http://localhost:4444/v1/meetings
URL: http://localhost:4444/v1/meetings/18755422
URL: http://localhost:4444/v1/meetings
URL: http://localhost:4444/v1/meetings/18755422
URL: http://localhost:4444/v1/meetings/18755422
=> [CON-1221] feat: Add Join Me connector

providers/whereby.go
const Whereby Provider = "whereby"
URL: http://localhost:4444/v1/meetings
URL: http://localhost:4444/v1/meetings/96948156
URL: http://localhost:4444/v1/meetings
URL; http://localhost:4444/v1/meetings/96948156
Requesting the paginated list of meetings using limit 
URL: http://localhost:4444/v1/meetings?limit=5
Request the next set of paginated meetings using the cursor parameter from the previous response, along with the limit parameter
URL: http://localhost:4444/v1/meetings?cursor=eyJ0eXBlIjoib2Zmc2V0IiwidmFsdWUiOiI1In0=&limit=5
Requesting remaining set of meetings by using cursor param
URL: http://localhost:4444/v1/meetings?cursor=eyJ0eXBlIjoib2Zmc2V0IiwidmFsdWUiOiIxMCJ9
=> [CON-1231] feat: Add Whereby connector

common/parse.go, providers/freshdesk/metadata.go, providers/freshdesk/parse.go, providers/freshdesk/read.go, providers/freshdesk/read_test.go, providers/freshdesk/test/mailboxes.json, providers/freshdesk/url.go, test/freshdesk/read/main.go
=> [CON-1062] feat: Add Freshdesk Read Connector

providers/joinMe.go
It supports batching
JoinMe Provider = "joinMe"
URL: https://proxy.withampersand.com/v1/meetings
URL: https://proxy.withampersand.com/v1/meetings/18755464
URL: https://proxy.withampersand.com/v1/meetings
URL: https://proxy.withampersand.com/v1/meetings/18755464
URL: https://proxy.withampersand.com/v1/meetings/18755464
=> [CON-1223] feat: Enable proxy: Join Me

providers/zoom/metadata/schemas.json, providers/zoom/objectNames.go, scripts/openapi/zoom/metadata/meeting/object.go
=> feat (zoom): add devices and H.322 devices object

providers/zoom.go
=> [CON-1167] feat(zoom): enable Read and Write

providers/chilipiper/test/add_user_team.json, providers/chilipiper/types.go, providers/chilipiper/url.go, providers/chilipiper/write.go, providers/chilipiper/write_test.go, test/chilipiper/write/write.go
Tests:
- Similar to Read Connector, I have added a map of objects to their paths, to support more objects.
=> [CON-990] feat: Add ChiliPiper Write Connector

common/json.go, common/json_test.go, providers/netsuite.go, providers/netsuite/connector.go, providers/netsuite/handlers.go, providers/netsuite/types.go, test/netsuite/connector.go, test/netsuite/metadata/example.json, test/netsuite/metadata/main.go
=> [ENG-1941] feat: add netsuite proxy & metadata connector 

common/types.go, providers/salesforce/bulk-delete.go, providers/salesforce/register.go, providers/salesforce/subscribe.go, test/salesforce/subscribe/register.go
```
jaehyunlim@Jaehyuns-MacBook-Pro connectors % go run test/salesforce/subscribe/register.go -unique 12345678901 -arn arn:aws:US-EAST-1:471112904037
time=2025-02-19T16:43:58.197-08:00 level=DEBUG msg="loading credentials file" path=./salesforce-creds.json
time=2025-02-19T16:43:58.199-08:00 level=DEBUG msg="HTTP request" method=POST url=https://ampersand-c-dev-ed.develop.my.salesforce.com/services/data/v59.0/tooling/sobjects/PlatformEventChannel headers="[{Key:Accept Value:application/json}]" bodySize=93
time=2025-02-19T16:43:58.741-08:00 level=DEBUG msg="HTTP request" method=POST url=https://ampersand-c-dev-ed.develop.my.salesforce.com/services/data/v59.0/tooling/sobjects/NamedCredential headers="[{Key:Accept Value:application/json}]" bodySize=204
time=2025-02-19T16:43:58.905-08:00 …
```
=> [ENG-1889] Create Salesforce Subscribe Method

providers/whereby.go
Whereby Provider = "whereby"
URL: https://proxy.withampersand.com/v1/meetings
URL: https://proxy.withampersand.com/v1/meetings/97161604
URL: https://proxy.withampersand.com/v1/meetings
URL: https://proxy.withampersand.com/v1/meetings/97161604
Requesting the paginated list of meetings using limit
URL: https://proxy.withampersand.com/v1/meetings?limit=5
Request the next set of paginated meetings using the cursor parameter from the previous response, along with the limit parameter
URL: https://proxy.withampersand.com/v1/meetings?cursor=eyJ0eXBlIjoib2Zmc2V0IiwidmFsdWUiOiI1In0=&limit=5
Requesting remaining set of meetings by using cursor param
URL: …
=> [CON-1233] feat: Enable proxy: whereby

providers/braze.go
-  Instance Id (workspace)
With `offset` we'd have to make calls until, we get an empty response, or less records then the limit.
=> [CON-1301] feat: Add Braze Connector

providers/instantly.go
It supports batching and pagination.
URL: https://proxy.withampersand.com/v2/campaigns
URL: https://proxy.withampersand.com/v2/campaigns/85dbcb5e-03e9-4824-84a8-f2037d544436
URL: https://proxy.withampersand.com/v2/campaigns
URL: https://proxy.withampersand.com/v2/campaigns/85dbcb5e-03e9-4824-84a8-f2037d544436
URL: https://proxy.withampersand.com/v2/campaigns/0d68b52e-8d35-4a22-88b2-74b1c3d0552d
Requesting a paginated list of campaigns using **limit**:
URL : https://proxy.withampersand.com/v2/campaigns?limit=4
Requesting the next paginated list of campaigns using the **limit** and **starting_after** parameters, where the value of **starting_after** is taken from the **next_starting_after** field in the …
=> [CON-1255] feat: Enable proxy: Instantly(v2)

common/http.go, common/logging/logging.go, test/hubspot/read-associations/main.go
This is a prerequisite for ENG-1816 which will allow us to log differently depending on the desired level of verbosity.
=> [ENG-1816] Add verbose logging distinction

providers/groove/connector.go, providers/groove/handlers.go, providers/groove/supports.go, test/groove/connector.go, test/groove/metadata/main.go
=> [CON-1170] feat: Add Groove Metadata Connector

providers/groove/connector.go, providers/groove/handlers.go, providers/groove/supports.go, test/groove/write/main.go
=> [CON-1172] feat: Add Groove Write Connector

internal/goutils/cloning.go, providers/outreach/metadata.go, test/outreach/metadata/metadata.go
=> [CON-1592] fix(outreach): panic when there is no response

providers/bitbucket.go
URL: http://localhost:4444/2.0/repositories
URL: http://localhost:4444/2.0/workspaces/integrationuser-bitbucket/hooks
URL: http://localhost:4444/2.0/workspaces/integrationuser-bitbucket/hooks/bf9632f3-251e-4726-ac24-8f5ecacd312d
URL: http://localhost:4444/2.0/workspaces/integrationuser-bitbucket/hooks/bf9632f3-251e-4726-ac24-8f5ecacd312d
Bitbucket pagination uses a next link to load more result. The last page has no next link.
Next page:
Invalid URL provided
incomplete payload provided
invalid method provided
=> [CON-1560] feat: Add Bitbucket Connector

providers/livestorm.go
-  It supports OAuth authentication.
-  For OAuth applicaion we must be a partner for this connector. To become a partner, you need to fill out the form(https://livestorm.typeform.com/tech-partners). 
-  Once you submit the form, you will receive an email from the support team, as shown below
**Optional**
- After completing the above two steps, you will receive the client ID and client secret via email.
- The redirect URI supports **https** protocol.
- It supports pagination and batching
URL: http://localhost:4444/v1/events
URL: http://localhost:4444/v1/events/8108d1fe-8e5e-4e08-93b0-4c950d7bbe6d
URL: http://localhost:4444/v1/events
URL: http://localhost:4444/v1/events/8108d1fe-8e5e-4e08-93b0-4c950d7bbe6d
URL: http://localhost:4444/v1/events/733122e3-182f-456d-9369-111dd52c0bef
Requesting …
=> [CON-1191] feat: Add livestorm connector

providers/zendesk.go, providers/zendeskchat/connector.go, providers/zendeskchat/handlers.go, providers/zendeskchat/supports.go, test/zendeskchat/connector.go, test/zendeskchat/metadata/main.go
Note: Refresh token can only be used once.
Tests:
=> [CON-1053] feat: Add ZendeskChat Metadata Connector

providers/zendeskchat/connector.go, providers/zendeskchat/handlers.go, providers/zendeskchat/supports.go, test/zendeskchat/write/main.go
=> [CON-1055] feat: Add ZendeskChat Writer Connector

providers/brevo/connector.go, providers/brevo/handlers.go, providers/brevo/parse.go, providers/brevo/support.go, test/brevo/write/main.go
=> [CON-1438] feat: Add Brevo Write Connector 

providers/capsule/connector.go, providers/capsule/metadata/index.json, providers/capsule/metadata/metadata.go, providers/capsule/metadata/schemas.json, providers/capsule/metadata_test.go, scripts/scraper/capsule/metadata/main.go, scripts/scraper/capsule/metadata/schemas.go, scripts/scraper/salesloft/metadata/main.go, test/capsule/connector.go, test/capsule/metadata/main.go, test/utils/creds.go, tools/scrapper/models.go, tools/scrapper/utils.go
* Developed a scraping script similar to `salesloft`.
* Capsule's documentation is well-structured and consistent, making extraction easy and reliable.
* Value options are conveniently preceded by the prefix **"Accepted values are:"**, simplifying the extraction of `singleSelect` `ValueType`.
Renamed `scrapper` parent directory to `scraper` (turns out 2 different words :laughing: ).
=> [CON-1324] feat(capsule): Metadata

providers/salesforce/register.go, providers/salesforce/subscribe.go, test/ashby/read/main.go, test/ashby/write/main.go, test/gorgias/read/main.go, test/salesforce/subscribe/register.go, test/zendeskchat/read/main.go, test/zendeskchat/write/main.go
- This PR implements updateSubscription method for Salesforce
Test Run result
```
jaehyunlim@Jaehyuns-MacBook-Pro connectors % go run test/salesforce/subscribe/register.go -unique 1234567890 -arn arn:was:<<REDACTED>>
time=2025-03-17T12:53:15.534-07:00 level=DEBUG msg="loading credentials file" path=./salesforce-creds.json
time=2025-03-17T12:53:15.535-07:00 level=DEBUG msg="HTTP request" method=POST url=https://ampersand-c-dev-ed.develop.my.salesforce.com/services/data/v59.0/tooling/sobjects/PlatformEventChannel
time=2025-03-17T12:53:16.200-07:00 level=DEBUG msg="HTTP request" method=POST url=https://ampersand-c-dev-ed.develop.my.salesforce.com/services/data/v59.0/tooling/sobjects/NamedCredential
time=2025-03-17T12:53:16.420-07:00 level=DEBUG msg="HTTP request" method=POST …
```
=> [ENG-2042] Salesforce UpdateSubscription method

providers/bitbucket.go
URL: https://proxy.withampersand.com/2.0/repositories
URL: https://proxy.withampersand.com/2.0/workspaces/integrationuser-bitbucket/hooks
URL: https://proxy.withampersand.com/2.0/workspaces/integrationuser-bitbucket/hooks/47b6a5b8-c6b0-4d12-b32e-48f4d2b5fe4e
URL: https://proxy.withampersand.com/2.0/workspaces/integrationuser-bitbucket/hooks/47b6a5b8-c6b0-4d12-b32e-48f4d2b5fe4e
Bitbucket pagination uses a next link to load more result. The last page has no next link.
Next page:
Invalid URL provided
incomplete payload provided
invalid method provided
=> [CON-1562] feat: Enable Bitbucket Proxy Connector

providers/aha/connector.go, providers/aha/metadata/metadata.go, providers/aha/metadata/schemas.json, providers/aha/metadata/scraping.go, test/aha/connector.go, test/aha/metadata/metadata.go
=> [CON-1539] feat(Aha): add ListMetadata

providers/aha/connector.go, providers/aha/handlers.go, providers/aha/supports.go, test/aha/connector.go, test/aha/read/main.go
=> [CON-1540] feat(Aha): Add Read Operation

providers/salesforce/subscribe.go
```
jaehyunlim@Jaehyuns-MacBook-Pro connectors % go run test/salesforce/subscribe/register.go -unique 1234567890 -arn arn:aws:US-EAST-1:zzzzzzzzzzzz
time=2025-03-20T15:52:52.618-07:00 level=DEBUG msg="loading credentials file" path=./salesforce-creds.json
time=2025-03-20T15:52:52.620-07:00 level=DEBUG msg="HTTP request" method=POST url=https://ampersand-dev-ed.develop.my.salesforce.com/services/data/v59.0/tooling/sobjects/PlatformEventChannel
time=2025-03-20T15:52:53.476-07:00 level=DEBUG msg="HTTP request" method=POST url=https://ampersand-dev-ed.develop.my.salesforce.com/services/data/v59.0/tooling/sobjects/NamedCredential
time=2025-03-20T15:52:53.666-07:00 level=DEBUG msg="HTTP request" method=POST url=https://ampersand-dev-ed.develop.my.salesforce.com/services/data/v59.0/tooling/sobjec …
```
=> [ENG-2068] Fix Diffing logic for UpdateSubscription

providers/lemlist/connnector.go, providers/lemlist/handlers.go, providers/lemlist/supports.go, test/lemlist/connector.go, test/lemlist/metadata/main.go
=> [CON-1460] feat:Add Lemlist Metadata Connector

providers/lemlist/connnector.go, providers/lemlist/handlers.go, providers/lemlist/parse.go, providers/lemlist/supports.go, test/lemlist/read/main.go
=> [CON-1461] feat: Add LemList Read Connector

providers/lemlist/connector.go, providers/lemlist/handlers.go, providers/lemlist/supports.go, test/lemlist/write/main.go
=> [CON-1462] feat:Add Lemlist Write Connector

providers/hunter/connector.go, providers/hunter/handlers.go, test/hunter/connector.go, test/hunter/metadata/main.go
=> [CON-1508] feat: Add Hunter Metadata Connector

providers/hunter/connector.go, providers/hunter/handlers.go, providers/hunter/parse.go, providers/hunter/supports.go, test/hunter/read/main.go
=> [CON-1509] feat: Add Hunter Read Connector

providers/hunter/connector.go, providers/hunter/handlers.go, providers/hunter/supports.go, test/hunter/write/main.go
=> [CON-1510] feat: Add Hunter Write Connector

providers/podium/connector.go, providers/podium/handlers.go, test/podium/connector.go, test/podium/metadata/main.go
=> [CON-1484] feat: Add Podium Metadata Connector

providers/podium/connector.go, providers/podium/handlers.go, providers/podium/parse.go, providers/podium/supports.go, scripts/oauth/token.go, test/podium/read/main.go
=> [CON-1485] feat: Add Podium Read Connector

providers/podium/connector.go, providers/podium/handlers.go, providers/podium/supports.go, scripts/oauth/token.go, test/podium/write/main.go
=> [CON-1486] feat: Add Podium Write Connector

providers/aha/connector.go, providers/aha/handlers.go, providers/aha/supports.go, test/aha/write/main.go
=> [CON-1541] feat(Aha): Add Write Operation

providers/livestorm.go
Livestorm Provider = "livestorm"
URL: https://proxy.withampersand.com/v1/events
URL: https://proxy.withampersand.com/v1/events/4f97ab09-6558-47e7-96e8-b5b365b2b578
URL: https://proxy.withampersand.com/v1/events
URL: https://proxy.withampersand.com/v1/events/4f97ab09-6558-47e7-96e8-b5b365b2b578
URL: https://proxy.withampersand.com/v1/events/4f97ab09-6558-47e7-96e8-b5b365b2b578
Requesting a paginated list of events using **page[size]** param in the URL
URL: https://proxy.withampersand.com/v1/events?page[size]=2
Request the next paginated list of events using the **page[number]** param with **page[size]** param in the URL
URL: …
=> [CON-1193] feat: Enable proxy: Livestorm

providers/atlassian/parse.go, providers/atlassian/read.go, providers/atlassian/read_test.go, test/atlassian/connector.go, test/atlassian/read/main.go
=> [CON-1034] fix(Atlassian): ReadResult.Raw

providers/brevo.go
=> [CON-1441] feat(Brevo): enable Read and Write

providers/happyFox_Chat.go
const HappyFoxChat Provider = "happyFoxChat"
URL: https://proxy.withampersand.com/v1/agents
URL: https://proxy.withampersand.com/v1/agents/67ef8f24fddc2206d5dd0b69
1. Requesting the paginated list of agents using limit and page parameter with value 1 for both.
URL: https://proxy.withampersand.com/v1/agents?page=1&limit=1
2. Requesting the next paginated list of agents giving limit as 1 and page value as 2.
URL: https://proxy.withampersand.com/v1/agents?page=2&limit=1
**NOTE**
You can also use the URL from the "next" field in the previous response to retrieve the next set of results.
Invalid endpoint
=> [CON-1127] feat: Enable proxy: happyFoxChat

providers/monday/connector.go, providers/monday/handlers.go, test/monday/write/write.go
=> [CON-960] feat: add monday write connector

providers/monday/connector.go, providers/monday/handlers.go, providers/monday/utils.go, test/monday/read/read.go, test/monday/read/sample_response/boards.json, test/monday/read/sample_response/boards_withpagination.json, test/monday/read/sample_response/boards_withpagination_2.json, test/monday/read/sample_response/user_withpagination.json, test/monday/read/sample_response/users.json, test/monday/write/write.go
**Tested locally:** 
Added the full json in `sample_response` folder (including pagination tests)
=> [CON-959] feat: add monday read connector functionality

providers/github.go
=> [CON-1580] feat(Github): enable read and write

providers/mixmax/connector.go, providers/mixmax/handlers.go, providers/mixmax/parse.go, providers/mixmax/supports.go, test/mixmax/read/main.go
=> [CON-1453] feat: Add MixMax Read Connector

providers/mixmax/connector.go, providers/mixmax/handlers.go, providers/mixmax/supports.go, test/mixmax/write/main.go
=> [CON-1454] feat: Add MixMax Write Connector

providers/drift/connector.go, providers/drift/handlers.go, providers/drift/parse.go, providers/drift/supports.go, test/drift/read/main.go
=> [CON-1469] feat: Add Drift Read Connector

providers/github/metadata/schemas.json, providers/github/supports.go, scripts/openapi/github/metadata/main.go
The same object had different names for the Write and Read operations. Therefore, this is a fix to use the same object naming convention for both Read and Write operations.
=> fix: Github objectName and schemas

providers/monday.go
=> [CON-963] feat(monday): add support for read

connectors.go, providers/hubspot/record.go, providers/salesforce/record.go, providers/salesforce/subscribe.go, test/hubspot/record/main.go, test/salesforce/record/main.go
Trivial Change. 
Will follow up with Server change as well.
=> [ENG-2167] Rename Subscribe methods and fix typo

providers/aha.go
=> [CON-1544] feat(aha): enable read and write support

common/types.go, providers/marketo/read.go, providers/marketo/types.go, providers/marketo/url.go, test/marketo/read/read.go
This Adds support for Reading Lead Activities.
Close CON-1636, CON-1643
=> [CON-1636] feat: Add Marketo lead activities API support  

providers/heyreach.go
@https://github.com/amp-labs/testdata/pull/42
=> [CON-1417] feat: Enable read + write  : Heyreach

providers/catalog.go
There's a problem I'm working on right now where I need a list of all of the provider names. We don't really expose this, and I'd prefer not to build a custom catalog (this is happening inside of an init function, so I really don't want to deal with errors, which the catalog stuff has). I'm just trying to build a map, and need the names for keys.
=> feat: Add the AllNames function

providers/ashby/handlers.go, providers/ashby/metadata/schemas.json, providers/ashby/supports.go, test/ashby/metadata/main.go, test/ashby/read/main.go, test/ashby/write/main.go
Remove`list`, `create` and `update` suffix from the objectName and use only the standard object name for consistency.
=> [CON-1640] fix(ashby) : remove verb from object name

providers/fireflies.go
URL: http://localhost:4444/
**Get users**
```
{ "query": "{ users { name user_id integrations } }" } 
```
**Add to Live**
```
{
"query": "mutation AddToLiveMeeting($meetingLink: String!) { addToLiveMeeting(meeting_link: $meetingLink) { success } }",
"variables": {
"meetingLink": "https://meet.google.com/yyg-bivu-ojn"
}
}
```
=> [CON-1651] feat: Added fireflies connector

providers/zohocrm/connector.go, providers/zohocrm/subscribe.go, providers/zohocrm/subscriptionEvent.go, providers/zohocrm/types.go, test/zohocrm/connector.go, test/zohocrm/subscribe/subscribe.go
This PR add subscribe action to Zoho CRM.
=> [CON-1646] feat: add zoho subscribe action (WIP)

internal/components/support.go
Insightly supports custom objects, therefore strict support registry is not applicable.
This PR introduces a silent `EndpointRegistry`.
=> feat(components): Support objects - allow-all

common/header.go
Already added this in oauth client
=> [ENG-2239] fix: add `isUnauthorized` to header client

internal/datautils/merge.go, providers/aws/connector.go, providers/aws/errors.go, providers/aws/internal/core/requests.go, providers/aws/internal/identitystore/objects.go, providers/aws/internal/identitystore/read.go, providers/aws/internal/identitystore/schemas.json, providers/aws/internal/ssoadmin/objects.go, providers/aws/internal/ssoadmin/read.go, providers/aws/metadata_test.go, providers/aws/read_test.go, providers/aws/requests.go, providers/aws/responses.go, providers/aws/supports.go, providers/aws/test/read/err-not-supported.json, providers/aws/test/read/groups.json, providers/aws/test/read/instances.json, test/aws/read/all/main.go, test/aws/read/groups/main.go, test/aws/read/instances/main.go, test/aws/read/users/main.go, test/utils/testroutines/comparator.go
* No max page cap is specified. Exceeding this value for the service will return an error. Each service has its own internal cap.
* Token based pagination is natural to CLI and SDK. Pagination is implemented.
* There is no incremental reading.
* Found out that NextPage token is temporary. After some time it becomes invalid. This has no impact on functionality.
From `identitystore` service.
From `identitystore` service.
From `sso-admin` service.
Next page is empty but valid.
Reading each and every possible object.
* ✅ -- means object returns data
* Empty output -- hypothetically it can return data.
* error -- issues with particular Identity Center instance setup.
=> [CON-1667] feat(aws): Read

providers/hubspot.go, providers/salesforce.go
This just adds a few endpoints for hubspot and salesforce so that we can check the health of credentials
=> chore: Add health check endpoints for hubspot and salesforce

internal/components/provider.go, internal/components/transport.go, providers/atlassian/connector.go, providers/hubspot/connector.go, providers/hubspot/metadata.go, providers/hubspot/string.go, providers/hubspot/url.go, providers/keap/connector.go, providers/keap/delete.go, providers/keap/metadata.go, providers/keap/read.go, providers/keap/write.go, providers/klaviyo/connector.go, providers/klaviyo/delete.go, providers/klaviyo/metadata.go, providers/klaviyo/read.go, providers/klaviyo/write.go, providers/marketo/connector.go, providers/marketo/metadata.go, providers/marketo/url.go, providers/zendesksupport/connector.go, providers/zendesksupport/customFields.go, providers/zendesksupport/metadata.go, providers/zendesksupport/read.go, providers/zoom/connector.go, providers/zoom/metadata.go, providers/zoom/read.go, providers/zoom/write.go
Reverts amp-labs/connectors#1523
=> Revert "[CON-1619] feat(modules): Connectors read moduleInfo"

providers/airtable.go, providers/calendly.go, providers/close.go, providers/constantContact.go, providers/helpScoutMailbox.go
Adds AuthHealthChecks for :
- Airtable
- Calendly
- Close
- ConstantContact
- Helpscout
=> feat: Add AuthHealtheck urls

common/types.go, internal/staticschema/core.go, providers/capsule.go, providers/capsule/connector.go, providers/capsule/errors.go, providers/capsule/handlers.go, providers/capsule/read_test.go, providers/capsule/supports.go, providers/capsule/test/read/not-found.json, providers/capsule/test/read/parties/first-page.json, providers/capsule/test/read/parties/last-page.json, providers/capsule/url.go, test/capsule/read/parties/main.go, test/utils/mockutils/mockserver/handlers.go
=> [CON-1325] feat(capsule): Read

providers/capsule/connector.go, providers/capsule/delete_test.go, providers/capsule/errors.go, providers/capsule/handlers.go, providers/capsule/objects.go, providers/capsule/supports.go, providers/capsule/test/write/method-not-allowed.json, providers/capsule/test/write/project/new.json, providers/capsule/test/write/task/new.json, providers/capsule/test/write/unprocessable-payload.json, providers/capsule/url.go, providers/capsule/write_test.go, test/capsule/write-delete/projects/main.go, test/capsule/write-delete/tasks/main.go, test/utils/testroutines/delete.go, test/utils/testroutines/metadata.go, test/utils/testroutines/outline.go, test/utils/testroutines/read.go, test/utils/testroutines/write.go
=> [CON-1326] feat(Capsule): Write

providers/marketo/errors.go, providers/marketo/write.go, providers/marketo/write_test.go, test/marketo/write/write.go
=> [CON-1683] fix: Marketo connector's Write method to accept a flattened record

common/interpreter/responder.go, common/scanning/registry_test.go, providers/monday/connector.go, providers/monday/errors.go, providers/monday/handlers.go, providers/monday/read_test.go, providers/monday/test/boards/err-unknown-property.json, providers/monday/types.go, providers/monday/utils.go, test/monday/metadata/main.go
=> fix(interpreter/monday): Error parsing

providers/utils_test.go, providers/zoom/metadata/schemas.json, providers/zoom/metadata_test.go, scripts/openapi/zoom/metadata/main.go, scripts/openapi/zoom/metadata/meeting/object.go, scripts/openapi/zoom/metadata/user/object.go, tools/fileconv/api3/parameters.go
Abandon usage of in house object names for zoom.
=> fix(zoom): Adapt new object naming

providers/linear.go
const Linear Provider = "linear"
It supports pagination.
URL: https://proxy.withampersand.com/v1/
**Get Issues**
```
query Issues {
issues {
edges {
node {
id
title
}
cursor
}
pageInfo {
hasPreviousPage
hasNextPage
startCursor
endCursor
}
}
}
```
**IssueCreate**
```
mutation IssueCreate {
issueCreate(
input: {
title: "New exception"
description: "More detailed error report in markdown"
teamId: "4f6d6f0b-3d0e-4f0e-acd5-eaee2f77a838"
}
) {
success
issue {
id
title
}
}
}
```
Requesting a paginated list of issues using **first** parameter
```
query Issues {
issues (first: 5){
edges {
node {
id
title
}
cursor
}
pageInfo {
hasPreviousPage
hasNextPage
startCursor
endCursor
}
}
}
```
To request the next paginated list of issues, pass the **pageInfo.endCursor** value as the **after** parameter …
=> [CON-1677] feat: Enable proxy: Linear

common/module.go, common/types.go, providers/salesforce.go, providers/salesforce/connector.go, providers/salesforce/internal/pardot/adapter.go, providers/salesforce/internal/pardot/metadata.go, providers/salesforce/internal/pardot/operations.go, providers/salesforce/internal/pardot/schemas.json, providers/salesforce/metadata.go, providers/salesforce/metadata_test.go, providers/salesforce/params.go, providers/salesforce/read.go, providers/salesforce/read_test.go, providers/salesforce/write.go, test/salesforce/connector.go, test/salesforce/pardot/metadata/emails/main.go
=> [CON-1682] feat(salesforce): AccountEngagement - Metadata

providers/freshdesk.go
[Test-Data Sample](https://github.com/amp-labs/testdata/pull/51)
=> feat: Enable read,write Freshdesk Connector

providers/dixa.go
Installation:
Ampersand Dashboard:
Webhook Response:
=> [CON-1093] feat: Enable Read, Write Dixa Connector

common/paramsbuilder/metadata.go, internal/datautils/timing.go, providers/salesforce.go, providers/salesforce/connector.go, providers/salesforce/internal/pardot/adapter.go, providers/salesforce/internal/pardot/errors.go, providers/salesforce/internal/pardot/operations.go, providers/salesforce/params.go, providers/salesforce/read_test.go, providers/salesforce/test/pardot/read/emails/1-first-page.json, providers/salesforce/test/pardot/read/emails/2-empty-page.json, providers/salesforce/test/pardot/read/emails/err-missing-header.json, providers/salesforce/test/pardot/read/emails/err-missing-query.json, test/salesforce/connector.go, test/salesforce/pardot/read/emails/main.go
Note: you can query dot seperated fields to get nested fields, but they won't appear under the fields only under raw unless we need to change that.
=> [CON-1682] feat(salesforce): AccountEngagement - Read

providers/instantly.go, providers/instantlyai/README.md
**Create custom -tags**
```
https://write.withampersand.com/v1/projects/8b257c62-6b89-4b9b-9271-6fe3f6b700f1/integrations/15134c58-5fd6-40b5-a4b3-0d3a31f1cefa/objects/custom-tags
```
**Update custom-tags**
```
https://write.withampersand.com/v1/projects/8b257c62-6b89-4b9b-9271-6fe3f6b700f1/integrations/15134c58-5fd6-40b5-a4b3-0d3a31f1cefa/objects/custom-tags
```
**Create lead-labels**
```
https://write.withampersand.com/v1/projects/8b257c62-6b89-4b9b-9271-6fe3f6b700f1/integrations/15134c58-5fd6-40b5-a4b3-0d3a31f1cefa/objects/lead-labels
```
**Update lead-labels**
```
https://write.withampersand.com/v1/projects/8b257c62-6b89-4b9b-9271-6fe3f6b700f1/integrations/15134c58-5fd6-40b5-a4b3-0d3a31f1cefa/objects/lead-labels
```
https://github.com/amp-labs/testdata/pull/53
=> [CON-1607] feat: Enable: read + write instantly V2

providers/salesforce/read.go, test/salesforce/read/account/main.go
=> [CON-1735] feat(salesforce): Read until

providers/kaseya.go
{{.workspace}} = withampersand.vsax.net
URL: http://localhost:4444/api/v3/scopes
---
URL: http://localhost:4444/api/v3/notifications/webhooks
---
URL: http://localhost:4444/api/v3/notifications/webhooks/1
---
URL: http://localhost:4444/api/v3/notifications/webhooks/1
Invalid id
---
Invalid payload
=> [CON-1135] feat: add Kaseya VSAX connector

connector/new.go
This Adds initialization to:
- Gitlab connector
- helpscout connector
- groove connector
=> feat: Add initialization to connectors

providers/freshchat.go
Invalid payload
Invalid user id in the url
=> [CON-737] feat: enable Freshchat proxy connector

providers/jobber.go
const Jobber Provider = "jobber"
```  
query Account {
account {
createdAt
id
industry
name
phone
signupName
}
}
```
---
```  
query Products {
products {
totalCount
nodes {
bookableType
category
description
id
}
}
}
```
---
```  
mutation ClientCreate {
clientCreate(
input: {
title: MR
firstName: "Deep"
phones: null
emails: null
properties: null
}
) {
client {
companyName
createdAt
defaultEmails
defaultPhones
firstName
id
isArchivable
isArchived
isCompany
isLead
jobberWebUri
lastName
name
receivesFollowUps
receivesInvoiceFollowUps
receivesQuoteFollowUps
receivesReminders
receivesReviewRequests
sampleData
secondaryName
title
updatedAt
balance
billingAddressPresent
}
}
}
```
---
```  
mutation TaskCreate {
taskCreate(
input: { title: "this is a test" }
clientId: …
```
=> [CON-1743] feat: enable Jobber proxy connector

providers/emailBison.go
It supports Pagination and Batching.
EmailBison Provider = "emailBison"
URL: https://proxy.withampersand.com/leads
URL: https://proxy.withampersand.com/leads/776207
URL: https://proxy.withampersand.com/leads
URL: https://proxy.withampersand.com/leads/984996
Requesting a paginated list of leads using the **page** parameter. Each page displays **15 records by default**.
URL: https://proxy.withampersand.com/leads?page=2
**Invalid Method**
**Invalid Endpoint**
=> [CON-823] feat: Enable Proxy : emailBison

providers/helpscoutmailbox/connector_test.go, providers/helpscoutmailbox/handlers.go, providers/helpscoutmailbox/test/conversations.json, providers/helpscoutmailbox/test/mailboxes.json, providers/helpscoutmailbox/test/unsupported.txt, providers/helpscoutmailbox/test/users.json
- Adds mock tests
-  fix read next page issue
=> feat: Add helpscout connector mock tests

providers/kaseya.go
* {{workspace}} = withampersand.vsax.net
Replaced the old icon (had aspect ratio issues) with the new one below.
URL : /api/v3/scopes
URL: /api/v3/notifications/webhooks
URL: /api/v3/notifications/webhooks/4
URL: /api/v3/notifications/webhooks/4
Invalid payload
invalid http method
invalid id
=> [CON-1137] feat: enable Kaseya VSAX proxy connector

providers/podium/handlers.go, test/podium/read/main.go
Adds support for incremental reads for 
- Contacts
- Locations
- Reviews, Review Invites
Tests:
=> feat: Add Incremetal Read support Podium connector

connector/new.go
This adds the clari copilot connector to the connector.New function
=> feat: Add Clari Copilot connector to connector.New

providers/pinterest.go
Mailmonkey using API key/Oauth2 with scopes/Password, etc.
```
POST https://write.withampersand.com/v1/projects/8b257c62/integrations/ed0de679-5bd2-4da4-b7af-e42d8cdac042/object/boards
```
```
POST https://write.withampersand.com/v1/projects/8b257c62/integrations/ed0de679-5bd2-4da4-b7af-e42d8cdac042/object/boards
```
```
POST https://write.withampersand.com/v1/projects/8b257c62/integrations/ed0de679-5bd2-4da4-b7af-e42d8cdac042/object/catalogs
```
https://github.com/amp-labs/testdata/pull/57
=> [CON-1401] feat: Enable proxy: read+write pinterest

providers/Fathom.go
URL: https://proxy.withampersand.com/external/v1/meetings
URL: https://proxy.withampersand.com/external/v1/teams
URL: https://proxy.withampersand.com/external/v1/[team_members](http://localhost:4444/external/v1/team_members)
There is no POST, PUT, DELETE, or PATCH methods.
Fathom pagination works using a cursor.
The server returns a fixed number of items and includes a new cursor for the next page in the response.
The client uses this cursor to load the next set of items.
First Page
Next Page
Wrong URL path
=> [CON-1765] feat(fathom): enable proxy support

common/http.go, common/printable.go
```
$> cd test/salesforce/read/account
$> go run ./main.go
{"time":"2025-07-10T11:54:05.544395-07:00","level":"DEBUG","msg":"loading credentials file","path":"./salesforce-creds.json"}
{"time":"2025-07-10T11:54:05.547407-07:00","level":"DEBUG","msg":"HTTP request","method":"GET","url":"https://orgfarm-b3cb75c050-dev-ed.develop.my.salesforce.com/services/data/v59.0/query?q=SELECT+Id%2CName%2CBillingCity%2CIsDeleted%2CSystemModstamp+FROM+Account+WHERE+SystemModstamp+%3E+2024-08-28T13%3A47%3A37Z+AND+SystemModstamp+%3C%3D+2025-09-01T00%3A00%3A00Z","correlationId":"02c73f5b-06ed-437c-ab29-a55cce8006ce","headers":{"Accept":"application/json"}}
{"time":"2025-07-10T11:54:05.832444-07:00","level":"DEBUG","msg":"HTTP response","method":"GET","url":"https://orgfarm-b3cb75c050-dev-ed.develop.my.salesf …
```
=> feat: log http bodies

providers/fireflies.go
**For liveMeetings object:**
**For bites object:**
**For mettingTitle:**
Link pull request to testdata repo which contains installation file: https://github.com/amp-labs/testdata/pull/65
=> [CON-1664] feat: Enable read and write : fireflies

providers/hubspot/associations.go, providers/hubspot/parse.go
Reverts amp-labs/connectors#1863
=> Revert "chore: Add a few logging statements for associations"

providers/lemlist.go
Mailmonkey using API key
[Test file](https://github.com/amp-labs/testdata/pull/61)
=> [CON-1465] feat: enable read, write Lemlist connector

providers/braze/connector.go, providers/braze/handlers.go, providers/braze/parse.go, providers/braze/support.go, test/braze/write/main.go
=> [CON-1892] feat: Add Braze Write connector

common/urlbuilder/url.go, common/urlbuilder/url_test.go, providers/atlassian.go, providers/atlassian/authmetadata.go, providers/atlassian/authmetadata_test.go, providers/atlassian/authmetamodel.go, providers/atlassian/connector.go, providers/atlassian/delete.go, providers/atlassian/delete_test.go, providers/atlassian/errors.go, providers/atlassian/metadata.go, providers/atlassian/metadata_test.go, providers/atlassian/modules.go, providers/atlassian/read.go, providers/atlassian/read_test.go, providers/atlassian/write.go, providers/atlassian/write_test.go, providers/utils.go, test/atlassian/connector.go, test/atlassian/jwt/main.go, test/atlassian/metadata/main.go, test/atlassian/write-delete/main.go
=> [CON-1620,CON-1621] feat(atlassian): getModuleURL

providers/hubspot.go, providers/hubspot/associations.go, providers/hubspot/connector.go, providers/hubspot/metadata.go, providers/hubspot/metadata_test.go, providers/hubspot/modules.go, providers/hubspot/url.go, providers/hubspot/url_test.go, providers/utils_test.go, test/avoma/read/main.go, test/avoma/write/main.go, test/flatfile/metadata/main.go, test/flatfile/read/main.go, test/flatfile/write/main.go, test/teamleader/write/main.go
Ran all tests under test/hubspot & added a new test
=> chore: hubspot url selection

common/types.go, providers/hubspot/subscriptionEvent.go, providers/salesforce/subscriptionEvent.go, providers/zohocrm/subscriptionEvent.go
This PR enables event message interface to return underlying message with RawMap() method.
=> [ENG-2414] Modifty event interface to return raw map

providers/google.go, providers/google/connector.go, providers/google/internal/contacts/adapter.go, providers/google/internal/contacts/metadata.go, providers/google/internal/contacts/schemas.json, providers/google/metadata_test.go, scripts/openapi/google/contacts/main.go, scripts/openapi/google/internal/files/file.go, scripts/openapi/google/internal/files/people.json, test/google/calendar/read/calendarList/main.go, test/google/calendar/read/events/main.go, test/google/connector.go, test/google/people/metadata/calendarList/main.go
=> [CON-2007] feat(google): Contacts Metadata

internal/jsonquery/converters.go, providers/google/connector.go, providers/google/internal/contacts/adapter.go, providers/google/internal/contacts/delete.go, providers/google/internal/contacts/errors.go, providers/google/internal/contacts/objectNames.go, providers/google/internal/contacts/read.go, providers/google/internal/contacts/write.go, providers/google/internal/core/commands.go, providers/google/test/contacts/delete/error-contact-group-not-found.json, providers/google/test/contacts/delete/error-my-connection-not-found.json, providers/google/test/contacts/write/contactGroups/new.json, providers/google/test/contacts/write/myConnections/new.json, providers/google/write_test.go, test/google/contacts/write-delete/contactGroups/main.go, test/google/contacts/write-delete/myConnections/main.go, test/utils/testscenario/crud.go
=> [CON-2009] feat(google): Contacts Write

common/stringMap.go, common/types.go, providers/salesforce/parse.go, providers/salesforce/read.go, providers/salesforce/record.go, test/avoma/read/main.go, test/avoma/write/main.go, test/flatfile/metadata/main.go, test/flatfile/read/main.go, test/flatfile/write/main.go, test/salesforce/read/account/main.go, test/salesforce/read/associations/main.go, test/teamleader/write/main.go
- Subqueries can be used to fetch associations when reading. Source in comments.
- Added a test for associations
=> [ENG-2405] feat: add salesforce associations

common/scanning/credscanning/fields.go, providers/gitlab.go, test/gitlab/connector.go
This Adds:
- updates the connector AuthType to Custom.
- live tests to use the New Auth scheme
Tests:
=> feat(gitlab): update the connector tests to use PATs, updates AuthType

providers/discourse.go
=> [CON-795] feat: enable proxy support for Discourse connector

connector/new.go, providers/flatFile.go, providers/flatfile/connector.go, test/flatfile/connector.go
The flatfile name shouldn't be in CamelCase or PascalCase. this PR fixes it.
=> fix: flatfile name casing

providers/teamleader.go
=> [CON-1353] feat(teamleader): enable read and write

providers/campaignMonitor.go
Link pull request to testdata repo which contains installation file: https://github.com/amp-labs/testdata/pull/76
=> [CON-1377] feat: [campaignMonitor] Enable read and write.

providers/breakcold.go
URL: https://proxy.withampersand.com/tags
URL: https://proxy.withampersand.com/tags
URL: https://proxy.withampersand.com/tags/423e5d5d-d91e-4399-bd30-2e80229a8a04
URL: https://proxy.withampersand.com/tags/423e5d5d-d91e-4399-bd30-2e80229a8a04
**Invalid endpoint**
**Invalid method**
=> [CON-2053] feat: [breakcold] Enable proxy

common/auth.go
Add the ability to attach tokens to contexts, and read them back
=> add WithAuthToken and GetAuthToken

providers/pylon/handlers.go
The page limit should be less than 1000 not 1000.
=> fix(pylon): update default page limit

connector/new.go, providers/microsoft/connector.go, providers/microsoft/errors.go, providers/microsoft/handlers.go, providers/microsoft/metadata/README.md, providers/microsoft/read_test.go, providers/microsoft/test/read/unknown-resource.json, providers/microsoft/test/read/users/1-first-page.json, providers/microsoft/test/read/users/2-second-page.json, test/microsoft/read/main.go
=> [CON-1803] feat(microsoft): Read

providers/asana/objectNames.go, test/asana/write/main.go
=> fix (Asana): add missing write objects

providers/gong/flows.go, providers/gong/metadata/schemas.json, providers/gong/objectNames.go, providers/gong/read.go, scripts/openapi/gong/metadata/main.go, test/gong/read/flows/read.go
Extend Gong read to support flows object
=> [CON-2229] gong: extend read support
