amp-labs/connectors

common/json.go
common/types.go
connectors.go
salesforce/client.go
salesforce/connector.go
salesforce/errors.go

This PR addresses a few small issues:
* Exposes JSONHTTPClient in the connector interface (avoids having to explicitly cast to get the client)
* Allow relative URLs to be passed in to JSONHTTPClient (full URLs will be auto-constructed)

Expose JSONHTTPClient in the Connector interface

---

common/types.go
salesforce/errors.go

Some Salesforce errors are structured as JSON. This PR adds the ability to introspect that JSON and return a more specific/relevant error to the caller.

[ENG-206] feat: Handle common Salesforce errors

---

common/oauth.go
hubspot/params.go
salesforce/params.go

Right now whenever a token is refreshed, we just discard the result. This leads to a lot of waste since we're effectively refreshing each time a workflow runs.
This PR makes it possible for us to be notified whenever a token is refreshed, so that we can persist it back to the database. This should cause fewer token refreshes over time.

feat: Add a callback to save OAuth tokens

---

common/types.go
connectors.go
hubspot/metadata.go
hubspot/modules.go
hubspot/params.go
hubspot/read.go
hubspot/search.go
salesforce/errors.go
salesforce/metadata.go

* Adds ListObjectMetadata to describe an object's properties
* Adds ObjectMetadata to hold an object's metadata
* Adds the ListObjectMetadata function in the Connector interface

[ENG-420] Add ListObjectMetadata to Salesforce & Hubspot connectors

---

README.md
test/salesforce.go

Also updated test code to use the concrete type, since we'll need it when we extend the test with Salesforce-specific methods.

docs: update README with the different ways to initialize a connector

---

common/types.go
connectors.go
hubspot/metadata.go
salesforce/metadata.go

* Instead of failing completely, this returns successful results & a list of errors indexed against the object name
Once the PR is merged, I will create a PR in the server repo to update the connector dependency & work off this new structure

[ENG-436] Modify ListObjectMetadata to return metadata & a list of errors

---

hubspot/README.md
hubspot/read.go
hubspot/search.go
hubspot/types.go

This PR updates the search function to the hubspot connector to allow filters & sorting.
However, this causes an issue with the initialization method `connectors.Provider.New` which returns the `Connector` interface, as the interface doesn't have `Search` as a method on it. 
To solve this, we have to either instantiate the connector via the package directly - `hubspot.New`, or add `Search` to the Connector interface & return a `NotImplemented` for Salesforce. I have opted for the first to avoid adding unnecessary methods to the interface. We will need to change this in the server codebase post merge.

[ENG-423] Add Search functionality

---

hubspot/read.go
hubspot/search.go
hubspot/types.go

The hubspot `Read` method redirects a request to `Search` if `ReadParams.Since` is set, but unknown to the caller, they will get cut off at 10,000 records. This sorts the result by the id that the request can be continued via a search if required.

chore: Sort hubspot reads by default

---

common/json.go
common/parse.go
hubspot/get.go
hubspot/metadata.go
hubspot/post.go
hubspot/read.go
hubspot/search.go
salesforce/bulkwrite.go
salesforce/get.go
salesforce/metadata.go
salesforce/patch.go
salesforce/post.go
salesforce/read.go
salesforce/write.go

I was writing this for another PR (not yet published) when I realized the changes here are substantial enough to warrant a dedicated PR of its own.
Basically I needed access to the HTTP status code. This led me down a rabbit hole to eventually re-working the JSON return type. The caller can still get the ajson.Node body, but they can also access the response code, the response body -- and crucially then can even unmarshal the response in to a structure if it makes sense to do so. This should cut down on boilerplate code in other places.

[ENG-493] feat: Improve the JSON response interface to be more flexible

---

common/types.go

Success should always be present in the result, but the other fields might not always be there.

chore: Update WriteResult type

---

common/types.go
hubspot/errors.go
hubspot/types.go

Correcting an invalid assumption about the lastmodifieddate field for hubspot objects. Verified that this field exists for all objects using the properties endpoint - 
```
{
"Result": {
"companies": {
"DisplayName": "companies",
"FieldsMap": {
"hs_lastmodifieddate": "Last Modified Date"
}
},
"contacts": {
"DisplayName": "contacts",
"FieldsMap": {
"hs_lastmodifieddate": "Object last modified date/time"
}
},
"deals": {
"DisplayName": "deals",
"FieldsMap": {
"hs_lastmodifieddate": "Last Modified Date"
}
},
"line_items": {
"DisplayName": "line_items",
"FieldsMap": {
"hs_lastmodifieddate": "Last Modified Date"
}
},
"taxes": {
"DisplayName": "taxes",
"FieldsMap": {
"hs_lastmodifieddate": "Object last modified date/time"
}
},
"tickets": {
"DisplayName": "tickets",
"FieldsMap": { …
```

chore: Use hs_lastmodifeddate field for hubspot objects

---

hubspot/write.go

This PR adds write functionality for the hubspot connector. This relies on functionality introduced in #40 
Related:
* https://github.com/amp-labs/connectors/pull/40
Example run:
```
$> go run ./main.go
{
"success": true,
"objectid": "29651",
"data": {
"company": "Compendia Bioscience Life Technologies",
"createdate": "2023-12-21T21:51:13.394Z",
"email": "nathanjacobson@kuhic.io",
"firstname": "Jarod",
"hs_all_contact_vids": "29651",
"hs_email_domain": "kuhic.io",
"hs_is_contact": "true",
"hs_is_unworked": "true",
"hs_lifecyclestage_lead_date": "2023-12-21T21:51:13.394Z",
"hs_object_id": "29651",
"hs_object_source": "INTEGRATION",
"hs_object_source_id": "2317233",
"hs_object_source_label": "INTEGRATION",
"hs_pipeline": "contacts-lifecycle-pipeline", …
```

[ENG-493] feat: add Hubspot write functionality

---

hubspot/parse.go
hubspot/read.go
hubspot/search.go
hubspot/types.go

* The `contacts` object silently fails to return objects according to criteria even if we use `hs_lastmodifieddate`. 
* According to https://community.hubspot.com/t5/APIs-Integrations/CRM-V3-API-Search-issue-with-Contacts-when-using-Filters/m-p/324617 (and testing), the right field to use is `lastmodifieddate` for contacts and `hs_lastmodifieddate` for other objects.
Also shifts a function that gets the last ID of a result into the connector, so that the server has minimal knowledge of the internal structure of a connector's response
* The check for which `lastmodifiedfield` to use is a direct string comparison, so we need to be careful (https://linear.app/ampersand/issue/ENG-520/how-do-we-handle-inconsistent-plural-object-name)

chore: Update contacts lastmodifieddate field

---

go.mod
go.sum
hubspot/search.go
salesforce/metadataApi.go
test/metadata/main.go

Replacing custom created xmlData struct to xmldom library. 
There is issue/bug with the library which is when parsing xml string into the struct, it omits namespaces in attributes. However, the only place we use that is in test runs to create xmldom.Node object, just for test run purpose. 
```
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Header xmlns="http://soap.sforce.com/2006/04/metadata"><AllOrNoneHeader><allOrNone>true</allOrNone></AllOrNoneHeader><SessionHeader><sessionId>00DDp000000JQ4L!ASAAQOszeyj5XanytfgLLuflNdcTWzijpNIV4bezmW9e0Nnm07UrduwdpiU7MXa6BqOXRP9s0Pq1L.2BE__U.7.F7PpPA37Q</sessionId></SessionHeader> …
```

[ENG-518] refactor: Replace XMLData struct to xmldom package. 

---

common/csv.go
common/error.go
common/http.go
common/json.go
hubspot/connector.go
hubspot/params.go
salesforce/bulkwrite.go
salesforce/connector.go
salesforce/metadataApi.go
salesforce/params.go

* `JSONHTTPClient` expects the response to be of a json type. 
* This PR refactors it so that it wraps around an `HTTPClient`, which makes no assumptions about the response type and returns the raw `http.Response` as it is. 
* `JSONHTTPClient` now wraps around this `HTTPClient` and parses the response before returning it.
There is no difference WRT to the functionality of all of these components. This PR just makes it easier for us to reuse the tried & tested HTTP client.
This should also open up the possibility to handle CSV/XML exchanges better for a future refactor.
Tested by making sample calls to Hubspot/Salesforce `Read` & `ListObjectMetadata`

feat: Add HTTPClient

---

common/http.go

This passes back any error encountered while making a request without modifying it

chore: Pass back raw net/http/Client.Do error

---

salesforce/metadata.go

* The correct salesforce version now comes from `APIVersion()`.

fix: Fix outdated salesforce version for ListObjectMetadata

---

hubspot/connector.go
hubspot/metadata.go
hubspot/modules.go
hubspot/params.go
hubspot/read.go
hubspot/search.go
hubspot/url.go
hubspot/write.go

* Our current setup always requires a module to be input which is a problem for proxy requests since a CRM specific prefix is automatically added to it. 
* This PR adds an empty module which we can use in the server repo for proxy request building

[ENG-620] chore: Add empty module to enable hubspot proxying

---

README.md
connectors.go
hubspot/connector.go
providers/catalog.go
providers/catalog_test.go
providers/providers.yaml
providers/types.go
salesforce/connector.go
salesforce/errors.go
salesforce/params.go
test/bulkwrite/main.go
test/creds.go
test/metadata/main.go
test/salesforce/event-flow/main.go
test/salesforce/read-write.go

* Reads values from catalog to set internal connector state
* This PR intentionally doesn't try to replace URL constructions, etc - we need to find a better way to do that in cases of Salesforce, etc. Sometimes we need base parts of the URL and sometimes we need the suffix of a URL, etc.
* Figure out what is the maximum amount of information we can transfer from code into the YAML without breaking anything or having too many overlapping fields in the YAML. For example, in metadata requests, we need only `services/data/v59.0/...` but for a read request we need `https://......./services...` - how do you store the least amount of information to get the most out of this?
* Refactor these connectors to get rid of struct members like 'BaseURL' or 'Domain' and work off a `ProviderInfo` member?

[ENG-684] Update hubspot & SF connectors to consume catalog

---

scripts/oauth/token.go
scripts/proxy/proxy.go
utils/credentials.go

The `oauth.go` script creates the token as a file, which the `proxy.go` script then uses to run a server that forwards requests to the provider.

[ENG-729] feat: Add helper scripts for running proxy & obtaining oauth token

---

providers/catalog.go
providers/catalog_test.go

The proxy and API responses differ when the response from the API is Bad Request(400). The proxy returns an empty body. The API has some details.
Showing pagination sample. The response data will have _next_page_ in the metadata.pagination object.
If the next_page value is not "null", There are more pages.
Then we can access the next page, by adding the page query parameter in the next response.

[ENG-788] feat: Add SalesLoft connector

---

providers/catalog.go
providers/catalog_test.go

No required variables.
An application can only retrieve an access token for a user once every 60 seconds.
The api uses query parameters to paginate. Retrieving a paginated response.
Using the next field value to access the next page.

[ENG-787] feat: Add Outreach connector

---

providers/catalog.go
providers/catalog_test.go

No variables required
No refresh token, the Access token does not expire.
Retrieving data that has paginated values.
We use the value next_cursor from above to retrieve the next page list of values, but the parameter is now start_cursor

[ENG-833] feat: Add Notion connector

---

providers/catalog.go
providers/catalog_test.go

Fixed the failed test issue, CloseCRM is no longer mentioned in the list of the failed ones:
--- FAIL: TestReadInfo (0.00s)
--- FAIL: TestReadInfo/notion (0.00s)
c:\Users\nadia\Desktop\projects\connectors\providers\catalog_test.go:284: [Valid Notion provider config with no substitutions] Expected support: {false false false false false}, but got: {false true false false false}
FAIL
coverage: 68.8% of statements
FAIL	github.com/amp-labs/connectors/providers	0.278s
FAIL

[ENG-792] feat: Add Close CRM connector (fix)

---

providers/catalog.go
providers/catalog_test.go

URL: <localhost:4444/v2/lists/new_test_list_2/entries/b10dcb40-95bc-4c34-82e5-c573f75c5673l> 
URL: <localhost:4444/v2/lists/new_test_list_2/entries/query> 
URL: <localhost:4444/v2/lists/new_test_list_2/entries/b10dcb40-95bc-4c34-82e5-c573f75c5673> 
URL: <localhost:4444/v2/lists/new_test_list_2/entries/b10dcb40-95bc-4c34-82e5-c573f75c5673> 
URL: <localhost:4444/v2/lists/new_test_list_2/entries/b10dcb40-95bc-4c34-82e5-c573f75c5673> 
Direct pagination works fine
Going through the connector both http and httpS generates the following error
GET https://localhost:4444/v2/lists?limit=3&offset=0
Error: connect ECONNREFUSED 127.0.0.1:4444
Could be related to the issues with my local env, would propose to reproduce it on the server.

[ENG-790] feat: Add Attio connector

---

providers/catalog.go
providers/catalog_test.go

workspace variable is required. It's given by Gong. Sample is us-49467 in https://us-49467.api.gong.io/
It's currently private, The only OAuth user who can access the app is the Creator. Publishing it requires filling a form.
Also the token endpoint requires Basic Authorization header whose values is base64 encoded `client_id:client_secret`
For pagination, we would have the cursor value in the records object below: We would in turn use that value as the query parameter in the next request.

[ENG-786] feat: Add Gong connector

---

providers/catalog.go
providers/catalog_test.go
providers/types.gen.go
providers/types.yaml

* OAuth tokens obtained from providers can come with extra metadata that contain information about -
* The account/workspace that the token is associated with (referred to as the `workspaceRef` here on)
* The user that the token is associated with (referred to as the `consumerRef` here on)
* The scopes related to the token
* For example, a salesforce token looks like - 
```
{
"access_token": "1234",
"refresh_token": "4321",
"scope": "refresh_token api id full",
"instance_url": "https://ampersand-dev-ed.my.salesforce.com",
"id": "https://login.salesforce.com/id/00D5x0000019AWSGA1/0053x000000orG1ABI",
"token_type": "Bearer",
"issued_at": "1680295102278"
}
```
* and a notion token looks like - 
```
{
"access_token": "1234",
"refresh_token": "4321",
"workspace_id": …
```

[ENG-758] Add metadata fields to catalog

---

providers/catalog.go
providers/catalog_test.go

+ Ran Linter
+ Catalog tests passing
+ Created PR from non-main branch
URL: <localhost:4444/v1/deals> 
URL: <localhost:4444/v1/deals>
URL: <localhost:4444/v1/deals/2>
URL: <api.pipedrive.com/v1/deals/1> - even the direct del doesn't work
Although the scopes contain "base,deals:full" permission. And the description of this scope tells that it is possibly to read (works), update (works) and delete (doesn't). Have raised this as an issue at the dev forum - https://devcommunity.pipedrive.com/t/deal-inserts-and-updates-work-fine-via-api-but-delete-fails/7977

[ENG-798] feat: Add Pipedrive connector

---

providers/catalog.go
providers/catalog_test.go

None
No refresh tokens. The access token does not expire.
Now pagination has 2 flavours: 
Retrieving paginated data in a listing API(GETs)
Using the `pages.next.starting_after` to retrieve the next page data
Retrieving paginated data in a searching API(POSTs)
Using the `pages.next.starting_after` to retrieve the next page data. Now in the request body.

[ENG-827] feat: Add Intercom connector

---

providers/catalog.go
providers/catalog_test.go

None
URL: http://localhost:4444/user/me
Describes the requester user
URL: http://localhost:4444/organizations/<ID>
Describes organization
URL: http://localhost:4444/organizations/<ID>/invitations
Invite user to organisation with email.
URL: http://localhost:4444/organization_memberships/<ID>
Remove member from org. No content response
URL: http://localhost:4444/organizations/<ID>/invitations
Lists user invitations to the org. Empty response
URL: http://localhost:4444/organization_memberships/?organisation=<OrganisationURI>
Lists all users that belong to org. No pagination limit.
Lists all users that belong to org. Page limit 1.
Lists all users that belong to org.

[ENG-866] feat: Add Calendly connector

---

salesforce/bulkwrite.go

Job result information had "errorMessage" field omitted. 
Test
```
=============================================
Testing Complete Failure
=============================================
Upload complete.
{
"state": "UploadComplete",
"jobId": "750Dp0000090ZSUIA2"
}
Write Result
{
"jobId": "750Dp0000090ZSUIA2",
"state": "Failed",
"jobInfo": {
"id": "750Dp0000090ZSUIA2",
"object": "Touchpoint__c",
"createdById": "005Dp000003Cd1SIAS",
"externalIdFieldName": "external_id__c",
"state": "Failed",
"operation": "upsert",
"columnDelimiter": "COMMA",
"lineEnding": "LF",
"numberRecordsFailed": 0,
"numberRecordsProcessed": 0,
"errorMessage": "InvalidBatch : Field name not found : ContactId__c",
"apexProcessingTime": 0,
"apiActiveProcessingTime": 0,
"apiVersion": 59,
"concurrencyMode": "Parallel", …
```

[ENG-858] fix: add error message

---

providers/catalog.go
providers/catalog_test.go

URL: <localhost:4444/crm/v6/Contacts?fields=Full_Name,Account_Name> 
URL: <localhost:4444/api/v2/unattended_computer/group> - fails if run via proxy
In case it is run directly, works fine - 
URL: <localhost:4444/api/v2/unattended_computer/group>
URL: <localhost:4444/api/v2/unattended_computer/group> - fails
But if we hit the endpoint directly - everything works fine

[ENG-800] feat: Add ZohoCRM connector

---

providers/utils.go

We're using `html/template` for substitutions. This probably won't work as intended, since part of html templating includes making the contents HTML-safe, which (for things like raw URLs) we probably don't want.
This PR just switches over to `text/template` so that we don't get this unintended side-effect.

fix: Use text/template rather than html/template

---

.github/PULL_REQUEST_TEMPLATE/new_connector.md
Makefile
scripts/bash/pr_options.sh

@RajatPawar please have a look
Create `<filename>.md` under `.github/PULL_REQUEST_TEMPLATE`.
Ensure that filename has no spaces. It is used as query parameter.
Bash script implies Pull Request URL based on current branch.
Appends for every template a respective query parameter. See [template qp](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request).
[Github docs.](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
In order to see the changes in action `.github/PULL_REQUEST_TEMPLATE` must be present on default branch first!

build: add support for multiple Github Templates

---

salesforce/bulkwrite.go

There was if statement that will never be executed because the condition is always false. It did not affect anything and didn't do any harm, but need to be cleaned up.

fix silent bug

---

providers/catalog.go
providers/catalog_test.go
scripts/oauth/token.go

> WARN [runner/source_code] Failed to get line 391 for file utils/credentials.go: invalid file line index0 (390) >= len(fc) (92) 
WARN [runner/source_code] Failed to get line 402 for file utils/credentials.go: invalid file line index0 (401) >= len(fc) (92) 
::error file=utils/credentials.go,line=391,col=1::getFromReader returns generic interface (T) (ireturn)
::error file=utils/credentials.go,line=402,col=1::get returns generic interface (T) (ireturn)
make: *** [Makefile:14: fix] Error 1
Workspace: `org5bd08fdd`
Scopes: `https://org5bd08fdd.crm.dynamics.com/user_impersonation,offline_access`
As of now substitution works for BaseURL. Here user impersonation scope itself contains workspace variable.
Acquires AccessToken from Microsoft Entra ID that has preconfigured permissioning to access …

[ENG-872] feat: Add Microsoft Dynamics 365 Sales connector

---

providers/catalog.go
providers/catalog_test.go
scripts/oauth/token.go
scripts/proxy/proxy.go

After creating AT/RT tokens for Ms Dynamics Sales I used them to make proxy requests. After 1 hour and 20 min token expired any proxy requests would fail with 401 Unauthorized.
Oauth2 library we use states that we must specify `expiry` field for it to consider using `refresh_token`.
[Reference](https://pkg.go.dev/golang.org/x/oauth2#Token).
There are different formats for time parsing so in `cred.json` we could use enum.
Contents of `cred.json` file:
```
{
"accessToken": "...",
"refreshToken": "...",
"expiry": "2024-03-26T16:22:32.768450621+02:00",
"expiryFormat": "RFC3339Nano"
}
```
Other connectors may have different field name, time format or even null value.
For example Zendesk returns null value signifying no refresh_token flow. More thought should be put to make it universal.

fix: Trigger Refresh grant on expired AT

---

providers/catalog.go
providers/catalog_test.go
scripts/oauth/token.go

Closes https://github.com/amp-labs/connectors/issues/135
scopes: `https://www.googleapis.com/auth/calendar`
URL: http://localhost:4444/v3/users/me/calendarList
List all calendars that belong to user
Go to google calendar and create an event for yourself, we will use it in the next set of requests. Back to postman using id of one of those calendars, retrieve events of that calendar, then query single event by that id.
URL: http://localhost:4444/v3/calendars/dobrbobr2022@gmail.com/events/7pv3h8pq79p0lga9v46c3ju2mp
We can change the end of an event to last longer, things immidietly are reflected in calendar.
URL: http://localhost:4444/v3/calendars/dobrbobr2022@gmail.com/events/7pv3h8pq79p0lga9v46c3ju2mp
Unlike PATCH it must include the whole payload, otherwise you will get `400`.
If you …

feat: Add Google Calendar connector

---

providers/catalog.go
providers/catalog_test.go

Closes #144 
scopes: `read write`
workspace: `d3v-ampersand`
URL: http://localhost:4444/api/v2/account
Get account description.
Creating chat can be only done after you create visitors.
URL: http://localhost:4444/api/v2/chats
Update visitor name of the chat.
URL:  http://localhost:4444/api/v2/chats/2404.20015967.U8hSBNJn7ON55
Remove the chat.
URL:  http://localhost:4444/api/v2/chats/2404.20015967.U8hSBNJn7ON55
Chat list cannot be paginated with the same query paramaters as in Zendesk Support. Listing agents "claims" to support pagination but rather it is peeking id and seeking certain number of records in back or forward time directions, response has no page related fields.

feat: Add Zendesk Chat connector

---

providers/catalog.go
providers/catalog_test.go

Closes #146 
Workspace: `d3v-ampersand`
Scopes: `read write`
URL: http://localhost:4444/api/v2/account/settings
List account settigns for Zendesk urser.
URL: http://localhost:4444/api/v2/tickets
List all tickets
URL: http://localhost:4444/api/v2/tickets
Create ticket.
URL: http://localhost:4444/api/v2/tickets/15
Update subject of the ticket.
URL: http://localhost:4444/api/v2/tickets/15
Delete ticket.
Ticket is also gone at Zendesk Support portal.
URL: http://localhost:4444/api/v2/channels/voice/phone_numbers.json
List phone numbers
URL: http://localhost:4444/api/v2/help_center/integration/account_custom_claims
Custom claims of help center
Please add screenshots that show successful pagination using the connector. 
URL: http://localhost:4444/api/v2/users?page[size]=1
Get users displaying …

feat: Add Zendesk Support connector

---

providers/catalog.go
providers/catalog_test.go
providers/types.gen.go
providers/types.yaml

We currently support only OAuth 2.0 Authorization code flow (& refresh token flow), but there's [multiple types of grants possible with OAuth 2.0](https://oauth.net/2/grant-types/). 
Some providers that we are working on are using these flows, so it might be a good idea to specify the grant types.

feat: Add oauth grant types to catalog

---

providers/catalog.go
providers/catalog_test.go
test/salesforce/bulkdelete/main.go
test/salesforce/metadata/main.go

One of the new providers used the wrong type, this fixes it.
I also ran ran gofumpt, in case you're wondering about the formatting changes.

fix: Correct the catalog to use new bulkwrite types

---

providers/catalog.go
providers/catalog_test.go

Closes #154
None
Auth flow uses PKCE, it is a mandatory requirement.
Requesting a list of records
The response has `offset` indicating there is a next page, using it to get the next page values

feat: Add Airtable Connector

---

connectors.go
mock/connector.go
mock/errors.go
mock/params.go
providers/catalog.go
providers/types.gen.go
providers/types.yaml

Certain tests are difficult to run against real providers. A prime example of that is a rate-limiting test, since we simply don't have enough actual data (in our test instance of salesforce, for example) to reliably trigger a 429 code. Another example is a load test, since we want to test the load tolerance of *our* system, not the load tolerance of the actual providers.
This PR introduces a mock connector, whose behavior can be dynamically configured via callback functions. It strives to be minimal, and leave the mock details up to the consumer.
This would be useful both in unit tests, as well as end-to-end tests.

feat: Add a mock connector

---

providers/catalog.go
providers/catalog_test.go

None
Sample retrieving paged result:
Retrieving the next page
closes #191

feat: Add Timely auth connector

---

providers/catalog.go
providers/catalog_test.go

<Please mention any variables you had to use for the provider's info>
* {{scope}}
Resolves #185
When calling an API use/2.3/ instead of v2
URL: <localhost:4444/2.3/answers?order=desc&sort=activity&site=stackoverflow> 
URL: <localhost:4444/2.3/questions/render> 
)
Requested pagesize= 2, which returned 2 elements. "has_more" = true indicates that more data is available.

Add StackExchange connector

---

microsoftdynamicscrm/read_test.go
providers/catalog.go
providers/catalog_test.go

* {{scope}}
Resolves #205
use 2.0 instead of v2 in the API call
URL: <localhost:4444/2.0/sheets> 
List Sheets
URL: <localhost:4444/2.0/folders/3384993222289284/sheets> 
Create Sheet
URL:<localhost:4444/2.0/folders/3384993222289284>
Update Folder
URL:<localhost:4444/2.0/sheets/557813268959108>
Delete Sheet
GET <localhost:4444/2.0/sheets?pageSize=2&page=3>
List Sheets with pagination, 2 items per page, display page 3

Smartsheet: Add connector

---

common/json.go
connectors.go
outreach/README.md
outreach/client.go
outreach/connector.go
outreach/errors.go
outreach/methods.go
outreach/params.go
outreach/parse.go
outreach/provider.go
outreach/read.go
outreach/string.go
providers/catalog.go
providers/catalog_test.go
test/outreach/read/read.go
utils/credentials.go

This PR adds the Outreach read capability.
- Updated the jsonResponse to allow application/vnd+.json. All providers implementing JSONAPISpecification will have this as the Content-Type in the response.
Written test to read an Object from Outreach api. The test reads users object from the outreach API.
draft PR for #187

feat: Add outreach read connector

---

providers/catalog.go

Does as the title says. This is necessary because the OpenAPI validations are failing, and frankly the frontend doesn't need this to be visible anyways.

fix: Remove the mock connector from the catalog

---

scripts/oauth/token.go

* Prints token out using `fmt.Printf` which also prints the unexported `raw` field, helping us get a hold of the extra metadata that is sent along with the token.

fix: Print token in script

---

providers/catalog.go
providers/catalog_test.go
scripts/proxy/proxy.go
test/outreach/read/read.go

Closes #241
Monday doesn't support refresh_token grant. Our library musn't even attempt to make such call in a first place. As of now the error would look as follows:
```
http: proxy error: Get "https://api.monday.com/v2/get_schema": oauth2: "unsupported_grant_type" "Unsupported grant_type param. Please use authorization_code"
```
```
{
"access_token":"...",
"scope":"me:read,boards:read,boards:write,docs:read,docs:write,workspaces:read,workspaces:write,users:read,users:write,account:read,notifications:write,updates:read,assets:read,updates:write,teams:read,tags:read,webhooks:write,webhooks:read",
"token_type":"bearer"  
}
```
No explicit scopes.
URL: `http://localhost:4444/v2`
Get boards.
```
{
"query":"query { boards {id name type communication board_kind creator {name}}}"
}
```
Create …

feat: Add Monday auth connector

---

hubspot/modules.go
hubspot/params.go

This adds the validation of the module in hubspot package. The client is expected to provide this during Connector creation.

fix: add module validation for Hubspot connector

---

providers/catalog.go
providers/catalog_test.go

Closes #242 
```
{
"access_token":"....",
"expires_in":604800,
"refresh_token":"...",
"state":"",
"token_type":"bearer"
}
```
We are using default data center by omitting it. We couldv'e specfied `eu.`
```
"substitutions": {
"dataCenter" : ""
}
```
URL: http://localhost:4444/forms
List forms.
URL: http://localhost:4444/forms
URL: http://localhost:4444/forms/BvXy6fa1
Changed form tittle. We are giving an array of changes to apply.
URL: http://localhost:4444/forms/BvXy6fa1
Same as Patch but the whole object is published.
URL: http://localhost:4444/forms/BvXy6fa1
Remove form.
URL: http://localhost:4444/forms?page=1&page_size=3
URL: http://localhost:4444/forms?page=2&page_size=3

feat: Add Typeform auth connector

---

providers/catalog.go
providers/catalog_test.go

Changes to the base URL as per Gong API webcast 
+ branch
+ tests
##GET direct no shards
##GET proxy no shards
Closes #267

Gong workspace substitution removal

---

providers/catalog.go
providers/catalog_test.go

no variables
Resolves #226 
AuthURL used is a mock URL, since Zuora does not require a code for receiving a token.
Use /v1/ instead of /v2/ in the API calls.
URL: <localhost:4444/v1/object/product/8a8aa2028ef98921018eff24f27d799b> 
Retrieve a Product
URL: <localhost:4444/v1/object/product> 
Create a Product
URL: <localhost:4444/v1/object/product/8a8aa2028ef98921018eff24f27d799b> 
Update a Product
URL: <localhost:4444/v1/object/product/8a8aa2028ef98921018eff24f27d799b> 
Delete a Product
Get a list of products without pagination
Get a list of products with pagination (3 items per page, land on page 3)

Zuora: Add connector

---

providers/catalog.go
providers/catalog_test.go

Closes https://github.com/amp-labs/connectors/issues/280
dropboxSign Provider = "dropboxSign"
URL: http://localhost:4444/v3/account?email_address=sanjaykanth@gmail.com
URL: http://localhost:4444/v3/account/create
URL: http://localhost:4444/v3/account

feat: Add DropboxSign auth connector

---

providers/catalog.go
providers/catalog_test.go

Closes #146 
Workspace: d3v-ampersand
Scopes: read write
Access token doesn't expire. There is no refresh token.
In postman the proxy is set to Ampersand: `{{amp}}=https://proxy.withampersand.com`
URL: https://proxy.withampersand.com/api/v2/tickets
List Tickets.
URL: https://proxy.withampersand.com/api/v2/tickets
Create ticket.
URL: https://proxy.withampersand.com/api/v2/tickets/1
Update ticket.
URL: https://proxy.withampersand.com/api/v2/tickets/8
Remove ticket.
Deleting or getting resource one more time returns expected error from API.
DELETE https://proxy.withampersand.com/api/v2/tickets
GET https://proxy.withampersand.com/api/v2/bananas
URL: https://proxy.withampersand.com/api/v2/users?page[after]=eyJvIjoiaWQiLCJ2IjoiYVpQMTJrRDZGd0FBIn0%3D&page[size]=1

enable proxy: Zendesk Support

---

providers/catalog.go
providers/catalog_test.go

No fishy behaviour observed. All the request/responses were parsed correctly.
URL: https://proxy.withampersand.com/api/v2/emailAddresses
URL: https://proxy.withampersand.com/api/v2/emailAddresses
URL: https://proxy.withampersand.com/api/v2/templates/1
URL: https://proxy.withampersand.com/api/v2/emailAddresses/4
Requeating a paginated list of emailAddresses:
URL: https://proxy.withampersand.com/api/v2/emailAddresses?count=false&page%5Bsize%5D=10
Requesting the next page using the next link provided in the previous request.
Going to the next and last page:
closes #279

feat: Update outreach proxy support

---

providers/catalog.go
providers/catalog_test.go

The OAuth token returned by Gong does not actually include a client_id field, which led to the following error:

fix: Remove client_id as a token metadata field from Gong connector

---

providers/catalog.go
providers/types.gen.go
providers/types.yaml

This PR introduces a `displayName` field to ProviderInfo and adds display names for Zendesk Chat and Zendesk Support

feat: introduce `displayName` to catalog

---

outreach/errors.go
outreach/metadata.go
test/outreach/metadata/metadata.go

Implemented the ListMetdata function for the Outreach connector. Loops through the objects one by one and from the response we generate the metadata field values or errors.
- Include tests for the success and failures.
Running the tests:

feat: Implement Outreach ListMetadata

---

providers/catalog.go

Pinterest Provider = "pinterest"
**SCRIPT:**
**POSTMAN:**
URL: http://localhost:4444/v5/ad_accounts/549767715102/ads
URL: http://localhost:4444/v5/ad_accounts/549767715102/ads
URL: http://localhost:4444/v5/ad_accounts/549767715102/ads
URL: http://localhost:4444/v5/pins/1054334962754985249
Requesting a paginated list of ads using page_size :
URL: http://localhost:4444/v5/ad_accounts/549767715102/ads?page_size=2
Requesting the next page using the bookmark value from the previous response
URL: http://localhost:4444/v5/ad_accounts/549767715102/ads?bookmark=P3A2ODcyNjY3NTk5NDF8MHwwfDEsMnwwfDExMzI4NDQzNzIzMTc0ODYqR1FMKnxlYTFhYTZjNDNjNmIwYzIyNGNlMGQzOWM4YzRjMGQ3MTQ1ZGY3YWNlYTVmNGFhZTk5NThhYzM3Y2E4OTk4OThmfE5FV3w=
closes #386

feat: Add Pinterest Auth connector

---

.github/PULL_REQUEST_TEMPLATE/new_connector.md
providers/catalog.go

Closes #382 
Workspace = `ampersand`
Redirect URI with `http` is not allowed, hence no local testing.

feat: Add Aha! connector

---

common/scrapper/models.go
intercom/metadata/schemas.json
intercom/metadata_test.go
scripts/scrapper/intercom/metadata/main.go
test/intercom/metadata/main.go

Scrapper collects LIST schemas and artifically pluralises it to match ObjectNames.
Since HTML docs are consistent and there are no edge cases this should work.
I checked some API endpoints and URI paths match.
NOTE: Scrapper tool requests URLs with dedicated schema on HTML file. It doesn't parse API endpoints (they do have response example, but harder to parse).
* Changed Mock tests focusing on LIST schemas.
* Manual test to use the same ObjectName for both Read/ListObjectMetadata methods.
* Scrapper filters out schemas that have nothing to do with Lists.
There are only 19 schemas that we pluralise. Reference:
```
help_centers
activity_logs
admins
articles
collections
companies
contacts
conversations
data_attributes
data_events
linked_objects
notes
segments
subscription_types
tags
teams …
```

fix: Intercom ObjectNames match Read and Metadata methods

---

common/paramsbuilder/params.go
intercom/connector.go
intercom/params.go
intercom/read.go
test/intercom/connector.go

We only want to have modules for products like Hubspot where there are several APIs for different product areas, and the APIs are versioned differently or have different ways of constructing URLs from object names. For Intercom, there's only a single REST API and there aren't sub-products. Requiring the connector to be initialized with a Module parameter (`intercom.WithModule(intercom.DefaultModule)`) adds unnecessary complexity and decreases usability. 
cc @Cobalt0s

Remove Modules from Intercom connector

---

common/naming/plural.go
common/naming/singular.go
common/naming/singular_test.go

#Description
This module is yet not used anywhere, this PR just introduces concepts.
Naming module provides:
* SingularString, PluralString `types` with slice type counterparts
* ToPlural, ToSingular respective `conversions`. (Unit tests check conversion between each other).
* Creation path:
* via `constructor`, which enforces language format. (Better than raw string conversion, hence it is a struct)
* via `JSON` file, where after realising itself into an object it will `automatically apply format` and acts as a string not a struct. (This can be useful for scrapping tool which reads/writes files and makes the contract clear).
@laurenzlong here is the `naming` package you mentioned.

add: Module naming; support Singular/Plural strings

---

common/scrapper/files.go
common/types.go
intercom/metadata.go
intercom/metadata/scrapping.go
salesloft/metadata.go
salesloft/metadata/index.json
salesloft/metadata/schemas.json
salesloft/metadata/scrapping.go
salesloft/metadata_test.go
scripts/scrapper/intercom/metadata/main.go
scripts/scrapper/salesloft/metadata/main.go
test/salesloft/metadata/main.go

Closes #370
Every "square" is a section opening each we get a list of URLs that describe CRUD operations for that group.
Given index of URLs for every operation, open each and navigate to `Schema` section. This represenets response body. Save those fields under schemas.
This method surfaces data stored under `salesloft/metadata/schemas.json`. This can be repopulated by scrapper tool.

feat: Deep connector Salesloft (ListMetadata) 

---

providers/catalog.go

Added Grant Type and removed Token Metadata scope field as it isn't returned in the token (see attached screenshot)
fixes #366

Wrike auth connector update

---

common/parse.go
common/types.go

We are allowing returning nil in parseJSONResponse, this will cause panics in parseResult function. This fixes that.

fix: avoid panics incase nil response

---

connectors.go
go.mod
go.sum
gong/README.md
gong/client.go
gong/connector.go
gong/errors.go
gong/methods.go
gong/params.go
gong/parse.go
gong/provider.go
gong/read.go
gong/read_test.go
gong/string.go
gong/test/read.json
gong/test/read_cursor.json
test/gong/read/read.go
utils/credentials.go

+ Linter issues fixed
+ Unit tests passed
Gong Read Connector gets the list of records (objects). For calls objects type there are 179 records in the sandbox database. 
Gong always returns the first 100 records and a cursor in case there's more. So for calls it returns both the raw feed and a cursor at the end.  
Test location: test\gong\read\read.go
closes #247

feat: Add Gong Read connector

---

providers/utils.go

There have been several instances where it would have been nice to override the providers in the connectors repo. As an example, testing out the proxy logic without needing to open a PR in connectors -> open a PR in server -> deploy preview environment. This is excessive for what amounts to changing a bool from false to true.
This PR allows us to override providers from the server repo. The general use-case here is for testing, but theoretically we could use it to disable problematic features in prod (e.g. a feature we marked as stable which turns out to have a show-stopping bug). Obviously we'd need to be very selective about when it's used, in general the source of truth should still live in the connectors repo. However being able to override is useful.

feat: Add providers.SetInfo

---

providers/catalog.go
providers/types.gen.go

I couldn't start local proxy for Salesloft. It had missing GrantType which is required now.
All connectors in catalog to include AuthorizationCode as GrantType.
@eberle1080 is this change ok?

fix: add AuthorizationCode for missing Grant Types

---

intercom/connector.go
intercom/delete.go
intercom/delete_test.go
intercom/read.go
intercom/read_test.go
intercom/write.go
intercom/write_test.go
test/utils/mockutils/server.go

As I recall from the documentation their server defaults to some API version. Since we are passing it to one method all other methods should be consistent.
Linter: https://github.com/amp-labs/connectors/pull/480

fix: pass API version Header for all Intercom methods

---

providers/catalog.go
providers/types.gen.go
providers/types.yaml
providers/utils.go
scripts/oauth/token.go
scripts/proxy/proxy.go

For client credentials, the authURL parameter will be empty. Right now it's not allowed to be empty. This PR allows it to be empty.

fix: make the authURL parameter optional

---

intercom/metadata/index.json
salesloft/metadata/index.json
salesloft/metadata/schemas.json
salesloft/metadata_test.go
scripts/scrapper/salesloft/metadata/main.go
test/utils/mockutils/server.go
tools/scrapper/files.go
tools/scrapper/models.go

* Salesloft object names use kebab case from Docs, modified that to snake case which is used in URL path. This turns `saved-list-views` into the `saved_list_views` (making read and metadata use the same object name).
* Index of HTML Docs used for Metadata are sorted in order to ensure consistent output. (I ran scrapper for Intercom as well). No functional change.

fix: Salesloft Metadata to match SnakeCase of ObjectName

---

providers/types.gen.go
providers/types.yaml

See title. ReadProviders is failing because of this.

fix: make OauthOpts optional, since not all providers need it

---

.github/workflows/linter.yml
gong/parse.go
gong/read.go
gong/read_test.go
test/gong/read/read.go

The linter was somehow set to `continue-on-error: true` before, so the CI passes even when the linter fails. This PR re-enables the linter and also fixes existing lint issues. 
I also pinned golangci to v1.54 (same version we use in the server), not latest.

build: re-enable linter in Github actions

---

salesloft/read.go
salesloft/read_test.go
salesloft/test/read-list-accounts-since.json
salesloft/test/read-list-accounts.json
scripts/oauth/token.go
scripts/proxy/proxy.go
test/utils/mockutils/checks.go
test/utils/mockutils/server.go

Ampersand schedules `read` without time interval by default.
About 30% of Read APIs use `updated_at` query parameter. It is **15** out of **48** total objects as of June 10th, 2024.
Salesloft read method is now capable of returning a subset of data since specified time focusing on recent updates.

feature: add Salesloft Read.Since

---

providers/catalog.go

Closes #458 
HeaderName: "Api-Key"
API key type of authentication
use api instead of v2
Screenshot of a printed token is not available as it is generated on the platform
URL: <localhost:4444/api/catalogs/catalogName/items/1> 
URL: <localhost:4444/api/catalogs/catalogName> 
URL: <localhost:4444/api/catalogs/catalogName/items/1> 
URL: <localhost:4444/api/catalogs/catalogName/items/1> 
URL: <localhost:4444/api/catalogs/catalogName/items/1> 
**After pagination**
`PageSize` and `Page` parameters added. The response includes `nextPageUrl` and `previousPageUrl`

Iterable:add connector

---

scripts/proxy/proxy.go

Provider such as Marketo fails if passing an empty slice of scope. Removing it resolves it.

fix: Attach scopes when required

---

salesloft/metadata/queryParamStats.json
scripts/oauth/token.go
scripts/proxy/proxy.go
scripts/scrapper/salesloft/metadata/main.go
tools/scrapper/files.go
tools/scrapper/models.go

Salesloft has some query parameters that can be used for performing Read method using `Since` qurying.
Added a method that can be executed at any time to see stats on frequency usage of query params in Salesloft APIs.

scrapper: Salesloft, collect Statistics on query params

---

providers/catalog.go

Closes #509 
None
Uses API Key scheme, InHeader. 
Requesting a paginated list of contacts
Using the `nextPageToken` to request next page contacts. As observed no more pages, as there is no `nextPageToken`

feat: Add MessageBird auth connector

---

providers/catalog.go
scripts/proxy/proxy.go

Closes #514 
Username is Track API Key
Password is empty.
Changed code such that username and password are not required for basic authentication unless both are empty. Prints a warning instead of failing execution.
N/A
Tell customer.io to identify user. As the matter of fact any data or even no payload sent via any POST endpoint will always produce `{"success": true}`. All these endpoints are used for some kind of tracking those users. It is usefull to know which page a person opened and if user switched from anonymouse to registered and then associating this data.
URL: http://localhost:4444/identify
N/A

feat: Add Customer.io Data Pipelines connector

---

providers/catalog.go

Closes #515 
All API is part of payed version!
Assistant is in beta  and doesn't look that it is payed.
List AI modules.
URL: http://localhost:4444/v1/models
Create image using propmt text. (cost 2 cents)
URL: http://localhost:4444/v1/images/generations'
Create assistant.
URL: http://localhost:4444/v1/assistants
With Header: OpenAI-Beta: assistants=v2
There is no PUT or PATCH, modifications are done via POST, example:
Also creating a speech out of text succeds. The output is in audio/mpeg format. (cost: 1 cent)
URL: http://localhost:4444/v1/audio/speech
Remove assitant.
URL: http://localhost:4444/v1/assistants/asst_zo1oGsgTtqwU4UPAe9d496Uj
After creating 3 assistants, list them puting a limit of 2 items per page.
http://localhost:4444/v1/assistants?limit=2 …

feat: Add OpenAI connector

---

providers/catalog.go

Closes #512
N/A
Only one endpoint exists to send messages. It is a conversation with AI chat bot.
Version header must be provided for a request to succeed.
Proxy can pass version header and POSTing a message succeeds:
```
curl --location --request POST 'http://localhost:4444/v1/messages' \
--header 'anthropic-version: 2023-06-01' \
--data-raw '{
"model": "claude-3-opus-20240229",
"max_tokens": 1024,
"messages": [
{
"role": "user",
"content": "Hello, world"
}
]
}'
```
Without version header we get error 400:
```
{
"type": "error",
"error": {
"type": "invalid_request_error",
"message": "anthropic-version: header is required"
}
}
```

feat: Add Anthropic connector

---

providers/brevo.go

Closes #511 
None
Pagination uses `limit` and `offset` parameters. Requesting Contacts using the values.
Requesting the next offset value, and since limit+offset > `count`,  we have reached the last record.

feat: Add Brevo auth connector

---

providers/sendGrid.go

Closes #510 
None
Requesting a paginated list of templates.
Using the `next` in `_metadata` to retrieve the next page token.

feat: Add SendGrid auth connector

---

providers/geckoboard.go

Closes #523 
No version is required when making API calls
It was not possible to print the token as it is generated via the platform
No documentation on pagination but after testing, the limit param is supported
URL: <localhost:4444/datasets> 
URL: <localhost:4444/v2/sales.by_year/data> 
URL: <localhost:4444/datasets/sales.by_year> 
URL: <localhost:4444/v2/datasets/sales.by_year> 
**After pagination**

Feat Add Geckoboard Connector

---

.github/PULL_REQUEST_TEMPLATE/proxy_connector.md
common/xml.go
common/xquery/queries.go
dynamicscrm/metadata.go
dynamicscrm/metadata_test.go
go.mod
go.sum
providers/dynamics.go
salesforce/metadataApi.go
test/dynamicscrm/connector.go
test/dynamicscrm/metadata/main.go
tools/connectorgen/template/test/connector.go.tmpl
utils/credentials.go

Based on https://github.com/amp-labs/connectors/pull/535
xmldom depends on xpath. Updating xpath to lates breaks the former. Panic is thrown by method that returns single values.
Xpath syntax worked before with older version.
Xpath library suggests query libraries for use which seem to be better updated. Switching to `antchfx/xmlquery` does the trick.
Also this library is wrapped to better handle panics and nil cases with NullObject pattern.
Library [Documentation](https://github.com/antchfx/xmlquery):
Dynamics CRM proxy is enabled. The code changes from this PR https://github.com/amp-labs/connectors/pull/535 are fully covered in this PR. This part closes #206

fix: Panic thrown by DynamicsCRM.Metadata, change XML lib

---

common/parse.go
gong/connector.go
gong/errors.go
gong/params.go
gong/parse.go
gong/read.go
gong/read_test.go
gong/url.go
test/gong/connector.go
test/gong/read/read.go
tools/connectorgen/template/base/connector.go.tmpl

* Parse error in the format that gong utilises
* Method `count number of records` - counts records manually, because currentPageSize doesn't reflect this
* Removed Workspace and APIModule options
* Response parsing to use `jsonquery` for a shorter form, adapted tests respectively
* Tiny changes to connector gen template files
* Pull connector instantiation for testing that can be used by other 'Methods'
Making request using existing `Read` test returns output as expected.

fix: Gong remove options, add error handler

---

common/paramsbuilder/params.go
connector/connector.go
connector/params.go
docusign/connector.go
docusign/params.go
hubspot/connector.go
hubspot/modules.go
hubspot/params.go
mock/connector.go
mock/params.go
outreach/connector.go
outreach/params.go
salesforce/connector.go
salesforce/params.go

* paramsbuilder.Workspace is used by relevant connectors, method returns substitutions map making usage concise
* Based on Hubstpot formulated behaviour of paramsbuilder.Module with fallback module
* all connectors delegate to paramsbuilder, shorter format

[ENG-1257] feat: Add WithWorkspace, connectors delegate to paramsbuilder

---

outreach/parse.go

Switched to the ajson wrapper for consistency(and cleanness) in the package.

clean: switch to ajson wrapper (Outreach deep connector)

---

.github/workflows/generate-json-catalog.yaml

Adding this explicitly is what makes the commit actually work and not reject the update. I don't know why because the checkout is supposed to work off the latest commit anyway.
I tweaked this action on [a test PR ](https://github.com/amp-labs/connectors/pull/663)to commit the file to the PR ref, and it successfully generated and committed the update json file. I assume the same should now carry over to main.
Also, adding the ops account to the 'Allow bypassing branch protection' list isn't the full picture. You also have to create a custom role with the 'bypass branch protection' permission and assign it to the ops account.

chore: Add explicit ref to checkout step in action

---

.github/PULL_REQUEST_TEMPLATE/new_connector.md
README.md
common/paramsbuilder/params.go
common/paramsbuilder/variables.go
common/paramsbuilder/variables_test.go
connector/connector.go
docusign/connector.go
dynamicscrm/connector.go
examples/auth_connectors/salesforce/salesforce.go
examples/deep_connectors/salesforce/salesforce.go
gong/connector.go
hubspot/connector.go
hubspot/modules.go
hubspot/params.go
intercom/connector.go
outreach/connector.go
providers/utils.go
providers/utils_test.go
salesforce/connector.go
salesloft/connector.go
scripts/oauth/token.go
scripts/proxy/proxy.go

Catalog substitutions were changed from `map` to `concrete type`.
We already have connector options defined under `paramsbuilder` package.
Parameters that are of CatalogVarialbe type can be directly passed into variadic `ReadInfo` function.
Any new parameters that will participate in substitution algorithm must return SubstitutionPlan. For example `paramsbuilder.Workspace` returns SubstitutionPlan{from:"workspace", to: "DesiredValue"}.
Also, sometimes ReadInfo or ReadCatalog perform adjustment of default catalog beforehand. This is now reflected in CustomizedCatalog(... CatalogOption). This allows stacking of 2 variadic configurations of CatalogOption and CatalogVariable.
We could clean up providers/utils.go even further. For example clone method is very general in nature and can be used …

[ENG-1257] define: CatalogVariable type for substitution

---

providers/crunchbase.go

Closes #622 
None
Crunchbase rest API is a read-only API.
Searching for organizations with certain criterias. default limit = 100 
Using the last item uuid in the response for the next request.
NOTE: We'd have to do this until we get an empty response or understand that we have iterated through all records using the `count` key.

feat: Add Crunchbase auth connector

---

providers/utils.go
providers/utils_test.go

Sometimes the server needs to read providerInfo without doing any variable substitutions (e.g. in GetProvider API call), we should not error out, otherwise the UI library will fail to work for providers that have substitution variables (such as Salesforce) because the UI library needs to call GetProvider first to see if it needs to render a workspace entry box.

fix: do not return error in ReadInfo if there are no substitution variables

---

common/jsonquery/converters.go
common/jsonquery/defaults.go
common/jsonquery/errors.go
common/jsonquery/queries.go
common/jsonquery/queries_test.go
common/types.go
salesforce/errors.go
salesforce/test/create-ok.json
salesforce/test/invalid-field-upsert.json
salesforce/test/success-with-errors.json
salesforce/test/unknown-field.json
salesforce/write.go
salesforce/write_test.go

Write seems to have had an issue when parsing errors during StatusOK. General convertor to golang data types is utilised as errors item has a free structure. This example again was taken from documentation as I failed to produce this case. (I would end up with real error -- non 2xx response codes).
```
{
"id": "001RM000003oLruYAE",
"success": false,
"errors": [
{
"statusCode": "MALFORMED_ID",
"message": "malformed id 001RM000003oLrB000",
"fields": []
}
]
}
```
Enforced required ObjectName.
Manual test for Saleforce which does Read+Write is still passing.

test: mock Salesforce Write method

---

common/paramsbuilder/variables.go
common/paramsbuilder/variables_test.go
common/substitutions/registry.go
common/substitutions/substitutions.go
providers/utils.go

This is refactoring. Moving algorithm that performs catalog varialbe substitution into a separate package. Providers package should be more concise.
As an example running Read on DynamicsCRM where workspace is required produces same output prior to change.

tidy: Relocate substitution algorithm to package

---

examples/utils/oauth2.go
providers/utils.go
scripts/proxy/proxy.go

In the server, I need to set some additional oauth options, but I can't with the current client setup. This PR allows passing in arbitrary OAuth client options.
The goal here is to set a callback function so the server can see when a token is refreshed.

feat: Allow OAuth clients to be configured more easily

---

providers/serviceNow.go

Updated pull request for ServiceNow
Old PR - https://github.com/amp-labs/connectors/pull/487
ServiceNow Provider = "serviceNow"
**SCRIPT:**
**POSTMAN:**
URL: https://proxy.withampersand.com/api/now/table/sys_user
URL: https://proxy.withampersand.com/api/now/table/incident
Requesting a paginated list of users using limit:
URL: https://proxy.withampersand.com/api/now/table/sys_user?sysparm_limit=1
closes #384

feat: Enable proxy: ServiceNow connector

---

common/paramsbuilder/params.go
common/scanning/credscanning/provider.go
connector/params.go
docusign/params.go
dynamicscrm/params.go
gong/params.go
hubspot/params.go
intercom/params.go
outreach/params.go
salesforce/params.go
salesloft/params.go
zendesksupport/params.go

As we are moving towards implementing **non oauth2** deep connectors there should be an option of selecting other auth clients used by connector.
`paramsbuilder.Client` is a parameter that now has 2 choices of either using Oauth2 or Basic authentication.
Every connector sets up parameters by delegation so their methods on the surface are not affected. Every connector will still use `WithClient` method making the naming predictable, however the passed arguments will differ.

add: Basic auth client as connector option

---

providers/mixmax.go

ProviderInfo has disappeared for some reason, therefore I have added it back.
Logo and Icon URLs have also been added.

Fix MixMax connector, add media

---

providers/zendesk.go

Each mode shares the same logo, icon.
**Reason:** Icon looks better than logo (has no name).
**zendeskSupport** and **zendeskSupport** use identical Media. 2 providers though 1 company.

add: Logo - Zendesk Support

---

providers/podium.go

Add Icon and Logo URLs to Podium connector.
Note: Neither regular nor dark-type icons were available for Podium. Logos were used instead.

Feat: Add media to Podium connector

---

providers/bynder.go

Add Icon and Logo URLs to Bynder connector.
Note: The regular version of the icon was not available on the media uploader, therefore the logo was used instead.

Feat: Add media to Bynder connector

---

providers/maxio.go

Add Icon and Logo URLs to Maxio connector.
Note: There is no regular type of Icon, therefore a regular logo was used instead.

Feat: Add media to Maxio connector

---

providers/dixa.go

Add Icon and Logo URLs to Dixa connector.
Note: Regular type of icon is not available on the uploader. Used regular Logo instead.

Feat: Add media to Dixa

---

providers/shopify.go

Add Icon and Logo URLs to Shopify connector.
Note: No logo for the regular mode

Feat: Add media to Shopify connector

---

providers/freshservice.go

Add Icon and Logo URLs to Freshservice connector.
Note: Freshservice is a part of Freshworks platform and, therefore, is sharing Freshworks icons as per the media uploader.

Feat: Add media to Freshservice

---

providers/freshsales.go

Add Icon and Logo URLs to Freshsales.
Note: Freshsales is a part of the Freshworks platform and therefore will share the Freshworks Icon and Logo as per the media generator.

Feat: Add media to Freshsales connector

---

providers/freshdesk.go

Add logo and icon URLs to Freshdesk connector
Note: Freshdesk is a part of the Freshworks platform and therefore will share the Freshworks Icon and Logo as per the media generator.

Feat: Add media to Freshdesk

---

providers/teamleader.go

Add Icon and Logo URLs to the Teamleader connector.
Note: Icon has been used for both logo and icon

feat: Add media to Teamleader

---

providers/jotform.go

Add Icon and Logo URLs to Jotform connector.

feat: Add media to Jotform

---

providers/braintree.go

feat: Add media to Braintree

---

providers/pipeliner.go

Add Icon and Logo URLs to Pipeliner connector.
Note: Neither regular nor dark-type icons were available for Pipeliner. Logos were used instead.

feat: Add media to pipeliner

---

providers/chargeOver.go

feat: Add media to ChargeOver

---

providers/sellsy.go

Add Icon and Logo URLs to Sellsy connector.

feat: Add media to Sellsy

---

providers/pipedrive.go

Add Icon and Logo URLs to Pipedrive connector.

feat: Add media to Pipedrive

---

common/paramsbuilder/module.go
hubspot/connector.go

Sometimes sub-product APIs might have different prefixes, not necessarily suffixes. Also the goal of this field is represents the name of the product that a caller of the library puts into the `WithModule` function, so name is more appropriate.

feat: rename Module.Suffix to Module.Name

---

providers/campaignMonitor.go

Add Icon and Logo URLs to campaignMonitor connector.

feat: Add media to CampaignMonitor

---

providers/klaviyo.go

Add Icon and Logo URLs to Klaviyo connector.
Note: Dark mode Icon is not available, used Logo instead.

Feat: Add media to klaviyo connector

---

providers/keap.go

Add Icon and Logo URLs to Keap connector.
Note: Icons not available for both dark and regular modes, logos were used instead.

Feat: Add media to Keap connector

---

providers/copper.go

Add Icon and Logo URLs to Copper connector.
Note: The icon has a background.

Feat: Add media to Copper connector

---

atlassian/authmetadata.go
atlassian/authmetadata_test.go
atlassian/authmetamodel.go
atlassian/client.go
atlassian/connector.go
atlassian/errors.go
atlassian/modules.go
atlassian/params.go
atlassian/test/cloud-id.json
atlassian/url.go
docusign/authmetamodel.go
test/atlassian/auth-metadata/main.go
test/atlassian/connector.go

Closes #709
This adds Jira connector with an ability to retreieve metadata information describing authentication.
CloudID is the only property of concern. This will be used when building API URL paths.
PostAuthInfo returns CloudID **based on the workspace name**.

feat: Deep connector Jira (AuthInfo)

---

atlassian/authmetadata.go
atlassian/connector.go
atlassian/parse.go
atlassian/read.go
atlassian/read_test.go
atlassian/test/jql-error.json
atlassian/test/path-not-found.json
atlassian/test/read-issues.json
providers/atlassian.go
test/atlassian/auth-metadata/main.go
test/atlassian/read/main.go

Closes #709 
Read operation uses search API endpoint to return Jira issues.
The data returned from `issue endpoint` is not returned untouched.
Fields property contains data of interest, the gist of it.
Id property is manually attached. This is the only relevant property outside of fields.
Manual script to retrieve list of issues.

feat: Deep connector Jira (Read)

---

atlassian/metadata.go
atlassian/metadataFields.go
atlassian/metadata_test.go
atlassian/test/issue-metadata.json
test/atlassian/metadata/main.go

Closes #709 
Implemented ListObjectMetadata by making an API call to `field` endpoint which returns fields of Jira issue.
Reference: https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-fields/#api-rest-api-2-field-get

feat: Deep connector Jira (Metadata)

---

providers/outreach.go

I tested against data in https://github.com/amp-labs/testdata/blob/main/outreach/write.http

Enable Outreach write functionality

---

providers/seismic.go

Seismic **requires scopes** to be passed.
Tried to generate token locally without scopes getting the same error.

fix: Scopes required: Seismic

---

providers/atlassian.go
test/outreach/read/read.go

It was too long and looked awkward in the dashboard.

chore: update display name of Atlassian connector

---

atlassian/authmetadata.go

Internally memoize the cloudID field so it can be used for subsequent calls using the same connector instance.

feat: set the connector cloudID for Atlassian once its retrieved by GetPostAuthInfo

---

dynamicscrm/delete_test.go
dynamicscrm/metadata_test.go
dynamicscrm/read.go
dynamicscrm/read_test.go
dynamicscrm/write_test.go
test/utils/testroutines/connector.go
test/utils/testroutines/delete.go
test/utils/testroutines/metadata.go
test/utils/testroutines/outline.go
test/utils/testroutines/read.go
test/utils/testroutines/write.go

Changes are grouped by commits. The first two are the most important to understand the change. 
Commits named `add: Define <METHOD> testing, dynamicsCRM` are mirroring each other.
Introduces `testroutines` package that will remove repetitive, long test setup.
This defines common test structure for Read/Write/ListObjectMetadata/Delete.
The boilerplate is removed with generics and appropriate calls to connectors method.
The test needs to check output expectations, error expectations.
They must not differ. This code is copied over and over with no changes.
Declaring test suites:
``` go
tests := []testroutines.Write{
{
Name:  "Test name",
Input: common.WriteParams{},
ExpectedErrs: []error{common.ErrBadRequest}
}
}
```
Running test suite (within for loop):
``` go
testSuite.Run(t, func() …
```

add: Package testroutines

---

common/handy/cloning.go
providers/utils.go

Initially thought of using this function for another reason (https://github.com/amp-labs/connectors/pull/876) hence the move to handy utils. Thats not needed anymore but the move itself - still might be relevant.
Cloning potentially can be used outside of `providers` package.

tidy: Move Clone method into handy utils

---

atlassian/delete_test.go
atlassian/metadata_test.go
atlassian/read_test.go
atlassian/write_test.go
gong/metadata_test.go
gong/read_test.go
intercom/delete_test.go
intercom/metadata_test.go
intercom/read_test.go
intercom/write_test.go
pipeliner/delete_test.go
pipeliner/metadata_test.go
pipeliner/read_test.go
pipeliner/write_test.go
salesforce/metadata_test.go
salesforce/read_test.go
salesforce/write_test.go
salesloft/delete_test.go
salesloft/metadata_test.go
salesloft/read_test.go
salesloft/write_test.go
zendesksupport/delete_test.go
zendesksupport/metadata_test.go
zendesksupport/read_test.go
zendesksupport/write_test.go

@eberle1080 This is a follow up PR to https://github.com/amp-labs/connectors/pull/834
Every connector becomes shorter and consistent in testing Read/Write/ListObjectMetadata/Delete.
Commits are split by connector.
Every test does rename and then points to `tesroutine.<METHOD_NAME>` struct. Then test execution is just a matter of calling one method on this struct.

tidy: Mocktests to use Testroutines

---

providers/marketo.go

Wrong verb applied, 
invalid path.
Retrieve paginationToken first.
Using the paginationToken to retrieve data.
As observed above `moreResults` is `true` thus we have more data to retrieve.
All Success and Failed Operations will show a success in the console, Although some will be failures and some will be success. This is because Marketo returns a 200 OK status code for all events. The difference is the value of the `success` and `errors` keys in the responses.

feat: enable proxy marketo

---

salesloft/metadata/index.json
salesloft/metadata/queryParamStats.json
salesloft/metadata/schemas.json
salesloft/metadata_test.go
scripts/scrapper/intercom/metadata/main.go
scripts/scrapper/pipeliner/metadata/main.go
scripts/scrapper/salesloft/metadata/main.go
scripts/scrapper/zendesksupport/metadata/main.go
tools/scrapper/models.go

As of now index has links but not schema file.
Index is more intermidiate file used to acquire schema. I think it is important to have docs reference there as people could review `schemas.json` to know what ListObjectMetadata offers.
This PR passes docs URL links from index of object endpoints to static schema files that are used to serve ListObjectMetadata.
```go
// URL points to docs endpoint. Optional.
URL *string `json:"url,omitempty"`
```
Reran 4 scrapping scripts.
Intercom is the only that doesn't work due to UI changes.
The rest are not broken by the change either have Docs URL added or have some minor fields added/removed.

add: Docs URLs to static Metadata schemas

---

common/handy/pointers.go
common/jsonquery/nested.go
common/jsonquery/queries.go
common/jsonquery/queries_test.go
gong/read.go
gong/read_test.go

#Background
jsonquery package has utility methods for querying JSON fields.
The key is assumed to be non empty string.
There is no way to reference itself, the current node. All utils assume that you want to reach for nested fields. As it turns out it is not always the case.
Example: you have a json node holding `[{}, {}, {}]`. Calculating the size would require calling ajson node in similiar steps to what is already done by jsonquery - redundancy.
getInnerKey is a shared method among all query calls which resolves zoom path.
Special case of empty string is handled as tautology.
As a side effect (not my direct intent) these statements will act identically:
```go
jsonquery.New(node, "flags").Bool("enabled", false)
jsonquery.New(node, "flags", "enabled").Bool("", false)
```

feat: jsonquery: Empty key behaves as itself reference

---

common/interpreter/error.go

Right now connectors support at most JSON and/or XML parsing of provider error response.
This adds an option to handle `text/html`, should the deep connector interpret such data.

feat: interpreter: Allow HTML provider error parsing

---

common/apiKey.go
common/paramsbuilder/client.go
providers/utils.go

Deep connectors support 2 types of Clients during connector initialization: Oauth2 and Basic password.
* paramsbuilder exposes Clients supporting API key authentication
* via Header
* via Query param
* ProviderInfo has 2 new methods fullfiling required arguments of paramsbuilder
* GetApiKeyQueryParamName - programatically figure out what is query param name by looking up the catalog
* GetApiKeyHeader - from catalog get header name, header value prefix

feat: paramsbuilder: API Key client

---

smartlead/metadata.go
smartlead/metadata/schemas.json
smartlead/metadata/scraping.go
smartlead/metadata_test.go
test/smartlead/metadata/main.go

Closes #911
Static schema file is served as Object Metadata.
The file is created using documentation. For campaigns the docs had less fields than what endpoint returns, so it was manually added.
Verified campaings, client endpoints.

feat: Add Deep connector Smartlead (Metadata)

---

smartlead/metadata/schemas.json

Smartlead static schema file that serves Object Metadata now has Docs URL reference.

add: URL docs to Smartlead Object Metadata

---

scripts/catalog/json.go

`json.Marshal` internally escapes certain HTML characters like <, > or & in the json which messes up strings like `Productivity & Collaboration` in the labels (from our current catalog) - 
This PR disables that behavior so that the character can be preserved as is in the generated json catalog -

chore: Avoid escaping HTML characters in the JSON catalog 

---

providers/linkedIn.go

This was the very first proxy connector I added ([originally in the server](https://github.com/amp-labs/server/pull/511)) and have tested it many times already. I guess after we moved it out of the server into this repo, we never enabled it.

proxy: enable LinkedIn

---

common/error.go
common/http.go
marketo/client.go
marketo/connnector.go
marketo/errors.go
marketo/module.go
marketo/params.go
marketo/parse.go
marketo/read.go
marketo/url.go
test/marketo/connector.go
test/marketo/read/read.go
test/marketo/read/sample_response/channels.json

This adds Read capability for the Marketo deep connector. 
Note:
- Marketo API responds with 200 Ok, for most cases, even when having errors.  Created a mapping function for mapping native marketo error codes to http status codes. So then the server can determine what to do with the response.
-doc link: https://experienceleague.adobe.com/en/docs/marketo-developer/marketo/rest/error-codes 
Sample test when the response from Marketo is 200, But the custom error handler returns a 404.
Closes #908

feat: Add Read (Marketo deep connector)

---

marketo/README.md
marketo/connnector.go
marketo/types.go
marketo/url.go
marketo/write.go
test/marketo/connector.go
test/marketo/write/write.go

Currently we write to the Leads API.
Note: We currently don't handle record level errors(These are individual record errors). 
Test Response:
Closes #908

feat: Add write  Marketo connector

---

common/urlbuilder/url.go

Add capability to return query parameter from our custom URL. 
Note: URL primarily manages path and query params.

add: Get URL query param

---

common/handy/lists.go
common/handy/maps.go
test/marketo/metadata/metadata.go

Extends methods of Map data structure.
Lists data structure can return names of buckets they sit in.

add: Map and Lists utilities

---

gong/metadata/scrapping.go
intercom/metadata/scrapping.go
pipeliner/metadata/scrapping.go
salesloft/metadata/scrapping.go
smartlead/metadata/scraping.go
test/marketo/metadata/metadata.go
tools/fileconv/files.go
zendesksupport/metadata/scrapping.go

Scrapping writes, reads index.json and schema.json files.
These file are located neighbouring, sibling to the `FileManager` declaration.
This is refactoring.

tidy: Simplify locating schemas.json for scrapping

---

providers/mural.go

Remove TokenMetadatafields from the connector as it does not return scopes

Feat: Remove TokenMetadatafields Mural

---

providers/ironclad.go

We are unable to test Ironclad because it needs our app to be in production mode. We've submitted it for review, but they haven't responded yet. It's best to release this experimentally for the time being, because it's already been a month of waiting.

chore: Enable Ironclad proxy

---

providers/salesforceMarketing.go

After some testings, we faced some challenges regarding the refreshing token bit. Decided to use `client_credentials` as it's simpler and easier for customers to use.

update salesforceMarketing grant type

---

providers/salesforceMarketing.go

Closes #883 
Wrong verb applied, 
invalid path.
Requesting a paginated list of categories:
Querying the second page: Note that you have to use the `count` and `pageSize` to understand that your in the last page.

feat: enable SalesforceMarketing connector

---

providers/marketo/README.md
providers/marketo/parse.go
providers/marketo/url.go
providers/marketo/write.go
test/marketo/read/read.go

This updates the Marketo Read connector to support Since filtering with the following Objects:
- Emails
- Programs
- SmartCampaigns
- SmartLists
Removed the `SinceDateTime` since all the objects it supports are currently not supported using the Write Ampersand API.
The `sinceDateTime` supports  `lead activities` object which requires a client to send the `activityTypeIds`  as a query parameter during the request.
Example responses:
Reading `campaign` does not use Since, even if provided
Reading `channels` does not use Since, even if provided.
Reading `smartCampaigns` uses provided Since value.

feat: Update Read Marketo connector

---

common/parse.go
providers/atlassian/parse.go
providers/atlassian/read.go
providers/dynamicscrm/parse.go
providers/dynamicscrm/read.go
providers/gong/parse.go
providers/gong/read.go
providers/hubspot/parse.go
providers/hubspot/read.go
providers/hubspot/search.go
providers/intercom/parse.go
providers/intercom/read.go
providers/marketo/parse.go
providers/marketo/read.go
providers/outreach/parse.go
providers/outreach/read.go
providers/pipeliner/parse.go
providers/pipeliner/read.go
providers/salesforce/parse.go
providers/salesforce/read.go
providers/salesloft/parse.go
providers/salesloft/read.go
providers/smartlead/parse.go
providers/smartlead/read.go
providers/zendesksupport/parse.go
providers/zendesksupport/read.go

In general the implemenation of `getTotalSize` is directly connected to `getRecords`. Since we already have this array, why not get the length from it.
Sometimes, some connector do have `size` field in their response but thats not going to give any performence boost but only complicate the code.

tidy: Remove RecordsSize method

---

common/oauth.go
providers/utils.go

Passing in a custom HTTP client to the OAuth token refresher actually requires a context value to pull off. Without this, the default client gets used, which right now is resulting in HTTP throttle errors (since our rate-limited client is being ignored for these calls).

[ENG-1423] fix: Enable rate limiting for oauth token refresher

---

common/types.go
providers/salesforce/read.go

This adds a filter field to `ReadParams`, which is supported only for Salesforce. This should be removed in favour of a better filter concept later on.

[ENG-1511] chore: Add filter for salesforce

---

common/parse.go

Since we removed page size calculation by every connector. Some connectors may not know when there is no next page since they construct URL themselfes. 
To resolve infinite Read we should signify that no more records exists after the page returns no records. 
That is the most broad catch it all precaution.

feat: Stop Read pagination on empty page

---

common/handy/maps.go

Utility data structure that acts like a normal map but invokes a fallback method when there is "key" miss.
This map is useful to define a relationship between 2 sets where one could apply "fallback" method to derive one from another. 
Let's say provider API usually returns Objects under `data` field. However, there are a handful of exceptions. This default map will be the bridge between Object Name and JSON field holding that object.
```
var ObjectNameToResponseField = handy.NewDefaultMap(map[string]string{
"ticket_audits":               "audits",
"search":                        "results",
"satisfaction_reasons":  "reasons",
},
func(key string) string {
// Other response fields are named after Object.
return key
},
)
```
From above we can conclude the following: object Name …

feat(utils): Map data structure with default return

---

providers/instantly/client.go
providers/instantly/connector.go
providers/instantly/errors.go
providers/instantly/params.go
providers/instantly/parse.go
providers/instantly/read.go
providers/instantly/read_test.go
providers/instantly/test/invalid-path.json
providers/instantly/test/read-campaigns.json
providers/instantly/test/read-tags.json
test/instantly/connector.go
test/instantly/read/main.go

Closes #912 
There are few endpoints that perform listing. Those that do have varying endpoint paths.
Therefore, there is a hard coded mapping between object name (in plural) to the appropriate URL path.
Pagination is manually calculated as response is not a reliable source as it differes among endpoints.

feat: Add Deep connector Instantly (Read)

---

providers/instantly/metadata.go
providers/instantly/metadata/schemas.json
providers/instantly/metadata/scraping.go
providers/instantly/metadata_test.go
test/instantly/metadata/main.go
test/instantly/read/main.go
test/instantly/write-delete/main.go

Closes #912 
Metadata is taken from documentation and saved as static files under `schema.json`.

feat: Deep connector Instantly (Metadata)

---

providers/apollo/README.md
providers/apollo/write.go
test/apollo/write/write.go

With the current implementation, the connector can only write to the following objects:
- Accounts
- Opportunities
- Contacts
Creating an Opportunity
Updating the `amount` field of the created opportunity above.
The rest are Bulk activities or search requests.

feat: Add Apollo Write connector

---

common/scanning/credscanning/fields.go
scripts/oauth/token.go
scripts/proxy/proxy.go

Proxy, Token scripts to use the same credential readers as those under `test` repo.
This means that the same credential file can be used for either `Test`, `Proxy`, `Token` without altering any field names.
One such inconsitency was: **userName** vs **username**.
In future adding new fields will have all those destinations in sync.

tidy: Proxy, Token use consistent creds names

---

common/handy/set.go
providers/salesforce/bulk-info.go

We can get all job results in a single call instead of calling this endpoint for each job - https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/get_all_jobs.htm
When I asked for ~4 jobs that were spread out over ~38 pages, i.e. from page 200 to page 7800
the quota used up was 3 units. I am fairly certain that it's only 1 unit, and the other 2 units were from previous calls. This is because when I tested this function to get ALL jobs, only 1 unit was used up.
To pick out 7 jobs out of the dataset, it took the function ~15 seconds, going over 40 pages / 8000 records

[ENG-1536] chore: Add list job results endpoint

---

connectors.go
providers/salesforce/url.go

This introduces a new interface for looking up URLs. I need this in order to use the token introspection endpoint for Salesforce.

feat: Add UrlConnector interface, and implement it for Salesforce

---

common/types.go
providers/apollo/metadata.go
providers/gong/metadata.go
providers/gong/metadata/scrapping.go
providers/instantly/metadata.go
providers/instantly/metadata/scraping.go
providers/intercom/metadata.go
providers/intercom/metadata/scraping.go
providers/marketo/metadata.go
providers/marketo/metadata/file.go
providers/pipeliner/metadata.go
providers/pipeliner/metadata/scraping.go
providers/salesloft/metadata.go
providers/salesloft/metadata/scrapping.go
providers/smartlead/metadata.go
providers/smartlead/metadata/scraping.go
providers/zendesksupport/metadata.go
providers/zendesksupport/metadata/scrapping.go
tools/scrapper/files.go
tools/scrapper/models.go

Every call to ListObjectMetadata involves parsing file data into schemas before serving. To give substantial performence boost as it was discovered after using benchmarking, see discussion: https://github.com/amp-labs/connectors/pull/722#discussion_r1697443793
It is pretty safe to ignore marshal error as every connector must have mock tests for ListObjectMetadata using `schema.json` content.

feat: Explicit loading of Metadata Schema

---

providers/pipeliner/metadata/schemas.json
scripts/openapi/intercom/metadata/main.go
scripts/openapi/pipeliner/metadata/main.go
scripts/openapi/zendesksupport/metadata/main.go
tools/fileconv/api3/models.go
tools/fileconv/api3/parameters.go

Every OpenAPI script must log errors for every schema it failed to extract.
I ensured no errors are present. I went through every error and looked OpenAPI spec. All of them were safe to be added to ignored. Some objects, resources are duplicate of each other or not suitable for reading.
Added utility function `CamelCaseToSpaceSeparated`, also Zendesk has better formating of display names that is commited.
Utility function had object name and field name in weird order that confuses me so I flipped it. Object name comes first in the codebase.

tidy: Improve OpenAPI scripts, 3 connectors

---

providers/intercom/objectNames.go
providers/intercom/parse.go
providers/intercom/read.go
providers/intercom/read_test.go
providers/pipeliner/objectNames.go
providers/pipeliner/read.go
providers/pipeliner/read_test.go
providers/salesloft/objectNames.go
providers/salesloft/read.go
providers/salesloft/read_test.go
providers/smartlead/objectNames.go
providers/smartlead/read.go
providers/smartlead/read_test.go
providers/zendesksupport/objectNames.go
providers/zendesksupport/read.go
scripts/openapi/README.md
scripts/openapi/intercom/metadata/main.go
scripts/openapi/zendesksupport/metadata/main.go
tools/fileconv/api3/parameters.go

* Every connector that serves Metadata from `schema.json` has additional check during **Read** that prunes unsupported objects (not part of metadata)
* OpenAPI did some special mapping between `ObjectName` and `JsonPath` holding that object. This logically belongs to the connector and is moved as `DefaultMap` called `ObjectNameToResponseField`. 
`ObjectNameToResponseField` is used by `ZendeskSupport` and `Intercom`.
Because of the move it is not only beneficial for OpenAPI scripts to extract schemas but now it offers correct JSON resolution!
**Zendesk Support Read:**
This removes the gap between ListObjectMetadata and Read methods. It syncs both, making Read cover **no more** and **no less** than what ListObjetMetadata returns.

feat: Sync Read capability with OpenAPI

---

tools/fileconv/api3/README.md
tools/fileconv/api3/models.go
tools/fileconv/api3/parameters.go
tools/fileconv/api3/queries.go

Get operations may require non uniform parameters. Ex: managerId is required query parameter to list `coaches` for Gong.
As of now Read doesn't support parameterized listing, therefore such schemas should be dropped.
Optional callback can be provided to filter schemas based on OpenAPI operation parameters.
Callback provides the most flexability. Sometimes OpenAPI and online documentation can be misleading and say that query parameter is a must have, while in practice no error is returned.

feat(openapi): Select schemas based on Operation params

---

common/handy/timing.go
common/handy/timing_test.go
providers/gong/read.go
providers/gong/read_test.go
providers/salesforce/read.go

While working on Gong found that calls and users objects support Since parameter but it must be in RFC3339 time format in UTC only.
Gong - support incremental read.
Salesforce - SOQL relied on the same time format `2006-01-02T15:04:05Z`. It was modified next to Gong.
This takes into account time zone differences and makes time universal. Salesforce Read is affected. If time was already passed in UTC then no changes will be noticed. Otherwise records could be omitted or duplicated depending on location of servers (likely duplicated).

fix: Time formatting to respect Zone diff

---

.github/workflows/linter.yml
Makefile
scripts/oauth/token.go
test/gong/connector.go
test/hubspot/connector.go
test/intercom/connector.go
test/outreach/connector.go
test/outreach/read/read.go
test/salesloft/connector.go

I always run `make lint` but noticed that `make fix` may modify files that were not flagged by `make lint`. I tried clearing the cache using `golangci-lint cache clean`, but the issue persisted.
After researching more about `gci`, which is used for formatting, I found the command `gci list .` which performs a "dry run" by returning a list of files that need to be modified.
Now, `make lint` will also print the files that should be changed by running `make fix`. If no files require changes, the exit code will be 0. This preserves the existing behavior while adding an extra check to notify when `make fix` needs running.
There are 2 commits. One is the result of running `make fix`, the other adds additional check under Makefile and Github action. I used this PR to test github action, such …

chore: Linter includes formatting check

---

providers/gong/read_test.go
test/apollo/read/read.go
test/apollo/search/search.go
test/gong/metadata/main.go
test/instantly/read/main.go
test/instantly/write-delete/main.go
test/salesforce/bulk/read/main.go
test/utils/testroutines/README.md
test/utils/testroutines/connector.go
test/utils/testroutines/delete.go
test/utils/testroutines/metadata.go
test/utils/testroutines/outline.go
test/utils/testroutines/read.go
test/utils/testroutines/write.go

Discovered that test cases for Read/Write/Delete/ListObjectMetadata can be further improved with generics making the code shorter.
Another advantage is custom `TestCase` can be declared by any connector. This allows to reuse the same testing checks (expected errors, output matching) and turns the problem into type declaration instead of rewriting boiler plate.
Included `README` file for those who are planning on using this package with examples.

tidy: testroutines improvement with generics

---

providers/salesforce/bulk-delete.go
providers/salesforce/bulk-delete_test.go
providers/salesforce/bulk-write_test.go
providers/salesforce/bulk.go
providers/salesforce/test/bulk/delete/launch-job-opportunity.json
providers/salesforce/test/bulk/delete/update-job-opportunity.json

Using real requests recorded Provider API output to create mock tests.
`BulkDelete` is very similiar to `BulkWrite` therefore created common `mock server` which is reused by both **TestSuites**.
Added validation to BulkDelete argument params. Also removed a comment that ExternalIdField is required (that is only true for **upserts**).

test: Salesforce Bulk Delete

---

.semgrepignore

Adding new OpenAPI files breaks `semgrep`.
These files can be treated as opaque content as they are downloaded from connector documentation or its dashboard.
Common complaint is about basic authentication being weak:

chore(semgrep): Ignore connector OpenAPI files

---

common/error.go
providers/salesforce/connector.go
providers/salesforce/errors.go

There is `ErrorPostProcessor` that is used by JSON and XML HTTP Clients. Error handling method is called by those clients before return statement. Some connectors could choose to provide final callback to handle error in some way.
Salesforce is the only connector that has custom handling of error coming from Oauth2 library when refresh token is not valid.
This logic is not specific to Salesforce and should be applied universally across all connectors. 
`ErrorPostProcessor` will now own this logic which will trickle down the effects to others.

feat: Universal Oauth2 error handling

---

common/oauth.go

To satisfy the `http.RoundTripper` contract, the http request is cloned before being modified. Unfortunately this is discarding the context, which means that certain context values won't carry over to the actual http transport.
This is important for us because our rate limiter relies on these context values, and can't receive them. This will copy over the context, thus making these values available.

fix: when cloning http.Requests, also clone the context

---

providers/gong/errors.go
providers/gong/objectNames.go
providers/gong/test/write-call.json
providers/gong/test/write-invalid-request.json
providers/gong/write.go
providers/gong/write_test.go
test/gong/write/main.go

Only one object **"calls"** is eligible for deep connector.
Allows to create calls.
Calls are not created immidietly, it takes arround a whole day for Gong to process them. Therefore manual tests doesn't do usual Read to check for side effects.

feat: Add Deep Connector Gong (Write)

---

providers/gong.go

This should count as success. Here are more details for this operation.
As you can see it says "no calls found". I can replicate this using PROXY.
The message is **identical**. If we modify `Since` parameter to be Jan 2024, since then we have one call:
It takes time the whole day for the call to appear after its creation. Querying should happen using "old" date instead of "now".
Create call.
https://github.com/amp-labs/testdata/pull/16

feat: Enable read+write: Gong

---

providers/intercom/params.go
providers/intercom/read.go
test/attio/write/main.go
test/gong/write/main.go
test/intercom/search/main.go

Read for Intercom is changed such that:
* When object is `conversations` and we use incremental read then use POST, where search query relying on `updated_at` with page token will be used. Page size is increased to 150 as per documentation. This [link](https://developers.intercom.com/docs/references/rest-api/api.intercom.io/conversations/searchconversations) is also added as a comment.
* All other objects (and non-incremental conversations) will work as before using List via GET.
Query example:
Via Ampersand proxy:
```
curl --location --request POST 'https://proxy.withampersand.com/conversations/search' \
--header 'x-amp-installation-id: 16d68884-e6ed-4d61-b0a1-d8be82c0f679' \
--header …
```

feat: Intercom Read conversations via Search

---

scripts/oauth/token.go
test/utils/mockutils/mockcond/body.go
test/utils/mockutils/mockcond/conditions.go
test/utils/mockutils/mockserver/conditional.go
test/utils/mockutils/mockserver/handlers.go

This is part of PR series dedicated to simplifying expressing the goal of mock server used by test case.
Often times when designing a test scenario you want to express if part of request matches certain criteria (condition) and when it does it should act one way otherwise fallback, following `if...else` paradigm.
* `mockserver.Reactive{...}.Server()` describes what mock server should do when condition evaluates to true
* `mockond.Condition` is an interface which allows to express nested rules very easily:
* `Check func(w http.ResponseWriter, r *http.Request) bool` -- basic building block of conditions. Future PRs introduce such things as: if URL matches then, if REST operation is POST then, if has query paremeter then, etc.
* `Or []Condition` and `And []Condition` allow nesting and …

feat(utils): Conditional mock server

---

providers/salesforce/bulk-query_test.go
providers/salesforce/bulk-read_test.go

Used new version of mockutilities: mockserver.Reactive.
The intermitent error that occured with the salesforce test was only for BulkRead not BulkQuery.
This happened because internally the SOQL which deep connector sends to the server sometimes had fields in different order: `SELECT Id,Name FROM Account` vs `SELECT Name,Id FROM Account"}`. Real server has no issues with it, so to reflec this the mock server will respond with success in either `or` case.

fix(test): Salesforce Bulk read, disordered SOQL

---

common/module.go
common/paramsbuilder/module.go
common/paramsbuilder/params.go
providers/atlassian/connector.go
providers/atlassian/modules.go
providers/atlassian/params.go
providers/hubspot/connector.go
providers/hubspot/modules.go
providers/hubspot/params.go
providers/hubspot/string.go
providers/hubspot/url.go
providers/marketo/connector.go
providers/marketo/module.go
providers/marketo/params.go
providers/marketo/url.go

Relying on the Module URL path as identifiter for that module seems limiting.
* Module.Name is renamed to Module.Path
* Module has new field: ID which is of `APIModuleID` type.
The developer of a deep connector defines the 'slugs' that the connector supports. These IDs can then be associated with a URL path. However, for some connectors, the endpoints of a module may not share identical URL prefixes, requiring custom mapping and code to resolve the URLs. This is why defining a Module ID adds more abstraction and flexibility for cases like this.

feat: Define ModuleID

---

providers/salesforce/bulk-write_test.go
test/utils/mockutils/mockcond/request.go
test/utils/mockutils/mockserver/conditional.go
test/utils/mockutils/mockserver/crossroads.go

There are tests that require mock server to return values multiple times based on different conditions and producing respective responses. This is a more complicated case of `mockserver.Conditional`, where more than one outcome is possible.
Inroduced `mockserver.Switch` which includes a list of case, which are condition to response pairs. 
Conditional mock server is an `if` server while Switch is just like go switch.
Bulk write has mock server which is called 3 times. Each case has its own "reason" and response:
I think the former version is much more confusing where `RespondToBody` is nested under `RespondToMethod` which itself is nested under the `switch case`. The structure is very cumbersome. And adding one more check would increase nesting even more.

feat(utils): Switch mock server

---

.github/workflows/linter.yml

Seems that the main issue with recent failures of `golangci-lint` have to do with this line:
```
Before:
go-version: ">=1.21.0"
After:
go-version: "1.21.0"
```

fix: golinter compatability with golang version

---

.github/workflows/linter.yml
providers/apollo/parse.go
providers/dynamicscrm/connector.go
providers/instantly/connector.go
providers/intercom/connector.go
providers/marketo/url.go
providers/outreach/read.go
providers/pipeliner/connector.go
providers/salesforce/bulk-info.go
providers/salesforce/connector.go
providers/salesloft/connector.go
providers/smartlead/connector.go
providers/zendesksupport/connector.go
tools/scrapper/utils.go

`golangci-lint-action` upgraded from `v1.54` to `v1.56.2`.
That also means that some lines of code need to abide by new rules, hence the changes.

chore: Bump golangci version

---

common/http.go
providers/salesforce/connector.go
providers/salesforce/events.go
test/salesforce/event-flow/main.go
test/utils/creds.go

The methods were not in use for a while, and during that time url building logics changed without testing these endpoints. This PR fixes those. Also, PlatformEvents will not be supported, so removed the testing code rather than debugging to fix it. 
```
jaehyunlim@Jaehyuns-MBP connectors % go run ./test/salesforce/event-flow
-----------------Testing Named Credential Legacy-----------------
time=2024-10-16T13:26:51.109-07:00 level=INFO msg="Named credential created" body="&{FullName:TestNamedCredentialLegacy1729110410507 Metadata:0x140002daea0 Id:0XAPa00000009GDOAY}"
-----------------Testing Change Data Capture-----------------
time=2024-10-16T13:26:51.307-07:00 level=INFO msg="Data Event channel created" body="&{Id:0YLPa00000000fxOAA FullName:TestCDCChannel1729110410507__chn …
```

Fix Salesforce subscription related methods

---

providers/intercom/connector.go
providers/intercom/metadata/schemas.json
providers/intercom/objectNames.go
providers/intercom/params.go
providers/intercom/read.go
providers/intercom/read_test.go
providers/intercom/search.go
providers/intercom/test/read-search-conversations-request.json
providers/intercom/test/read-search-conversations.json
scripts/openapi/intercom/metadata/main.go
test/intercom/search/main.go

* First of all static schema for conversation originally had the right fields then they were replaced with `newsfeed` object. It seems this issue was not noticed as it affects "selectable fields" for Read. The right conversation schema is selected from OpenAPI (coming from POST search conversations)
* Some objects were not properly handled. A better distinction of `Ampersand Object Name` and matching URL path is introduced for exceptions.
* Tickets was added as a supported object. It can be queried via POST only. For `builders` this means they must pass Since parameter. This is added into [documentation](https://github.com/amp-labs/docs/pull/78).
* Conversations, Contacts, Tickets fallback to search endpoint when Since parameter is provided.
* Activity Logs is now an only GET endpoint …

feat: Intercom Read via search

---

common/paramsbuilder/authclient.go
common/paramsbuilder/client.go
providers/apollo/params.go
providers/instantly/params.go
providers/smartlead/params.go

1. paramsbuilder.Client is split, where AuthClient is embeded in Client. This shrinks client.go file focusing on picking `Auth Type`, while authclient.go has validation, basic definitions.
2. Most important: `WithApiKeyQueryParamClient` and `WithApiKeyHeaderClient` rely on provider.Provider to imply the name of header and the name of query parameters using **Catalog**.

feat: Infer params for API Key auth from catalog

---

common/parse.go
common/scanning/credscanning/path.go
providers/customerapp/client.go
providers/customerapp/connector.go
providers/customerapp/errors.go
providers/customerapp/metadata/schemas.json
providers/customerapp/metadata/scraping.go
providers/customerapp/objectNames.go
providers/customerapp/params.go
providers/customerapp/parse.go
providers/customerapp/read.go
providers/customerapp/read_test.go
providers/customerapp/test/read-exports-empty.json
providers/customerapp/test/read-newsletters-1-first-page.json
providers/customerapp/test/read-newsletters-2-empty-page.json
test/customerio/journeysapp/connector.go
test/customerio/journeysapp/read/main.go

This is a read implementation for `Customer Journeys App` connector.
For simplicity the code that extracts metadata schema is kept seperate (will be part of ListObjectMetadata).
The schema.json file is commited and used for read. This is a complete list of supported objects for reading.
The tests includes sample empty response for exports and newletters (I went over all objects and there seems to be 2 common patterns for empty response, `null` and `[]` lists).
Next page URL is built using "next" response field with correct URL encoding. The page size various and a minimum of 50 entries has been chosen.

feat: CustomerJourneysApp (Read)

---

providers/customerapp/metadata.go
providers/customerapp/metadata_test.go
providers/customerapp/openapi/file.go
scripts/openapi/customerio/journeysapp/metadata/main.go
test/customerio/journeysapp/metadata/main.go

Customer Journeys App implements `ListObjectMetadata` by serving static `schema.json`.
OpenAPI extraction script is created for this connector and OpenAPI file is attached (119,158 lines).

feat: CustomerJourneysApp (Metadata)

---

providers/kit.go

Kit Provider = "kit"
URL: https://proxy.withampersand.com/v4/custom_fields
URL: https://proxy.withampersand.com/v4/custom_fields
URL: https://proxy.withampersand.com/v4/custom_fields/728151
URL: https://proxy.withampersand.com/v4/custom_fields/728151
Requesting a paginated list of custom fields using the **per_page** parameter to set the record limit and the **include_total_count** parameter to return the total record count
URL: https://proxy.withampersand.com/v4/custom_fields?include_total_count=true&per_page=5
Request the next paginated list of custom fields by using the token from the **end_cursor** field in the response and passing it in the **after** parameter
URL: …

feat: Enable proxy: Kit

---

providers/zohocrm/write.go
test/zohocrm/read/read.go
test/zohocrm/write/write.go

This Adds the ZohoCRM write conector. 
Writing to zoho supports upto 100 records per API Call. So the the RecordData should be a slice of maps.
Supports Updating 1 record per API Call. 
They have an API for updating several records as well.(We currently do not support this)
We do not return the recordId as one may create several records per call.
Tests:
On the last call, The request was a success but there are some records that failed to insert.

feat: Add ZohoCRM Write Connector

---

common/oauth.go

Right now the token source has no way to get hints from the caller. Specifically, the kinds of hints I'm talking about are things like "I got a 401 and I need to forcefully refresh". This kind of info can be encoded in to a `context.Context` but as is, the `oauth2.TokenSource` interface doesn't accept a context.
This extends the interface so that the caller may implement this new signature, and get called with the context. This will let me do the 401 "force refresh" logic I need. If the caller doesn't implement this interface, it's fine, it will just fall back to the normal one.

feat: add the TokenSourceContext interface

---

providers/closecrm/connector.go
providers/closecrm/metadata.go
providers/closecrm/parse.go
providers/closecrm/read.go
providers/closecrm/search.go
providers/closecrm/types.go
test/closecrm/connector.go
test/closecrm/metadata/metadata.go
test/closecrm/read/read.go

Adds the CloseCRM Read Connector. The Close API offers the Listing and Searching APIs.
The searching API supports incremental Read by Adding Filtering Queries in the request body. I have added the switching route to search if the Since Field is provided. 
The search API has a limitation of reading up to 10K with pagination.
The Cursor for pagination expires in 30 seconds.
Test Outputs:

feat: Add CloseCRM Read connector

---

common/module.go
internal/staticschema/core.go
providers/zendesksupport/connector.go
providers/zendesksupport/delete_test.go
providers/zendesksupport/metadata/schemas.json
providers/zendesksupport/metadata_test.go
providers/zendesksupport/modules.go
providers/zendesksupport/objectNames.go
providers/zendesksupport/openapi/file.go
providers/zendesksupport/openapi/help-center-api.yaml
providers/zendesksupport/params.go
providers/zendesksupport/read.go
providers/zendesksupport/read_test.go
providers/zendesksupport/write_test.go
scripts/openapi/zendesksupport/metadata/helpcenter/objects.go
scripts/openapi/zendesksupport/metadata/main.go
scripts/openapi/zendesksupport/metadata/support/objects.go
test/zendesksupport/connector.go

Zendesk Support consists of 3 modules:
* [Ticketing API](https://developer.zendesk.com/api-reference/ticketing/introduction/)
* [Help Center API](https://developer.zendesk.com/api-reference/help_center/help-center-api/introduction/)
* [Voice API](https://developer.zendesk.com/api-reference/voice/talk-api/introduction/)
This PR introduces Help Center module by adding OpenAPI yaml. The script is modified in such way that `schema.json` instead of having default empty name module, it is renamed to ticketing while a newly added module is called help center.
No changes are `required`.
To be more explicit when constructin connector we could add `WithModule` option.
While it is possible to merge the two API modules since each has universally unique objects without collission, I decided to keep …

feat: Zendesk add Help Center module

---

providers/zendesk.go
providers/zendesksupport/connector.go
providers/zendesksupport/delete_test.go
providers/zendesksupport/metadata_test.go
providers/zendesksupport/parse.go
providers/zendesksupport/read_test.go
providers/zendesksupport/test/read-posts.json
providers/zendesksupport/test/write-post.json
providers/zendesksupport/write_test.go
test/zendesksupport/metadata/main.go

As of now the only supported resources have short URLs. There is no systematic approach for other cases.
* The static schema file holds URL paths for every object, allowing nested REST API resources to be requested via Read/Write/Delete methods.
Some connectors have few endpoints with hardcoded mapping between ObjectName and URL. However, in this case `schema.json` was generated from the OpenAPI file, so it naturally holds the mapping. As a result, creating URLs is straightforward.
```go
path, err := metadata.Schemas.LookupURLPath(c.ModuleID, objectName)
url, err := urlbuilder.New(c.BaseURL, path)
```
* I noticed that pagination response format differs between ticketing and help center modules. I updated the parsing so that both pagination formats are handled in a fallback sequence, …

feat: Zendesk modules use URLs from schema.json

---

tools/fileconv/api2/README.md
tools/fileconv/api2/manager.go
tools/fileconv/api3/README.md
tools/fileconv/api3/manager.go
tools/fileconv/api3/queries.go

We have `api3` package as a tool to extract object schema for ListObjectMetadata and Read methods using OpenAPI V3 files.
This PR adds a simple way of supporting OpenAPI V2 by introducing package `api2` which first parses the file and converts from V2 to V3 producing `api3.Explorer`. Therefore, it acts as a wrapper utilizing the same processing logic as `api3.Explorer`.
The convertor is part of the library that I already use for dealing with OpenAPI.
Reference: https://github.com/getkin/kin-openapi
Under provider package we create `openapi` repository holding json or yaml file with golang "wiring".
If we want to treat it as version 2, simply change the pacakge:
Everything else remains unchanged.

feat: Support OpenAPI V2

---

scripts/openapi/gong/metadata/main.go
scripts/openapi/pipedrive/metadata/main.go
scripts/openapi/pipeliner/metadata/main.go
tools/fileconv/api3/README.md
tools/fileconv/api3/models.go
tools/fileconv/api3/parameters.go
tools/fileconv/api3/queries.go

OpenAPI tool using response object schema, locates the field that holds an array and uses that schema to describe object that we return during Read/ListObjectMetadata.
* Response schema might already be a an array, so there is no need for this extra "locate" step. We need to extract fields from current `array-item schema`.
* `ObjectCheck` was renamed to `ObjectArrayLocator`. Array holder would use this callback to find field name, ex (product schema is located under products response field): 
```json
{
"field1":[{}, {}, {}],
"field2":{...},
"products":[],
"field3":{},
}
```
A direct return of `[ {product1},  {product2},  {product3}, ]` doesn't need `ObjectArrayLocator`.
Array of objects is either returned directly or part of top level object under some field name resolved by …

feat: OpenAPI extract schema from Object or Array

---

internal/staticschema/core.go
providers/customerapp/metadata/schemas.json
providers/gong/metadata/schemas.json
providers/intercom/metadata/schemas.json
providers/marketo/metadata/schemas.json
providers/pipedrive/metadata/schemas.json
providers/pipeliner/metadata/schemas.json
providers/salesloft/metadata/index.json
providers/salesloft/metadata/schemas.json
providers/zendesksupport/metadata/schemas.json
scripts/openapi/customerio/journeysapp/metadata/main.go
scripts/openapi/gong/metadata/main.go
scripts/openapi/intercom/metadata/main.go
scripts/openapi/pipedrive/metadata/main.go
scripts/openapi/pipeliner/metadata/main.go
scripts/openapi/zendesksupport/metadata/main.go
scripts/scrapper/salesloft/metadata/main.go
tools/fileconv/api3/models.go

Added `locatedAt` field in schema.json.
This is present for those providers relying on OpenAPI or scrapping.
schema.json:
LocatedAt indicates under which field name the array of object is located.
From schema.json it is easier to tell, what is the URL path, where the object is found from provider response and what fields it will returns. It captures all required information to see how Ampersand metadata is mapped to provider APIs.

tidy: Store JSON array path in schema.json

---

providers/pipedrive.go

Providing scopes in the Authorization call is not a mandatory requirement. There is a step in the App creation in which you should select the scopes that will be used for the Application, And they can not be altered by the scopes provided in the Authorization call.
ref: https://devcommunity.pipedrive.com/t/can-i-specify-scopes-when-authorizing-oauth/3244/2

fix: pipedrive scope requirement

---

common/http.go
providers/hubspot/errors.go
providers/hubspot/record.go
providers/hubspot/url.go
providers/hubspot/webhook.go
providers/hubspot/write.go
test/hubspot/record/main.go
test/zohocrm/read/read.go

This PR implements a Connector method for HubSpot that transforms webhook messages to `WebhookResult` which will contain original record data. In order to achieve that, this PR introduces `GetRecord(...)` method that takes `recordId` and `objectName` as arguments and returns `ReadResultRow` which will have raw data. 
```
jaehyunlim@Jaehyuns-MacBook-Pro connectors % go run test/hubspot/record/main.go  
time=2024-11-04T16:29:05.992-08:00 level=DEBUG msg="loading credentials file" path=./hubspot-creds.json
{
"webhookMessage": {
"appId": 4210286,
"eventId": 100,
"subscriptionId": 2902227,
"portalId": 44237313,
"occurredAt": 1730750483646,
"subscriptionType": "contact.propertyChange",
"attemptNumber": 0,
"objectId": 75032904814,
"changeSource": "CRM",
"propertyName": "message", …
```

[ENG-1652] Introduce a method to transform the webhook payload into a ReadResultRow

---

providers/close.go

This updates the close configurations. We need to explicitly provide scopes.
Ref:  https://developer.close.com/topics/authentication-oauth2/#refresh-access-token
The slab indicates this as well.

fix: Close scope requirement

---

common/jsonquery/defaults.go
internal/staticschema/core.go

Identifiers in provider responses may be of either string or integer types. This adds a utility that surfaces that value as string.
The strict attitude of what JSON data type we expect is not relevant. Instead with a new method we are asking give me data as "Text" regardless of what it is.

feat(jsonquery): Soft string requirement

---

common/module.go
providers/keap/client.go
providers/keap/connector.go
providers/keap/errors.go
providers/keap/metadata/schemas.json
providers/keap/metadata/scraping.go
providers/keap/modules.go
providers/keap/objectNames.go
providers/keap/params.go
providers/keap/parse.go
providers/keap/read.go
providers/keap/read_test.go
providers/keap/test/get-with-req-body-not-allowed.html
providers/keap/test/read-contacts-1-first-page-v1.json
providers/keap/test/read-contacts-2-empty-page-v1.json
providers/keap/test/read-tags-v2.json
providers/keap/test/url-not-found.html
test/keap/connector.go
test/keap/read/main.go

Some error response from provider are either in JSON or HTML format. 
`schema.json` produced from OpenAPI is added illustrating the support for read objects.
Depending on the Module the Read is affected such that `limit` == `page_size` query parameter. Next page is located under either "next" or "next_page_token".
Since parameter is available for V1 only.
Listing emails:

feat: Keap (Read)

---

providers/utils.go
scripts/oauth/token.go
scripts/proxy/proxy.go

Modified `token` script to generate authentication token using AuthCode grant type with PKCE. 
I am able to generate auth token for Klaviyo. Additionally checked ConstantContact which for backwards compatability, and the script works as expected.
For `proxy` the script was modified to allow requests through without the proper refresh strategy. For local testing I just recreate access token manually. For deep Klaviyo connector implementation  it is sufficient.

feat(scripts): PKCE for AuthCode grant type

---

tools/fileconv/api3/models.go
tools/fileconv/api3/parameters.go
tools/fileconv/api3/queries.go

Klaviyo is the first connector that uses `"application/vnd.api+json"` as response MIME type.
This PR adds configuration to specify your own MIME. By default we are looking for `"application/json"`

feat(openapi): Configure custom media type

---

tools/fileconv/api3/models.go
tools/fileconv/api3/parameters.go
tools/fileconv/api3/queries.go

Klaviyo consistently returns objects with the following fields:
```json
{
"type": "account",
"id": "W4D9sr",
"attributes": {},
"links": {}
}
```
This PR adds an option to move fields located under certain nested key (in our case "attributes") to the top level. For the accounts object we will get:
```json
{
"type": "account",
"id": "W4D9sr",
"test_account": false,
"contact_information": {},
"industry": null,
"timezone": "US/Eastern",
"preferred_currency": "USD",
"public_api_key": "W4D9sr",
"locale": "en-US",
"links": {}
}
```

feat(openapi): Option for Fields flattening

---

common/interpreter/error.go
common/interpreter/error_test.go
common/types.go
providers/klaviyo/client.go
providers/klaviyo/connector.go
providers/klaviyo/errors.go
providers/klaviyo/metadata/metadata.go
providers/klaviyo/metadata/schemas.json
providers/klaviyo/modules.go
providers/klaviyo/objectNames.go
providers/klaviyo/params.go
providers/klaviyo/parse.go
providers/klaviyo/read.go
providers/klaviyo/read_test.go
providers/klaviyo/test/read-campaigns.json
providers/klaviyo/test/read-profiles-1-first-page.json
providers/klaviyo/test/read-unsupported-pagination.json
test/klaviyo/connector.go
test/klaviyo/read/main.go
test/utils/mockutils/mockserver/handlers.go

* Since - incremental read uses unique to that object field name. Providing missing field in query will produce the error, thats why on package startup I go over each object known by Read/Metadata and select desired field for Since. 
Note: If no such field exists then nothing it is a no-op.
* Filter - Klaviyo requires filter query parameter for some objects to perform read. This means Salesforce would be not the only one to utilize `common.ReadParams.Filter`. 
Both Since and Filter arguments will be combined and properly passed via `filter` query parameter. They are allowed to be comma separated as per documentation. This falls under custom mime type: "application/vnd.api+json".
Another PR focuses on processing OpenAPI and produces schema.json which we rely uppon.
Every API request …

feat: Klaviyo (Read)

---

common/types.go
providers/hubspot/webhook.go
providers/hubspot/webhook_test.go

Added webhook types including create,delete,update, pathThrough
added hubspot webhook type parsing and unit test.

[ENG-1637] Parse webhook types from message for hubspot

---

providers/constantcontact/client.go
providers/constantcontact/connector.go
providers/constantcontact/errors.go
providers/constantcontact/metadata/schemas.json
providers/constantcontact/metadata/scraping.go
providers/constantcontact/objectNames.go
providers/constantcontact/params.go
providers/constantcontact/parse.go
providers/constantcontact/read.go
providers/constantcontact/read_test.go
providers/constantcontact/test/read-contact-ids-error.json
providers/constantcontact/test/read-contacts-1-first-page.json
providers/constantcontact/test/read-contacts-2-second-page.json
test/constantcontact/connector.go
test/constantcontact/read/main.go

Mock tests demonstrate the reading of contacts, pagination using an optional href, and handling of erroneous responses represented as an array.
schema.json is created using OpenAPI file. This file will be added in different PR focusing on ListObjectMetadata.

feat: ConstantContact (Read)

---

providers/customerapp/connector.go
providers/customerapp/delete.go
providers/customerapp/delete_test.go
providers/customerapp/errors.go
providers/customerapp/objectNames.go
providers/customerapp/read.go
providers/customerapp/test/README.md
providers/customerapp/test/delete-not-found.json
providers/customerapp/test/write-segment-bad-request.json
providers/customerapp/test/write-segment.json
providers/customerapp/write.go
providers/customerapp/write_test.go
scripts/openapi/customerio/journeysapp/metadata/main.go
test/customerio/journeysapp/write-delete/main.go

There is a difference in support among objects between Create/Update/Delete. 
2 objects are made up mapping to URL path:
`customer_exports`  refers to "/exports/customers";
`deliveries_exports` refers to "/exports/deliveries".
Response key holding record of interest differes among objects and such exceptions are also recorded, for more refer to `objectNames.go`.

feat: CustomerJourneysApp (Write)

---

providers/google.go

Google OAuth2 seems to have some <sub><sup>ridiculous</sup></sub> undocumented behavior.
If a user grants access to a Google app via the standard OAuth flow, setting the `access_type` set to `offline`, we receive a set of access and refresh tokens. However, during subsequent OAuth flows for the same Google app, the oauth flow will automatically bypass the allow/consent screen. This is google's way of speeding up the flow since it knows that you already consent to the app. 
The catch is that Google seems to ignore requests for refresh tokens during the second type of oauth flows, i.e. when it skips past the consent screen for you.
To fix this, we need to force Google to always display the consent screen and therefore, make it always honor the request for a refresh token. This issue is easy …

[ENG-1268] fix: Update google auth params

---

common/interpreter/statusCode.go
common/types.go
providers/gong/read.go
test/gong/read/read.go

Core code mapping to error messages is modified such that 404 is distinguished from other 4xx.
Gong read has a check returning empty ReadResult on error not found.
Modified Read script to do the most recent incremental read. Using debug tools verified that the correct code branch is visited:
This PR focuses on Gong only as per ticket.
I left the TODO on better error handling a while ago, it seems this could be a good time to think what errors are expected to be returned by connectors library. Also, treating not-found error as success may only apply to Gong but not other connectors. 
@laurenzlong let me know in slack if there are any plans on universal error format by Ampersand connectors and what is the priority for this.

[CON-2] Gong returns empty ReadResult on not-found

---

internal/datautils/maps.go
providers/hubspot/write.go

Previously Hubspot write was only returning the `properties` of the record, whereas it should return the full record (which includes associations). 
This is technically a breaking change, but I checked the logs and there aren't any write API calls for Hubspot in the last 14 days, so doesn't appear like this is being actively used.

Feat: Hubspot write method now returns full record

---

providers/hubspot/parse.go
providers/hubspot/parse_test.go
providers/hubspot/types.go

* We added the `Raw` field to `ReadResult` after this function was originally introduced. At the time, it looked for ID inside the fields object
*  This function needs to look for the ID of a record in the `Raw` object, and not the `Fields` object, since `Fields` may or may not have the ID field
* The `Raw` response will always have the ID inside `Raw.properties`
This test should help clarify the required output - https://github.com/amp-labs/connectors/pull/1186/files#diff-24f929d222aa9a04a0837d0f97a1b5c230629c1420ae254486acefc9b10f2a00R61

fix: Update hubspot.GetResultId to look for ID in the raw object

---

providers/atlassian/connector.go
providers/atlassian/modules.go
providers/utils.go

Atlassian connect has a different base URL than the usual atlassian API (read more @ https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/#authentication), but we need this to function in the same connector. This PR enables the atlassian connector to use a module which overrides the base URL and lets it makes calls to the Connect API. If we like this pattern, we can add it into modules

feat: Allow a module to override base URL

---

common/header.go
common/jwt.go
common/scanning/credscanning/fields.go
go.mod
go.sum
providers/atlassian/jwt.go
providers/atlassian/jwt_test.go
providers/types.gen.go
providers/utils.go
test/atlassian/connector.go
test/atlassian/jwt/main.go

- Adds a JWT client that can be used with Atlassian's Connect module 
- This client, for every request, generates a signed token based on the current time, the actual request and some fixed claim data (`iss` to be exact)
- **Note:** The current connector ONLY supports `issues` though, so this will also only support issues for now. 
I need to do more testing around writes, but reads work just like usual.

[ENG-1729] feat: Atlassian JWT client

---

providers/airtable.go

Wrong verb applied, invalid path.
A response having the `offset` indicates there is a next page.
Using the `offset` to access the next-page

[CON-25] feat: enable Airtable proxy

---

providers/constantcontact/metadata/schemas.json
providers/constantcontact/objectNames.go
providers/constantcontact/read_test.go
providers/constantcontact/test/read-contact-ids-error.json
scripts/openapi/constantcontact/metadata/main.go

Removed objects that either require extra query parameters or are part of `partner` APIs which need passing JWT token not only in auth header but custom header.

[CON-100] tidy: ConstantContact: Prune dubious objects

---

providers/constantcontact/metadata/schemas.json
providers/constantcontact/objectNames.go
providers/constantcontact/params.go
providers/constantcontact/parse.go
providers/constantcontact/read.go
providers/constantcontact/read_test.go
providers/constantcontact/test/read-contact-ids-error.json
scripts/openapi/constantcontact/metadata/main.go
test/constantcontact/read/main.go
test/utils/dump.go

* Enabled pagination (for some reason this was missing again...)
* Incremental Read by `email_campaigns` and `contacts`. Manually tried combination of Since/NextPage fields. Query parameters are applied correctly on first and consequent pages.
* DumpJSON confused me for being responsible for escaping URL `&` symbol. Modified helper funciton.

[CON-100] feat: ConstantContact: Pagination, Since

---

common/error.go
common/paramsbuilder/params.go
connector/connector.go
internal/goutils/utils.go
mock/connector.go
mock/params.go
providers/apollo/connector.go
providers/atlassian/connector.go
providers/attio/connector.go
providers/closecrm/connector.go
providers/constantcontact/connector.go
providers/customerapp/connector.go
providers/docusign/connector.go
providers/dynamicscrm/connector.go
providers/gong/connector.go
providers/hubspot/connector.go
providers/instantly/connector.go
providers/intercom/connector.go
providers/keap/connector.go
providers/klaviyo/connector.go
providers/marketo/connector.go
providers/outreach/connector.go
providers/pipedrive/connector.go
providers/pipeliner/connector.go
providers/salesforce/connector.go
providers/salesloft/connector.go
providers/smartlead/connector.go
providers/zendesksupport/connector.go
providers/zohocrm/connector.go

PanicRecover shouldn't be called from Connector constructor. Panics can be used within connector options. We have a more local place to call for panic recovery which is `paramsbuilder.Apply`. This should clean the code and hide this method.
Review them by commits.
* https://github.com/amp-labs/connectors/pull/1175/commits/3f23dafaf16bcbcee9afa890742684924a4bb68c 
* PanicRecovery is moved to `goutils`. It is not related to `common` package but provides a very general utility, it belongs to golang utility ("std library").
* parambsbuilder.Apply uses recovery. The gist of PR.
* https://github.com/amp-labs/connectors/pull/1175/commits/d045b8a692c5b4e6c749a5c87889341d80dc494e
*  removed panicrecovery from connectors because now it doesn't guard against anything.
* …

tidy: Scope panic recovery to Options constructor

---

common/parse.go
providers/attio/read_test.go
providers/customerapp/read_test.go
providers/dynamicscrm/read_test.go
providers/gong/read_test.go
providers/intercom/read_test.go
providers/keap/read_test.go
providers/kit/read_test.go
providers/pipeliner/read_test.go
providers/salesforce/read_test.go
providers/salesloft/read_test.go
providers/smartlead/read_test.go
providers/zendesksupport/read_test.go
test/kit/write/main.go

Due to the concern on returning nil rows and marshalling cares about `nil` vs `[]` to be safe resort to returning empty slice for all Read operations.
Previously some connectors would return null or [], for consistent expection it will be `[]`.

fix: Read empty rows, never nil

---

common/types.go
connectors.go
providers/hubspot/subscriptionEvent.go
providers/hubspot/types.go
providers/kit/read_test.go
test/kit/write/main.go

Webhooks from providers need to be verified. This PR creates types for the verification params, and defines method for Hubspot to verify webhook.

[ENG-1707] Hubspot connector method to verify webhook. 

---

providers/apollo/types.go
test/apollo/read/read.go

This adds
-  support for reading sequence (emailer_campaigns) object in apollo. It uses reading by search but does not have the 50K display limitations. So this can currently be supported.
- reading the tasks object, can now be supported by the Search method.
Testing reading the `emailer_campaigns`

feat: (apollo) update sequences object support

---

providers/closecrm/read.go
providers/closecrm/types.go
test/closecrm/read/read.go

The objects: Leads, Contacts & Opportunities are the only Objects supporting the Advanced Filtering Query. Doc [Link](https://developer.close.com/resources/advanced-filtering/).  These filtering queries can in turn be used for the incremental read support.
This PR adds a check to confirm objects support when `since` parameter is provided.

fix: (closeCRM) update objects supporting incremental read

---

common/jsonquery/converters.go
providers/keap/README.md
providers/keap/objectNames.go
providers/keap/parse.go
providers/keap/read.go
providers/keap/read_test.go
providers/keap/test/custom-fields-contacts.json
providers/keap/test/read-contacts-1-first-page-v1.json
scripts/openapi/keap/metadata/v1/objects.go
scripts/openapi/keap/metadata/v2/objects.go
test/keap/read/main.go

Include custom fields as part of `Read` response alongside the native fields.
[How to create/update/delete custom fields?](https://help.keap.com/help/create-custom-fields) This can be done via dashboard. I noticed that update and delete are absent in REST APIs, therefore managing custom fields via dashboard is preferred.
Check the `README.md` for how the read output is effected, as well as tests.

[CON-186] Keap - read with custom fields

---

.github/workflows/linter.yml
Makefile
internal/datautils/maps.go
internal/staticschema/convertors.go

Noticed that a test would fail under parallel execution: https://github.com/amp-labs/connectors/actions/runs/12360650495/job/34496076253?pr=1220#step:5:1728
Located an issue shared by connectors that create `*common.ListObjectMetadataResult` relying on shared static schema. A copy of the map is now used to construct object metadata.

fix: Return shallow copy of Metadata

---

providers/zohocrm/write.go
test/zohocrm/write/write.go

-  Zoho expects a list of objects that's are to be created/updated.  
- Ampersand API sends a map[string]any. A single object
This PR wraps the object into a slice and sends it. Checks if the received data is not a list.
Tests:
For more context: https://linear.app/ampersand/issue/CON-420/zoho-crm-deep-connector

[CON-423] feat: (zoho)update write input dynamically

---

internal/datautils/timing.go
providers/keap/read.go
providers/keap/read_test.go
test/keap/read/main.go

Using the date format provided in the documentation didn't work. Found out on Keap forum that timestmap must include milliseconds.
Added new time format as suggested by https://integration.keap.com/t/getting-invalid-date-format-while-creating-appointment/71578/3.
Modified a mock test to expect the time format in the query parameter and ran the script with desired output:
VS output prior to fix:

[CON-186] Keap: fix since time format

---

providers/keap/metadata/schemas.json
scripts/openapi/keap/metadata/v1/objects.go

I went over each and every Keap object and discovered only 2 couldn't be supported. 
Query parameters give required context to call those endpoints. As of now such Read objects are not supported.

[CON-186] Keap: remove objects - required QueryParams

---

providers/apollo/connector.go
providers/apollo/metadata.go
providers/apollo/parse.go
providers/apollo/read.go
providers/apollo/types.go
providers/apollo/write.go
test/apollo/metadata/metadata.go
test/apollo/read/read.go
test/apollo/write/write.go

Apollo sometimes uses different names in the URL vs in the description of the API documentation:
[Emailer Campaigns are called Sequences](https://docs.apollo.io/reference/search-for-sequences)
[Opportunities are called Deals](https://docs.apollo.io/reference/list-all-deals)
[Opportunity Stages are called Deal Stages](https://docs.apollo.io/reference/list-deal-stages)
[Lists and Tags and called Labels](https://docs.apollo.io/reference/get-a-list-of-all-liststags)
This Adds support for these product names.
Testing(Reading):
Writing:
Reading Metadata:

[CON-892] feat: (apollo) support API product names

---

tools/fileconv/api3/README.md
tools/fileconv/api3/models.go
tools/fileconv/api3/parameters.go
tools/fileconv/api3/queries.go

The response schema may include multiple array properties. To determine the correct one, a callback ObjectArrayLocator was always used. This effectively created a mapping between the object name and the desired array property.
Not all APIs adhere to consistent property naming conventions. While most inconsistencies can be addressed by modifying the object name, others must be hardcoded as a last resort. Creating such mappings is often tedious and, in many cases, impractical.
The OpenAPI explorer now includes an additional configuration option: `ArrayItemAutoSelection`.
If the response schema contains only one array property, it will be selected automatically. For ambiguous multi-array responses, however, the mapping via ObjectArrayLocator will still be required.

feat(openapi): Array schema autoselect

---

providers/ringCentral.go

RingCentral Provider = "ringCentral"
URL: https://proxy.withampersand.com/team-messaging/v1/teams
URL: https://proxy.withampersand.com/team-messaging/v1/teams
URL: https://proxy.withampersand.com/team-messaging/v1/teams/142731788294
URL: https://proxy.withampersand.com/team-messaging/v1/teams/142731788294
Requested a paginated list of teams using the **recordCount** parameter to set the record limit and it will return the **prevPageToken** field with the next page token value.
URL: https://proxy.withampersand.com/team-messaging/v1/teams?recordCount=5
**a)** Requested the next paginated list of teams by using the **prevPageToken** field value from the previous response and …

[CON-539] feat: Enable proxy: ringCentral

---

providers/smartlead/metadata/schemas.json
providers/smartlead/metadata_test.go

Reading leads requies email as a query parameter.
No place relies on leads object and this PR is to tidy this inconsistency. Its not mentioned up the stack and shouldn't be here either.

fix(Smartlead): Remove unsupported leads

---

providers/hubspot/metadata_test.go
providers/hubspot/test/metadata-contacts-properties-sampled.json
test/hubspot/auth-metadata/main.go
test/hubspot/metadata/main.go

1. Renamed `GetPostAuthInfo` test as `auth-metadata`.
2. Created `metadata` script that uses `ListObjectMetadata` for `contacts`.
(script requests each field provided by ListObjectMetadata when making Read, thats why URL is long)
3. Added provider response describing `contacts` object to the mock test. (API response will be used in more details in the next graphite PR regarding ValueType proposal).

tidy(Hubspot): Bootstrap ListObjectMetadata tests

---

common/types.go
common/valueType.go
providers/hubspot/metadata.go
providers/hubspot/metadata_test.go
test/utils/mockutils/metadataResult.go

1. Defined `FieldMetadataMap` on `ObjectMetadata`.
2. Marked `FieldsMap` as deprecated (will be reflected in IDE). `ObjectMetadata` constructor will populate this field automatically as a derivative of `FieldMetadataMap`.
3. Hubspot has a method that transforms data acquired from provider API (the gist of the PR).
4. Extended mock tests which make extended use of properties. Note: the sample response has a bit of everything, ex: string, boolean, enumaration, etc. Repetitive fields are truncated for brevity, real endpoint response is just enormous.
Please refer to the mock tests to understand the output, given that provider returns this JSON: https://github.com/amp-labs/connectors/blob/cobalt0s/hubspot-value-type/providers/hubspot/test/metadata-contacts-properties-sampled.json

[CON-967] Hubpsot with FieldsMetadata

---

common/error.go
common/types.go
providers/hubspot/associations.go
providers/hubspot/parse.go
providers/hubspot/read.go
providers/hubspot/record.go
providers/hubspot/search.go
providers/hubspot/types.go
test/hubspot/read-associations/main.go

Test run:
```
$> go run ./test/hubspot/read-associations/main.go
time=2025-01-09T14:17:48.910-08:00 level=DEBUG msg="loading credentials file" path=./hubspot-creds.json
time=2025-01-09T14:17:48.911-08:00 level=DEBUG msg="HTTP request" connector=hubspot connector=hubspot method=POST url=https://api.hubapi.com/crm/v3/objects/companies/search headers="[{Key:Accept Value:application/json}]" bodySize=226
time=2025-01-09T14:17:49.271-08:00 level=DEBUG msg="HTTP request" connector=hubspot connector=hubspot method=POST url=https://api.hubapi.com/crm/v4/associations/companies/contacts/batch/read headers="[{Key:Accept Value:application/json}]" bodySize=75
Reading contacts..
{
"rows": 3,
"data": [
{
"fields": {
"name": "Airbnb, Inc."
},
"associations": {
"contacts": [
{
"objectId": "85902267225", …
```

feat: Batch fetch associations for hubspot

---

providers/zohocrm/metadata.go
providers/zohocrm/types.go
providers/zohocrm/url.go
providers/zohocrm/write.go
test/zohocrm/read/read.go
test/zohocrm/write/write.go

Currently Reading Field Names are case sensitive. With an exception in `id`. This updates the connector so as it can receiver lower cased field names. 
This also updates the Metadata Connector to return lower case field names.
Testing:
- Read
- Metadata:
- Write
For more ctx: https://github.com/amp-labs/samples/pull/7

feat: (zoho) Add support for lowercase fieldnames

---

providers/hubspot/read.go
providers/hubspot/read_test.go
providers/hubspot/search.go
providers/hubspot/test/read-contacts-objects-api.json
providers/hubspot/url.go
test/hubspot/read/contacts/main.go

* Given more API endpoints will be called I have seperated building existing API endpoints into dedicated functions and shortening the conditional branching.
* Bootstrap mock read tests.
* Added dedicated hubpost contacts read. See screenshots below.

tidy(Hubspot): Bootstrap Read tests

---

providers/apollo/metadata_test.go
test/utils/mockutils/errors.go
test/utils/mockutils/metadataResult.go
test/utils/testroutines/comparator.go

This mock test utility allows to compare `ListObjectMetadataResult.Errors` map.
As of now tests ignored and never relied on this field.
The utility allows exact match of errors per objectName or convinent subset, this removes the need to construct the full wrapped golang error, which is not the best pracitce in golang in a first place. It is advised to use `errors.Is()`.
By wrapping  errors under `mockutils.ExpectedSubsetErrors` you are telling the test suite comparator to apply `errors.Is()` in a loop with respect to each error. Help me out how to write better documentation to deliever this idea.
```
Errors: map[string]error{
"arsenal": mockutils.ExpectedSubsetErrors{
common.ErrCaller,
errors.New(string(unsupportedResponse)), // nolint:goerr113
},
},
```
Explanation: The test suite will …

feat(tests): Metadata.Errors compare with subset of err

---

providers/hubspot/read.go

This removes associations from the query params, which removes a redundant portion of the response

chore: Remove redundant associations

---

providers/outreach/parse.go
providers/outreach/read_test.go
test/outreach/read/sample_responses/sequences.json

Outreach sends back data in this format, and we flatten the attributes to be at the top level, but we omit relationships. This is valuable data for correlation. Good to have.

feat: add relationships to outreach response

---

common/types.go
providers/hubspot/objectName.go
providers/hubspot/params.go
providers/hubspot/parse.go
providers/hubspot/read.go
providers/hubspot/read_test.go
providers/hubspot/search.go
providers/hubspot/test/read-lists-1-first-page.json
providers/hubspot/test/read-lists-2-second-page.json
providers/hubspot/types.go
providers/hubspot/url.go
test/hubspot/read/lists/main.go

Lists object while being part of CRM is not part of Objects API. I put it under `crmObjectsOutsideTheObjectAPI` category.
Lists can be quired using 
* `crm/v3/lists` - relies on query params and knowing ids beforehand, otherwise always returns empty array
* `crm/v3/lists/search` - returns all lists even on empty payload. There is no incremental read. Payload gives control over pagination.
Read for `Lists` object defaults to SearchCRM method calling `crm/v3/search`. Next Page token is the offset integer that is used by `Lists` pagination.
Modifying page size to 2 and giving NextPage as `2`, meaning offset 2 returns the last page with last third list.
Read: Contacts
Read+Write Contacts
As you can see the reading in read and write doesn't always return contacts, I noticed the same on main. …

[CON-972] feat(Hubspot): Read Lists object

---

providers/hubspot/metadata.go
providers/hubspot/metadata/metadata.go
providers/hubspot/metadata/schemas.json
providers/hubspot/metadata_test.go
providers/hubspot/objectName.go
providers/hubspot/read.go
providers/hubspot/types.go
test/hubspot/metadata/lists/main.go

Lists is an object that lives under CRM module but is outside Objects APIs. Current implementation of `ListObjectMetadata` focusses on CRM Objects API that uses field discovery endpoint. This is not applicable for `Lists`.
As with other connectors the approach is to make read request for 1 item and use response fields as metadata fields. As a fallback rely on static schema file for the object metadata. This same approach takes place in this PR. Lists object is added under schema.json for the fallback.
Lists
Contacts

[CON-972] feat(Hubspot): Support Lists object by ListObjectMetadata

---

providers/chilipiper.go

None. We could choose to use it though.
Pagination uses the query param `page` and `pageSize`.
You'd have to calculate how much you should go as they give how many records are available.
Used the same for logo & icon. It's an svg.

[CON-999] feat: Add ChiliPiper Connector

---

common/types.go
providers/hubspot/metadata.go
providers/hubspot/metadata_test.go
providers/hubspot/test/metadata-deals-properties-sampled.json
test/hubspot/metadata/contacts/main.go

I didn't find a field that would hold stages for contacts. By reading [this documenation](https://knowledge.hubspot.com/object-settings/set-up-and-customize-pipelines#:~:text=The%20default%20pipeline%20has%20seven,(0%25%2C%20Lost).), I have concluded that there are no such field, because there is no mention of contacts in stages paragraph:
Mock tests where updated in accordance to the format specified in the ticket.

[CON-1039] fix(Hubspot): Separate pipelines and stages

---

internal/datautils/maps.go
tools/fileconv/api3/queries.go

When going over each endpoint some of them will have duplicate suffixes and therefore would be associated with the same objectName. Those are duplicates. They were already reported when running OpenAPI extractor to draw attention for action.
However, one endpoint would still be extracted into `shema.json` and others would be considered duplicates. The one that is used was picked at random (not intended).
All objectNames that have multiple endpoints will be ignored for consistency.
Each is reported by the DEBUG logs.
All duplicates are reporeted.
No matter how many times you run the script the output file doesn't change.

fix(openapi): Consistent report on duplicate objectNames

---

scripts/openapi/keap/endpoints/main.go
scripts/openapi/stripe/endpoints/main.go
tools/fileconv/api3/models.go
tools/fileconv/api3/queries.go
tools/fileconv/api3/strategy.go

Added new method to openapi exploerer `GetEndpointOperations`. It gives convinient summary of the OpenAPI file by specified REST operations.
During Write/Delete implementation you can get a list of relevant endpoints.
See output of `scripts/openapi/stripe/endpoints/main.go`:
For demonstration purpose the same script is added for Keap. It uses 2 files therefore 2 outputs:
`GetEndpointOperations` makes a call to `GetPathItems` ignoring paths that has nested IDs. Only one ID at the end is allowed for update operation.

feat(openapi): Script to report write endpoints

---

common/http.go
common/types.go

The HTTP wrapper methods in the common package do not support making POST requests with the default content type "application/x-www-form-urlencoded".
When deep in the HTTP client call stack, the payload is represented as bytes alongside a list of headers. This information is sufficient to decide how to handle the payload:
1. Default Behavior:
* The existing handling remains unchanged for content types other than `"application/x-www-form-urlencoded"`.
2. New Behavior:
* If the caller specifies the header `"application/x-www-form-urlencoded"`, the payload must be string key-value pairs.
* If the payload does not conform, the client will return a new error, `ErrPayloadNotURLForm`, to signal invalid usage.
* Values are URL-encoded, and the content length is calculated respectively.
Using …

feat(common): Extend HTTP POST with form-urlencoded payload

---

internal/datautils/maps.go
internal/metadatadef/definition.go
internal/staticschema/core.go
scripts/openapi/asana/metadata/main.go
scripts/openapi/constantcontact/metadata/main.go
scripts/openapi/customerio/journeysapp/metadata/main.go
scripts/openapi/gong/metadata/main.go
scripts/openapi/intercom/metadata/main.go
scripts/openapi/iterable/metadata/main.go
scripts/openapi/keap/metadata/main.go
scripts/openapi/keap/metadata/v1/objects.go
scripts/openapi/keap/metadata/v2/objects.go
scripts/openapi/klaviyo/metadata/main.go
scripts/openapi/pipedrive/metadata/main.go
scripts/openapi/pipeliner/metadata/main.go
scripts/openapi/stripe/metadata/main.go
scripts/openapi/zendesksupport/metadata/helpcenter/objects.go
scripts/openapi/zendesksupport/metadata/main.go
scripts/openapi/zendesksupport/metadata/support/objects.go
tools/fileconv/api3/models.go
tools/fileconv/api3/queries.go

Schema struct is a model that is used by `OpenAPI` scripts and one `Scrapper`.
With the upcoming introduction of the GoogleDiscovery extractor, the following considerations are clear:
* Metadata can originate from multiple sources (OpenAPI/GoogleDiscovery/Scrapper).
* A single model should be sufficient to represent all sources. (`metadatadef.Schema`)
* The model should exist within its own package, separate from the tools. (`metadatadef`)
This PR restructures the code to separate data models from tools.
Additonally, fields extractor does not just return the field names as array of strings but array of `metadatadef.Field{}`.

tidy(metadata): Separate Schema definition from tools

---

common/types.go
providers/klaviyo/write.go

An increasing number of connectors no longer treat WriteParams.RecordData as an opaque object.
This PR introduces a member function that returns RecordData as a map:
* If RecordData is already a map, it is returned as is.
* Otherwise, it is serialized to JSON and deserialized back into a raw map.

tidy(write): Convert Payload to map

---

scripts/proxy/proxy.go
scripts/utils/proxyserv/common.go
scripts/utils/proxyserv/oauthApiKey.go
scripts/utils/proxyserv/oauthAuthCode.go
scripts/utils/proxyserv/oauthBasic.go
scripts/utils/proxyserv/oauthClientCred.go
scripts/utils/proxyserv/oauthPassword.go
scripts/utils/proxyserv/proxy.go

The proxy for the OAuth2 password grant type no longer works. However, reverting to an earlier commit when it was introduced confirms that it previously functioned.
The solution is straightforward (one liner): the password grant type should delegate and construct a proxy identical to the authorization code grant type (not client credentials).
While I am at it, refactored the script.
The file is quite large, and while it didn’t take long to locate the issue, it was slightly longer than expected. Splitting the file into multiple smaller files helps to isolate similar-looking functions. There is no point to refactor more than that for little return.
1. All proxies are now created using the same set of arguments. To avoid excessively long function signatures, these values are encapsulated in …

tidy(proxy): Split file, utils package

---

providers/marketo/metadata.go
providers/marketo/read.go
providers/marketo/types.go
providers/marketo/url.go
test/marketo/metadata/metadata.go

Leads API has a few objects that has a dedicated resource for returning Metadata. These objects include
- `Leads`
- `Companies`
- `NamedAccounts`
- `SalesPersons`
-  `Opportunities` (Although this is currently not supporting Read)
This PR Adds support for retrieving Metadata using the `describe` resource.
Tests:

feat: update Marketo Metadata Connector for Leads Module

---

providers/hubspot/parse.go
providers/hubspot/read.go
providers/hubspot/read_test.go
providers/hubspot/record.go
providers/hubspot/search.go
providers/hubspot/test/read-contacts-objects-api.json

No functional change, some refactors to make code easier to understand & reduce repetitive code:
- renamed getMarshalledData to getDataMarshaller to make it more obvious it's a higher order function
- revised getDataMarshaller to handle case when len(fields) is 0, so that GetRecordsFromIds doesn't need to implement it that logic
- also modified the test the check that full raw record is returned, I'm surprised it wasn't failing before

refactor: Hubspot getMarshalledData -> getDataMarshaller

---

go.mod
go.sum
scripts/oauth/token.go
scripts/utils/credutils/tokenWriter.go

Generating a token and repeatedly filling in `accessToken/refreshToken` is a tedious and repetitive task that should be automated.
* The `creds.json` file should be updated when a new access token is acquired.
* The `<provider>-creds.json` file should be updated as well. Ex: `keap-creds.json`.
* `creds.json` and `keap-creds.json` should be updated independently. Ex: if `clientId` is different in both files it should stay that way. We focus only on `accessToken/refreshToken/expiry/expiryFormat`.
* The `expiry` field should be populated to enable proper use of the refresh token (manually it is never updated making it overlooked).
* Other fields should remain unchanged.
* The order of lines should be preserved to allow users to group related fields as desired. 
To handle file loading, …

feat(token): Write access/refresh tokens to creds.json

---

providers/zendesksupport/objectNames.go
providers/zendesksupport/read.go
scripts/openapi/zendesksupport/metadata/helpcenter/objects.go
scripts/openapi/zendesksupport/metadata/support/objects.go

Zendesk was implemented before schema.json included the responseKey, which stores the array of objects.
Although this mapping always existed, it is hardcoded in the script for other connectors. Simmilarly, to reduce mental load, this PR moves all hardcoded registries into the script, ensuring that `schema.json` is the single source of truth.
`schema.json` file includes values as before.

tidy(Zendesk): Read response key from schemas

---

internal/staticschema/core.go
providers/zendesksupport/metadata/schemas.json
providers/zendesksupport/read.go
providers/zendesksupport/schema_test.go
test/freshdesk/read/main.go

The deep connector uses offset pagination and not cursor pagination, and zendesk supports only fetching the first 100 pages with offset pagination. https://developer.zendesk.com/api-reference/introduction/pagination/#using-offset-pagination
Zendesk also supports cursor pagination for some objects, and offset for some. And errors out if you get it wrong. I had to go through objects and figure out the support

fix: add pagination logic for zendesk

---

internal/metadatadef/definition.go
scripts/openapi/utils/convert.go
tools/fileconv/api3/models.go

OpenAPI files may contain [enumeration properties](https://swagger.io/docs/specification/v3_0/data-models/enums/).
This PR extends the Field struct to include new properties derived from OpenAPI files:
* Type
* List of enumeration options
Many connectors can benefit from enumeration data present in OpenAPI files. All of them can migrate to `field metadata version 2`.

feat(openapi): Return field enums

---

providers/zendesksupport/connector.go
providers/zendesksupport/delete.go
providers/zendesksupport/objectNames.go
providers/zendesksupport/read.go
providers/zendesksupport/read_test.go
providers/zendesksupport/write.go
providers/zendesksupport/write_test.go

Issues discovered during integration testing:
* Forgot to update write URL endpoints. Incremental endpoints are unique for Read not Write/Delete.
* `start_time` cannot be less than 1 minute old. If it is then Since parameter is adapted to avoid an error.

[CON-1526]fix(zendesk): Incremental objects diff write URLs

---

providers/instantly.go

**Expanded Endpoints:** V2 offers twice the number of endpoints compared to V1.
**Granular API Scopes:** Allows precise control over API keys and their usage.
**Multiple API Keys:** Supports creating multiple keys with different privileges. API keys can also be created via an endpoint.
**Pagination:** Now uses limit and starting_after parameters.
InstantlyAI Provider = "instantlyAI"
URL: http://localhost:4444/v2/campaigns
URL: http://localhost:4444/v2/campaigns
URL: http://localhost:4444/v2/campaigns/5dd3c8b5-52ba-4679-866a-c7c2cad699a2
URL: http://localhost:4444/v2/campaigns/5dd3c8b5-52ba-4679-866a-c7c2cad699a2
URL: http://localhost:4444/v2/campaigns/5dd3c8b5-52ba-4679-866a-c7c2cad699a2
Requesting a paginated list of campaigns using limit:
URL: http://localhost:4444/v2/campaigns?limit=2 …

[CON-1253] feat: Add Instantly(V2) connector

---

providers/helpScoutMailbox.go

With Authorization Code Grant,  The refresh token can only be used once(found this by testing).  Updating this to use client credentials grant for simplicity.

feat: update grant type helpScout connector

---

common/types.go
providers/salesforce/connector_test.go
providers/salesforce/register.go
providers/salesforce/subscribe.go
test/front/metadata/main.go
test/front/read/main.go

Problem:
- data is saved in the database as `byte[]`, server needs to convert it to the correct format to pass to the connector for updating a subscription. 
When we want to json unmarshal, we basically need the container or shell for the data. 
Instead of the connector interface to have json unmarshal interface methods, we instead have NewSubscribeParams, NewRegistrationParams, NewSubscribeResult NewRegistrationResult methods that will return shells for provider specific data structure we can json unmarshal into. This will make the interface easier to understand and having NewOOO(). 
The RegistrationResult struct is defined as below
```
// in common/types.go
type RegistrationResult struct {
RegistrationRef string
Result          any  // this is stored as []byte in database
Status …
```

[ENG-1889] Salesforce Subscribe Add EmptyResult method to connector interface

---

internal/components/operations/operations.go
providers/blueshift/handlers.go
providers/front/handlers.go
providers/gorgias/handlers.go
providers/groove/handlers.go
providers/helpscout/handlers.go
providers/netsuite/handlers.go
providers/smartleadv2/handlers.go

This PR modifies the ParseResponse handler signature in HTTPOperation to include the original request, enabling better access to request parameters needed for pagination.
- Updated HTTPHandlers.ParseResponse signature to include *http.Request parameter in `internal/components/operations/operations.go`
- Updated all affected connector implementations to match the new signature
Before:
```go
ParseResponse func(context.Context, RequestType, *common.JSONHTTPResponse) (ResponseType, error)
```
After
``` go
ParseResponse func(context.Context, RequestType, *http.Request, *common.JSONHTTPResponse) (ResponseType, error)
```

feat: Update HTTPHandlers to include request parameter in ParseResponse

---

internal/components/transport.go
test/blueshift/metadata/metadata.go
test/blueshift/read/main.go
test/front/metadata/main.go
test/front/read/main.go

Transport should override base URL. This is useful for mock tests, where the base URL is replaced with the test server URL.
Unblocks mock tests.

feat(transport): SetBaseURL

---

common/types.go
providers/salesforce/record.go
providers/salesforce/soql.go
providers/salesforce/soql_test.go
test/salesforce/record/main.go

* Extended existing SOQL builder to accept list of identifiers.
* Added mock test to ensure query is built as expected.
* Added test script to query Accounts (see below).
`salesforce/record/main.go`:
Associations argument at `GetRecordsWithIds` is preserved to **match method signature** of other deep connectors. However, it is not used by the Salesforce implementation.

[CON-1591]feat(Salesforce): GetRecordsWithIds

---

scripts/utils/credutils/tokenWriter.go

Zendesk is such a provider that doesn't return refresh token. Regenereting `accessToken` for this type of provider doesn't make sense to include empty refresh token fields.

tidy(scripts/oauth): Ignore refresh token if empty

---

providers/happyFox_Chat.go

const HappyFoxChat Provider = "happyFoxChat"
HappyFox Chat’s REST API provides read-only access to your data for use in your application.
URL: http://localhost:4444/v1/agents
URL: http://localhost:4444/v1/agents/67af15298a8e6a70c0c318f4
1. Requesting the paginated list of agents using limit and page parameter with value 1 for both.
URL: http://localhost:4444/v1/agents?page=1&limit=1
2. Requesting the next paginated list of agents giving limit as 1 and page value as 2.
URL: http://localhost:4444/v1/agents?page=2&limit=1
**NOTE**
You can also use the URL from the "next" field in the previous response to retrieve the next set of results.

[CON-1125] feat: Add HappyFox Chat connector

---

go.mod
go.sum
internal/httpkit/response.go

* Created the `httpkit` package.
* The Capsule provider includes the next page URL in the `Link` header. This PR adds utility to parse and extract URL data.
* The implementation delegates to `github.com/deiu/linkparser` library.

feat(httpkit): Link header parser

---

providers/blueshift.go
providers/blueshift/metadata/openapi/api.yaml
providers/blueshift/metadata/schemas.json
providers/blueshift/supports.go
scripts/openapi/blueshift/metadata/main.go
test/blueshift/read/main.go

1.  Fix `onsite_slots` response key mapping in Blueshift 
2. Remove unsupported `campaigns` write object  in Blueshift

chore(blueshift): update ListMetadata schema and write support

---

providers/github/README.md
providers/github/connector.go
providers/github/metadata/openapi/file.go
providers/github/metadata/schemas.json
providers/github/metadata/scraping.go
scripts/openapi/github/metadata/main.go
test/github/connector.go
test/github/metadata/main.go

[CON-1575] feat: Add ListMetadata Github Connector

---

providers/salesforce/subscribe.go
test/github/read/main.go

The Update method had bugs that the it was deleting all objects. This PR fixes the issue. 
Test Result
- The lookups are not deleted after update

Fix UpdateSubscription method for Salesforce to delete correct objects and return correct ressult

---

scripts/docs/salesloft/main.go

Prints lines that can be copy pasted into the docs repo.

[ENG-2051] feat(docs): Print Salesloft objects

---

internal/components/deleter/deleter.go
internal/components/deleter/deleter_test.go
internal/components/mocked/connector.go
internal/components/operations/types.go
internal/components/reader/reader.go
internal/components/reader/reader_test.go
internal/components/schema/openapi_test.go
internal/components/writer/writer.go
internal/components/writer/writer_test.go

Common test cases no longer need to be repeated, which is a great improvement. Shared test cases now belong to components.
Deep connector mock tests are now more **focused**, covering only **business logic**.
#Changes
* Introduced a mocked package that provides a base connector, which can be extended via struct composition to function as a `ReadConnector`, `WriteConnector`, etc.
* Added tests for Read, Write, Delete, and OpenAPI Metadata.

feat(components): Mock Tests

---

common/urlbuilder/url.go
common/urlbuilder/url_test.go

With the newly refactored deep connectors, we often work directly with raw `url.URL`. This bypasses the query parameter utilities provided by `urlbuilder`, making simple query parameter modifications cumbersome.
`urlbuilder.URL` can now be created from a raw `url.URL`.

feat(urlbuilder): Construct from url.URL

---

providers/ringover.go

RingOver offers two Base URLs: one for the EU and one for the US. The API key generated for the US cannot be used with the EU Base URL, and vice versa. Therefore, two proxy connectors have been created: one for the EU and one for the US.
URL: http://localhost:4444/v2/teams
URL: http://localhost:4444/v2/tags
URL: http://localhost:4444/v2/blacklists/numbers/81247638412
Pagination works with `limit_offset` and `limit_count` . limit_offset skips X items, and limit_count returns Y items after that
Invalid payload
Incorrect method
Invalid url

[CON-1532] feat: add RingOver proxy connector

---

examples/utils/api_key.go
providers/utils.go
scripts/utils/proxyserv/oauthApiKey.go

We have a provider (Asana) which penalizes us when we refresh the token too early (well, penalizes is a strong word, it just doesn't follow typical refresh logic rules). As a result we need to refresh those tokens reactively (wait for a 401) rather than proactively (wait for some timestamp). This PR lets us do the plumbing to support this, by adding a generic Unauthorized handler.

feat: Add a generic UnauthorizedHandler to HTTP client

---

providers/monday.go

no workspace variables used
Monday API is a graphql API hence all the calls are POST calls like this: 
```
curl -X POST 'https://api.monday.com/v2' \
-H 'Content-Type: application/json' \
-d '{"query": "query { me { is_guest created_at name id}}"}'
```
URL: `localhost:4444/v2`
URL: `localhost:4444/v2`
Here pagination works with `limit` & `page` params to the graphQL query

[CON-957] feat: add monday proxy connector

---

internal/goutils/utils.go
tools/fileconv/api3/parameters.go
tools/fileconv/api3/queries.go

Object names are made up usually for those cases where last URI part collides with other endpoints.
To avoid made up object names the full URL path will be used by default as an object name that collides with others.
This is maybe a better approach then purely reporting the duplicates in the logs. The developer my oversee and forget about addressing those objects. On the contrary `schema.json` will have all objects without exceptions.
`objectEndpoints` still exists as an override as a direct object name control.
`api3.WithDuplicatesResolver` is a procedure to turn any colliding endpoint into an object name.

feat(opeanapi): Default duplicate path resolver

---

providers/keap/parse.go
providers/keap/read.go
providers/keap/read_test.go
test/keap/read/main.go

Requested available fields using `ListObjectMetadata`.
Experience field is one of the custom fields. As you can see this field is not present inside raw response. But requesting such field will include it inside `fields` JSON object.

[CON-1038] fix(Keap): ReadResult.Raw

---

providers/clickup.go

>  There is only one object that supports the read operation.
> There are no objects for writing operations.

[CON-1572] feat(clickup): enable read support

---

providers/salesforce/write.go
providers/salesforce/write_test.go

In Salesforce, creates return a recordId, however updates don't. This is due to how their API is written, which returns an empty body as a response for updates. This is confusing for some customers who rely on this field. This change will include the record id in all update responses.

Salesforce - add RecordId for updates

---

providers/redditAds.go

redditAds uses a function named `Init`, however go won't automatically invoke this, and also we don't really need to export this. I suspect this was a typo. This fixes that.

fix: redditAds: Init -> init

---

providers/marketo/read.go
providers/marketo/types.go
providers/marketo/url.go
test/marketo/read/read.go

Tests:
Added some comment on the task [here](https://linear.app/ampersand/issue/CON-1642/support-incremental-read-for-leads#comment-c2532a5d)
Closes CON-1641 as well.

[CON-1642] feat: Add incremental read support for Marketo Leads API

---

providers/salesforce/subscriptionEvent.go
providers/salesforce/subscriptionEvent_test.go
providers/salesforce/test/subscription/update_user.json

This adds logic to normalize field names, so that updates generated by Salesforce compound fields will strip out the compound field prefix.

fix: (Salesforce) Normalize compound field names

---

common/header.go
common/query.go

The contract of `http.Transport.Do` requires that the transport making modifications won't impact the original. This honors that contract more completely by ensuring that the unauthorized handler is given the original input, thus letting them do their own logic on the original message, rather than on the version we modified.

fix: Give unauthorized handler access to the original message

---

providers/marketo/read.go
providers/marketo/url.go
scripts/oauth/token.go
test/marketo/read/read.go

Issue:
Reading Leads, using the Incremental read approach, should be treated differently in the first call.  The next-page call should be delegated to the full Lead read, as it takes care of adding subsequent ids, provided the starting Id. 
Reading Next-Page Leads:

fix: Reading Next-Page in Marketo Incremental Leads

---

mock/connector.go
mock/connector_test.go
mock/params.go
mock/types.go

In unit tests, it would be nice to mock all of the available connector interfaces, not just read and write and listObjectMetadata. This adds the rest.

chore: Make the mock connector implement all interfaces

---

common/urlbuilder/url.go
common/urlbuilder/url_test.go
internal/datautils/slice.go
test/utils/testroutines/comparator.go

Strict string comparison of `NextPage` tokens in mock tests isn't reliable:
```
actual.NextPage.String() == expectedNextPage
```
Query parameters can appear in different orders, making equivalent URLs fail the comparison.
Introduced a `compareNextPageToken` method used by all read test suites. It delegates to the `urlbuilder.URL` equality check.
Added test cases with semantically equivalent but differently ordered URLs to validate the implementation.

feat(test): Soft equals NextPage URLs

---

common/paramsbuilder/catalogVariable.go
common/paramsbuilder/catalogVariable_test.go
common/paramsbuilder/metadata.go
common/substitutions/registry.go
common/urlbuilder/url.go
connector/connector.go
connector/params.go
scripts/proxy/proxy.go
scripts/utils/proxyserv/common.go
scripts/utils/proxyserv/oauthApiKey.go
scripts/utils/proxyserv/oauthAuthCode.go
scripts/utils/proxyserv/oauthBasic.go
scripts/utils/proxyserv/oauthClientCred.go

We are not limited to workspace catalog variables. The Google connector requires support for multiple modules, each differing by subdomain. This can only be communicated via metadata.
AWS connector also relies uppon region and some service specific metadata.
* `connectors.NewConnector` now accepts `WithMetadata` option.
* `paramsbuilder.Metadata` returns all values as potential catalog variables.
* Proxy instances, regardless of auth type, capture substitutions and use the `WithMetadata` option.

feat: Construct proxy connector with metadata+catalogVars

---

common/scanning/credscanning/fields.go
common/scanning/credscanning/provider.go
test/utils/creds.go

`credscanning` infers fields in the `<name>-creds.json` file based on the ProviderInfo, no more no less.
Custom fields can be passed using variadic argument. Then values will be available by calling `reader.Get(someField credscanning.Field)`

feat(creds): Custom JSON/ENV fields

---

providers/aws/internal/core/commands.go
providers/aws/internal/core/requests.go
providers/aws/internal/identitystore/metadata.go
providers/aws/internal/identitystore/schemas.json
providers/aws/internal/ssoadmin/metadata.go
providers/aws/internal/ssoadmin/schemas.json
providers/aws/metadata.go
providers/aws/metadata_test.go
test/aws/metadata/main.go

Using [AWS Golang SDK](https://github.com/aws/aws-sdk-go-v2/tree/main) inferred object schema response. Metadata is stored under `schema.json` associated with each AWS service.
Package `awsidentitystore` matches `identitystore` service and `awsssoadmin` matches `sso-admin`.
When object is queried search for metadata service by service.
AWS Identity Center module combines `identitystore` and `sso-admin`. In future other AWS modules may correspond to one or many AWS services.

[CON-1667] feat(aws): Metadata

---

internal/staticschema/core.go
providers/aws/internal/ssoadmin/schemas.json
providers/aws/responses.go

Some Object names differ among `CLI` and `response JSON key`.
As a standard I use names used in `CLI` because that is documented.
Ex: AccountAssignmentCreationStatus: AWS command header will use `List`AccountAssignmentCreationStatus, while response will be stored at AccountAssignment`s`CreationStatus.

fix(aws): Mistmatching Read/Metadata object names

---

providers/insightly/custom.go
providers/insightly/handlers.go
providers/insightly/read_test.go
providers/insightly/test/read/contacts/list.json
providers/insightly/test/read/fruits-custom-object/list.json
providers/insightly/url.go
test/insightly/read/customObject/main.go
test/utils/mockutils/mockserver/switch.go

Custom fields on custom object or core object can be requested during the connector read operation.
The fields are flattened and moved to the fields. The raw response is not modified. But custom field querying is treated as equal to the core fields.

[CON-1666] feat(insightly): Custom objects & fields

---

providers/marketo/url.go
test/marketo/read/read.go

This updates the Read Activity API to use the timestamp `1970-01-01` as the default since parameter when none is provided.
This ensures all historical activities in the instance are retrieved, which is appropriate when backfillHistory is set to true.
Tests:

feat: Add support to read all Marketo Lead Activities

---

common/types.go
providers/hubspot/record.go

Exposing this error so that the server can detect it specifically. Also fix typos.

chore: expose ErrGetRecordNotSupportedForObject

---

providers/hubspot/record.go

User is not CRM object, but the API endpoint has the same structure, so we just need to add to the list.

Enable user object for Hubspot GetRecordsById

---

test/utils/testscenario/crd.go
test/utils/testscenario/crud.go

Similar to CRUD test scenario this PR adds Create/Reat/Delete ignoring Update in case deep connector object doesn't support update.
PS: Originaly it was developed for AWS, but I figured out update, therefore no test usage. But I think it will come in handy.

feat(test): Create/Read/Delete scenario

---

go.mod
go.sum
providers/aws/connector.go
providers/aws/delete_test.go
providers/aws/internal/core/commands.go
providers/aws/internal/core/object.go
providers/aws/internal/identitystore/delete.go
providers/aws/internal/identitystore/objects.go
providers/aws/internal/identitystore/read.go
providers/aws/internal/identitystore/write.go
providers/aws/internal/ssoadmin/delete.go
providers/aws/internal/ssoadmin/objects.go
providers/aws/internal/ssoadmin/read.go
providers/aws/internal/ssoadmin/write.go
providers/aws/requests.go
providers/aws/responses.go
providers/aws/supports.go
providers/aws/test/write/issuer/new.json
providers/aws/test/write/user/new.json
providers/aws/write_test.go
test/aws/write-delete/groups/main.go
test/aws/write-delete/trust-token-issuer/main.go
test/aws/write-delete/users/main.go

* AWS Core package defines object registry structs. 
* Each AWS package maps 
* `object` to AWS commands we support,
* `object` to `resource identifier` for request payload or id location in response.
* Create/Update injects IdentityStoreId or InstanceARN into payload. This is coming from connector metadata. Each service relies on these identifiers for majority of objects.
* Mock tests capture AWS headers sent and payload which is enhanced using connector-metadata variables and record id in case of update/delete operation.
* Added 2 tests to create/update/delete `User`, `Groups` and `TrustedTokenIssuers`, see testing section below.

[CON-1667] feat(aws): Write

---

providers/utils.go

Workspace is a first class field on our API, so we need to keep supporting it. This is a helper that lets you quickly check if it exists as a requirement on the catalog.

chore: add catalog helper

---

internal/components/schema/openapi_test.go
internal/staticschema/convertors.go
providers/asana/metadata_test.go
providers/chilipiper/metadata.go
providers/chilipiper/metadata_test.go
providers/constantcontact/metadata_test.go
providers/customerapp/metadata_test.go
providers/gong/metadata_test.go
providers/insightly/metadata_test.go
providers/instantly/metadata_test.go
providers/intercom/metadata_test.go
providers/iterable/metadata_test.go
providers/keap/metadata_test.go
providers/klaviyo/metadata_test.go
providers/pipeliner/metadata_test.go
providers/salesloft/metadata_test.go
providers/smartlead/metadata_test.go
providers/stripe/metadata_test.go
providers/zendesksupport/metadata_test.go
providers/zoom/metadata_test.go

In scenarios where an object is not supported (i.e., it does not have a static schema), we currently fail the entire call. This PR adds the error to the Errors map.
This change will enable future flexibility—for example, if we implement a fallback schema provider, we can later use it for the failed objects.

fix: Gracefully handle unsupported objects via Errors map

---

internal/components/provider.go
internal/components/transport.go
providers/atlassian/connector.go
providers/hubspot/connector.go
providers/hubspot/metadata.go
providers/hubspot/string.go
providers/hubspot/url.go
providers/keap/connector.go
providers/keap/delete.go
providers/keap/metadata.go
providers/keap/read.go
providers/keap/write.go
providers/klaviyo/connector.go
providers/klaviyo/delete.go
providers/klaviyo/metadata.go
providers/klaviyo/read.go
providers/klaviyo/write.go
providers/marketo/connector.go
providers/marketo/metadata.go
providers/marketo/url.go
providers/zendesksupport/connector.go
providers/zendesksupport/customFields.go
providers/zendesksupport/metadata.go
providers/zendesksupport/read.go
providers/zoom/connector.go
providers/zoom/metadata.go
providers/zoom/read.go
providers/zoom/write.go

Connectors built using the components package will automatically load module information into `ProviderContext`, which belongs to `Transport`, a field of the base `components.Connector`.
This PR only introduces the declaration and initialization of this capability — it does not utilize `moduleInfo` yet.
For example, AWS is built using `components.Connector` and will therefore have module info loaded automatically:
The following connectors manually invoke `ReadModuleInfo` and store the result directly in their `<provider>.Connector` struct:
* Atlassian
* Hubspot
* Keap
* Klaviyo
* Marketo
* Zendesk
* Zoom

[CON-1619] feat(modules): Connectors read moduleInfo

---

providers/freshdesk.go

I think It was blocked before as it uses workspace + basic Auth.
Tests:
Using the `Link` header next page

feat: enable freshdesk proxy

---

common/error.go
common/http.go
common/json.go
common/types.go
common/xml.go
connectors.go
providers/hubspot/associations.go
test/utils/testroutines/comparator.go

One of our customers wants to have access to the raw HTTP response -- no error prefixes added. This PR makes it possible to extract the original response, and pass it along so that the user can do their own parsing.

[ENG-2284] feat: Include raw HTTP response in error messages

---

common/error.go
common/http.go
common/json.go
common/xml.go
providers/hubspot/errors.go

We rely on common.HTTPError to populate certain fields. Most connectors return this, hubspot doesn't. This PR makes it so that hubspot wraps its errors in this type so that we can extract what we need when errors happen.

fix: Make hubspot use NewHTTPError for errors

---

providers/front/handlers.go
providers/front/parse.go
test/front/read/main.go

With this we can support incremental reads for contacts object in Front Connector.
Updated the pageSize as well (it was 1 by mistake)
Tests:

feat: Add incremental read contacts Front Connector

---

.github/workflows/linter.yml

Recently getting this issue once in a while:
[Reference.](https://github.com/amp-labs/connectors/actions/runs/15593835862/job/43919286718?pr=1746)
Maybe enforcing building code with go version at `exactly` version 1.23.3 would solve this.

fix(CI): Go v1.23.3

---

providers/braze.go

URL: https://proxy.withampersand.com/catalogs
URL: https://proxy.withampersand.com/catalogs
URL: https://proxy.withampersand.com/preference_center/v1/615bd689-f825-4757-9f3c-addabd52b629
invalid path.
Pagination uses `limit` and `offset` (for some endpoints)
increasing offset:

[CON-1303] feat: enable braze proxy connector

---

providers/Fathom.go

URL: http://localhost:4444/external/v1/meetings
URL: http://localhost:4444/external/v1/teams
URL: http://localhost:4444/external/v1/team_members
There is no POST, PUT, DELETE, or PATCH methods.
Fathom pagination works using a cursor.
The server returns a fixed number of items and includes a new cursor for the next page in the response.
The client uses this cursor to load the next set of items.
First Page
Next Page
Icons for both dark and regular theme
Logo for dark theme
Logo for Regular theme

[CON-1763] feat: add Fathom connector

---

providers/claricopilot/connector.go
providers/claricopilot/handlers.go
providers/claricopilot/metadata_test.go
providers/claricopilot/test/calls.json
providers/claricopilot/test/users.json
test/claricopilot/connector.go
test/claricopilot/metadata/main.go

[CON-1727] feat(clariCopilot): add ListObjectMetadata

---

providers/chargeOver.go

Wrong verb applied,
invalid path.
There is no explicit data to indicate there is next page. You manually iterate to check if there is. usig the `limit` and `offset` params

[CON-57] feat: enable chargeover proxy connector

---

providers/vtiger.go

URL: https://proxy.withampersand.com/v1/vtiger/default/tags_retrieve?id=3x493
URL: https://proxy.withampersand.com/v1/vtiger/default/tags_add
URL: https://proxy.withampersand.com/v1/vtiger/default/tags_delete
**Invalid Endpoint**
**Invalid Method**

[CON-402] feat: Enable proxy : vtiger

---

providers/atlassian.go
providers/utils_test.go
test/utils/testutils/checks.go

This PR makes 2 updates:
- Removes version numbers. As a general rule of thumb, base URLs should never contain version numbers. This allows customers who are making proxy calls to use any version of the API they would like to use.
- Update the URL of the base module's base URL to match that of the Jira module (which is the default module.) This is because `api.atlassian.com` is a pretty unusable base URL for proxy request since the builder won't know the cloud ID. I've also double checked our logs and nobody is using Atlassian proxy actions yet, so this isn't going to break any customers.

fix: update base URLs of Atlassian connector

---

common/naming/formatting.go
providers/linear/connector.go
providers/linear/handlers.go
providers/linear/types.go
test/linear/connector.go
test/linear/metadata/main.go

[CON-1929] feat(linear): add ListObjectMetadata

---

providers/flatFile.go

URL: https://proxy.withampersand.com/v1/events
URL: https://proxy.withampersand.com/v1/jobs
URL: https://proxy.withampersand.com/v1/jobs/us_jb_8UXI8zqD
FlatFile pagination works using pageSize and pageNumber.
The user sends:
pageSize — how many items to return per page (default is 20 if not provided).
pageNumber — which page of results to return based on the pageSize.
The response includes pagination info such as currentPage, pageCount, and totalCount to help navigate through pages.
First Page
Second Page
Wrong URL path
Wrong payload

[CON-1826] feat: enable Flatfile connector

---

test/atlassian/connector.go
test/atlassian/write-delete/main.go

Fixes read-write script for atlassian.
Dynamically uses cloud id from credential file.

chore(atlassian): Fix read-write script

---

internal/components/operations/operations.go
providers/dynamicsbusiness/metadata_test.go

In case the response is not OK and the connector has not initialised it's own error handler, we fallback to the basic error handler.

feat: Add fallback to basic error handler when connector has no error handler

---

providers/zohocrm/subscribe.go
providers/zohocrm/subscribe_test.go
providers/zohocrm/vars.go
test/zohocrm/subscribe/subscribe.go

This PR fixes the error when more than 2 fields are being watched for subscription. 
```
jlim@Mac connectors % go run ./test/zohocrm/subscribe/subscribe.go
time=2025-07-10T15:45:28.827-07:00 level=DEBUG msg="loading credentials file" path=./zoho-creds.json
time=2025-07-10T15:45:28.830-07:00 level=DEBUG msg="HTTP request" method=GET url=https://www.zohoapis.com/crm/v7/settings/modules correlationId=29ce682c-8a10-44e4-b335-ec763d13a50e headers.Accept=application/json
time=2025-07-10T15:45:29.307-07:00 level=DEBUG msg="HTTP response" method=GET url=https://www.zohoapis.com/crm/v7/settings/modules correlationId=29ce682c-8a10-44e4-b335-ec763d13a50e headers.Cache-Control="no-store, no-cache, must-revalidate, private" headers.Expires="Thu, 01 Jan 1970 00:00:00 GMT" …
```

[ENG-2214]Zoho: fix field grouping for more than 2 fields 

---

providers/google/connector.go
providers/google/delete_test.go
providers/google/internal/calendar/adapter.go
providers/google/internal/calendar/operations.go
providers/google/test/delete/calendarList/not-found.json
providers/google/test/write/calendarList/error-missing-color.json
providers/google/test/write/calendarList/new.json
providers/google/test/write/events/new.json
providers/google/write_test.go
test/google/calendar/write-delete/calendarList/main.go
test/google/calendar/write-delete/events/main.go

[CON-617] feat(google): Calendar - Write

---

providers/avoma.go

**For template object**
**For smart_categories object**
Link pull request to testdata repo which contains installation file: https://github.com/amp-labs/testdata/pull/68

[CON-1713] feat: Enable read+write: avoma

---

providers/lever.go
providers/lever/README.md
providers/lever/connector.go
providers/lever/errors.go
providers/lever/handlers.go
providers/lever/metadata_test.go
providers/lever/test/opportunities.json
providers/lever/test/requisition_fields.json
providers/lever/utils.go
test/lever/connector.go
test/lever/metadata/main.go

[CON-1888] feat: Added lever metadata functionality

---

providers/zendesk.go

Mailmonkey using Oauth2 with Authorizatio code grant.
[zendeskChat samples](https://github.com/amp-labs/testdata/pull/66)

[CON-1058] feat: Enable read, write zedeskChat Connector

---

connector/new.go

Notes:
In the Lever connector, there are two types of configurations: one for production and one for testing. For now, I have added the initialization to the testing configuration because I only have access to the testing setup. After completing the integration testing, I will switch to the production configuration.

[CON-1995] feat: Add initialization to Lever connector

---

providers/chilipiper.go

[sample test-data link](https://github.com/amp-labs/testdata/tree/main/chilipiper)

[CON-993] feat: enable read, write Chilipiper connector

---

providers/front.go

[test-data Link](https://github.com/amp-labs/testdata/tree/main/front)

[CON-1068] feat: enable read, write Front connector

---

connector/new.go
providers/lever.go
providers/lever/README.md
providers/lever/connector.go
providers/lever/support.go

**For object requisitions**
**For object requistion_fields**
Link pull request to testdata repo which contains installation file: https://github.com/amp-labs/testdata/pull/69

[CON-1997] feat: Enable read+write : Lever

---

providers/salesforce/bulk-info_test.go
providers/salesforce/bulk-query_test.go
providers/salesforce/bulk-read_test.go
providers/salesforce/bulk-write_test.go
providers/salesforce/connector.go
providers/salesforce/metadata_test.go
providers/salesforce/read_test.go
providers/salesforce/test/bulk/delete/launch-job-opportunity.json
providers/salesforce/test/bulk/delete/update-job-opportunity.json
providers/salesforce/test/bulk/info/complete-failure.json
providers/salesforce/test/bulk/info/in-progress.json
providers/salesforce/test/bulk/info/partial-failure.json
providers/salesforce/test/bulk/info/success.json
providers/salesforce/test/bulk/read-launch-job-account.json
providers/salesforce/test/bulk/write/launch-job-opportunity.json
providers/salesforce/test/bulk/write/update-job-opportunity.json
providers/salesforce/test/metadata-organization-sampled.json
providers/salesforce/test/read-list-contacts.json
providers/salesforce/test/read-list-leads.json
test/utils/mockutils/mockserver/README.md

```
=== RUN   TestBulkDelete
=== PAUSE TestBulkDelete
=== RUN   TestJobInfo
=== PAUSE TestJobInfo
=== RUN   TestGetBulkQueryInfo
=== PAUSE TestGetBulkQueryInfo
=== RUN   TestJobResults
=== PAUSE TestJobResults
=== RUN   TestGetSuccessfulJobResults
=== PAUSE TestGetSuccessfulJobResults
=== RUN   TestGetBulkQueryResults
=== PAUSE TestGetBulkQueryResults
=== RUN   TestBulkQuery
=== PAUSE TestBulkQuery
=== RUN   TestBulkRead
=== PAUSE TestBulkRead
=== RUN   TestBulkWrite
=== PAUSE TestBulkWrite
=== RUN   TestSubscribeConnector
=== PAUSE TestSubscribeConnector
=== RUN   TestCreateMetadata
=== PAUSE TestCreateMetadata
=== RUN   TestListObjectMetadata
=== PAUSE TestListObjectMetadata
=== RUN   TestListObjectMetadataPardot
=== PAUSE TestListObjectMetadataPardot
=== RUN   TestRead
=== PAUSE …
```

chore: upgrade salesforce to v60.0

---

providers/teamleader/connector.go
providers/teamleader/handlers.go
test/teamleader/connector.go
test/teamleader/metadata/main.go

[CON-1348] feat(teamleader): add ListObjectMetadata

---

providers/Fathom.go

[CON-1988] feat(fathom): enable Read and Write

---

providers/meta.go

**Icons for Dark and Regular mode**
**Logo for Regular mode**
**Logo for Dark mode**
**Notes:**
Facebook and WhatsApp connectors share the same base URL, auth URL, and token URL. As they both belong to Meta, I merged their provider configurations into a single Meta configuration.

[CON-2025] chore: [Meta] Combine the Facebook and WhatsApp provider configurations into Meta configuration

---

providers/braze/handlers.go
providers/braze/support.go
test/braze/metadata/main.go
test/braze/read/main.go

With this builders can use `campaigns` instead of `campaigns/list` and similar objects while reading.
Metadata Live Tests:
Read Live Tests:
Write Live Tests:

fix: Map ObjectName to endpoints in Braze connector

---

common/types.go

- Currently, our associations type doesn't let the connector send associations as full records
- Salesforce can fetch associations directly in the Read call, so we can populate it within the connector

chore: extend associations type to allow sending full record from the connector

---

providers/flatfile/parse.go
test/flatfile/read/main.go

`environments` object returns a pagination object in the response. However, unlike others, when fetching a non-existent page, it doesn't return an empty array—instead, it returns the records from the last page. This change handles that behavior.

feat(flatfile): enhance pagination handling

---

common/csv.go
common/http.go

We don't need to explicitly set the Content-Length header for requests. Go will automatically fill this in, especially if the request body is a bytes.Reader or similar.
Example success run (test/salesforce/read/account):
```
time=2025-07-23T13:38:17.376-07:00 level=DEBUG msg="loading credentials file" path=./salesforce-creds.json
time=2025-07-23T13:38:17.381-07:00 level=DEBUG msg="HTTP request" method=GET url="https://orgfarm-b3cb75c050-dev-ed.develop.my.salesforce.com/services/data/v60.0/query?q=SELECT+Name%2CBillingCity%2CIsDeleted%2CSystemModstamp%2CId+FROM+Account+WHERE+SystemModstamp+%3E+2024-08-28T13%3A47%3A37Z+AND+SystemModstamp+%3C%3D+2025-01-01T00%3A00%3A00Z" correlationId=06a42771-c94e-4da5-98c3-3a1b86fc805d headers.Accept=application/json
time=2025-07-23T13:38:17.728-07:00 …
```

fix: Get rid of explicit content-length handling

---

common/csv.go
common/http.go

We're not seeing HTTP responses in the logs for non-2xx responses. We see the error but not the actual body and headers. Turns out we're bailing out before the log lines happened. This just moves things around so that the response logging happens before any error handling, so we always see the response.
Example success request: https://gist.github.com/eberle1080/dcd33c4ec65bc10dea6dac7dbd39ab68
Example failed request: https://gist.github.com/eberle1080/ee89dae9855911dfecb36afc0d54dc35

fix: Move response logging to happen before error handling

---

providers/braze.go

Mailmonkey using API key.
[Test-data](https://github.com/amp-labs/testdata/pull/72)

[CON-1895] feat: Enable read, write Braze connector

---

test/constantcontact/metadata/privileges/main.go
test/customerio/journeysapp/metadata/main.go
test/dynamicscrm/metadata/main.go
test/gong/metadata/main.go
test/instantly/metadata/main.go
test/intercom/metadata/main.go
test/iterable/metadata/main.go
test/klaviyo/metadata/main.go
test/pipeliner/metadata/main.go
test/salesforce/metadata/read/organizations/main.go
test/salesloft/metadata/main.go
test/smartlead/metadata/main.go
test/smartleadv2/metadata/main.go
test/utils/mockutils/metadataResult.go
test/utils/testscenario/README.md
test/utils/testscenario/matching-metadata.go
test/zendesksupport/metadata/brands/main.go

The live tests were overly verbose, duplicated, and relied on the deprecated `FieldsMap`.
This PR introduces reusable live test templates to simplify and standardize metadata validation.
Available live test templates:
* `testscenario.ValidateMetadataExactlyMatchesRead` -- Verifies that the `ListObjectMetadata` implementation returns all fields present in the `Read` response.
* `testscenario.ValidateMetadataContainsRead` -- Verifies that `ListObjectMetadata` returns all fields provided by `Read`, even if `Read` omits null or empty fields. The test fails if `ListObjectMetadata` does not include a field present in the `Read` response.

tidy(testscenario): Compare Read/Metadata fields match

---

internal/components/schema/composite.go
providers/gitlab.go

this PR fixes 2 issues:
- ListObjectMetadata was actually mutating the objects param, instead of making a copy of it, this caused errors in getHydratedRevision
- `gitlab` is preferred over `gitLab`

fix: ListObjectMetadata shouldn't mutate original object and fix gitlab casing

---

providers/gitlab/handlers.go
test/gitlab/read/main.go

- Adds support for reading user owned projects + membership projects. 
- Adds since parameter implementation, works for both merge_requests and projects.
- Adds live tests for `merge_requests` and `projects`
With this we can now:
-  read: `merge_requests`, `projects`
- write `projects`
Tests:

feat: Extend merge_requests, projects supports Gitlab connector

---

providers/braze/handlers.go
providers/braze/parse.go
providers/dynamicsbusiness/responses.go
test/braze/metadata/main.go
test/braze/read/main.go
test/braze/write/main.go

- Adds support reading next page the objects using defaultPagination. 
With the previous implementation. 
It was failing to correctly construct next page for campaigns + other related objects:
Now:

fix(Braze): support reading next page for campaigns, canvas objects

---

common/interpreter/formatTemplate.go
common/interpreter/responder.go
providers/dynamicsbusiness/connector.go
providers/dynamicsbusiness/errors.go
providers/dynamicsbusiness/read_test.go
providers/dynamicsbusiness/requests.go
providers/dynamicsbusiness/test/err-missing-environment.xml
providers/dynamicsbusiness/url.go

```
errorHandler := interpreter.ErrorHandler{
JSON: interpreter.NewFaultyResponder(errorFormats, nil),
XML:  interpreter.NewXMLFaultyResponder(xmlErrorFormats, nil),
}.Handle
```
Where `xmlErrorFormats` is a list of structs that serve as a format expected to be returned on server error.
Any connector in future can only declare the following:
Business Central can return XML errors. This was discovered when EnvironmentName was invalid.

feat(businesscentral): Handle XML error

---

providers/breakcold.go

URL: http://localhost:4444/tags
URL: http://localhost:4444/tags
URL: http://localhost:4444/tags/ef58b421-a5f2-42b6-93df-be72770457e4
URL: http://localhost:4444/tags/ef58b421-a5f2-42b6-93df-be72770457e4
**Icons for dark and regular mode**
**Logo for  dark mode**
**Logo for regular mode**
**Note:**
In the retool, there is no logo for dark and regular mode. So I resourced them through online.
Link: 
https://mintlify.s3.us-west-1.amazonaws.com/breakcold/logo/dark.svg
https://mintlify.s3.us-west-1.amazonaws.com/breakcold/logo/light.svg

[CON-2051] feat: [breakcold] proxy connector

---

common/printable.go

Nesting them under `details` lets our FE extract one key and display it directly to builders

[ENG-2443] chore(logging): nest connector logs under details

---

connector/new.go
providers/copper.go
providers/copper/connector.go
providers/copper/internal/metadata/metadata.go
providers/copper/internal/metadata/schemas.json
providers/copper/metadata_test.go
scripts/schemadocs/copper/main.go
scripts/schemadocs/copper/samples.json
test/copper/connector.go
test/copper/metadata/main.go

Sample response objects for each endpoint are coppied into one file and used to extract `schema.json`.
* This is not covered in this PR for simplicity

[CON-1266] feat(copper): Metadata

---

internal/datautils/set.go
providers/copper/connector.go
providers/copper/custom.go
providers/copper/handlers.go
providers/copper/metadata.go
providers/copper/metadata_test.go
providers/copper/read_test.go
providers/copper/test/custom/fields.json
providers/copper/test/read/companies/with-custom-fields.json
test/copper/read/companies/main.go
test/utils/mockutils/mockcond/request.go

* Metadata is implemented directly without the helper because of custom field resolution.
* Read still uses `internal/components`
* Custom fields are artifically added to the read with `custom_field_` prefix.

[CON-1266,CON-1267] feat(copper): Custom fields

---

providers/gitlab/handlers.go
test/gitlab/write/main.go

Adds recordId value in the write connector result.

fix: add recordId gitlab write connector

---

providers/loxo.go

URL: http://localhost:4444/people
URL: http://localhost:4444/people/1388693
URL: http://localhost:4444/people
URL: http://localhost:4444/people/1388693
Request the list of people paginated results by using **per_page** to limit the response.
URL:  http://localhost:4444/people?per_page=1
Request the next paginated result by using **scroll_id**  in the response and use the value on the **scroll_id**  query param.
URL: http://localhost:4444/people?per_page=1&scroll_id=5B313735363230393730353637302C302E302C313338383337315D
Logo for light mode
Logo for dark mode
Icon for light & dark mode

[CON-2032] feat: [loxo] Add loxo connector

---

providers/pylon.go

URL: http://localhost:4444/accounts
URL: http://localhost:4444/tags
URL: http://localhost:4444/tags/10c78695-9246-4e0c-874d-8c2654783de7
URL: http://localhost:4444/tags/10c78695-9246-4e0c-874d-8c2654783de7
Pylon pagination works with a cursor and a limit. The response object contains the cursor for the next page, and the limit query specifies the number of results per page.
First Page
Next Page
Icon and logo are the same.
Icon and logo for dark theme
Icon and logo for regular theme

[CON-2140] feat: add Pylon connector

---

common/metadata.go
providers/hubspot/connector.go
providers/hubspot/internal/custom/adapter.go
providers/hubspot/internal/custom/create.go
providers/hubspot/internal/custom/metadata.go
providers/hubspot/internal/custom/payload.go
providers/hubspot/internal/custom/update.go
test/hubspot/metadata/write/many/main.go

Auto create group name uses group id: `integrationcreatedproperties` and its display name is `Integration Created Properties`.
The auto get-create is applied for each object only once.
After running the live `test` script the properties were "moved" to a new group. 
As you can see the group exists with valid display name:
Note: I had removed some fields and ran the script again to see that create & update work as expected:

[CON-2157] feat(hubspot): Custom fields - auto create group

---

providers/dixa/handlers.go

fix: Add recordId in dixa connector writeResults

---

providers/teamleader/handlers.go

Teamleader requires a record ID in the payload. This fix adds the record ID to the payload

[2134] fix(teamleader): add record ID in the payload for the update operation

---

providers/gorgias.go

Mailmonkey using Oauth2 Authorization code grant.
[Test-data](https://github.com/amp-labs/testdata/pull/70)

[CON-1082] feat: Enable read, write actions Gorgias Connector

---

providers/zohocrm/metadata.go
providers/zohocrm/parse.go
providers/zohocrm/read.go
providers/zohocrm/url.go
test/zohocrm/metadata/metadata.go
test/zohocrm/read/users/users.go

This fixes the users object only, the rest (lowercased) don't use the same metadata retrieval approach as the rest. 
Live Tests:
Meatadata:
Read:

fix: Add support for users object zoho connector

---

common/types.go
providers/salesforce/errors.go

This detects the INVALID_QUERY_LOCATOR code from Salesforce and returns a typed error that can be caught in the server for more nuanced processing (e.g. deleting the cursor from the state so that it doesn't get used again).

detect INVALID_QUERY_LOCATOR error

---

providers/highlevel.go
providers/highlevelstandard/README.md
providers/highlevelstandard/handlers.go
providers/highlevelstandard/support.go
providers/highlevelstandard/utils.go
providers/highlevelwhitelabel/README.md
providers/highlevelwhitelabel/handlers.go
providers/highlevelwhitelabel/support.go
providers/highlevelwhitelabel/utils.go

Link pull request to testdata repo which contains installation file: https://github.com/amp-labs/testdata/pull/87
**Note:**
In this PR, I have added support for some read and write endpoints, and removed certain delete endpoints because they require query parameters or body parameters in the request. 
And also chekced all this and tested it.

[CON-2022] feat: [Highlevel] Enable read and write

---

providers/chorus.go

**Icon for Dark and Regular mode**
**Logo for Dark and Regular mode**
```
API docs: https://api-docs.zoominfo.com/
Please note: we can develop, but cannot test and therefore cannot release the connector. Reviewer should not expect testing to be done.
```
For info for the Zoominfo connector. The Chorus connector is product of zoominfo, So testing is impossible.

[CON-2163] feat: [chorus] Added the connector

---

providers/amplitude/connector.go
providers/amplitude/handlers.go
providers/amplitude/parse.go
providers/amplitude/support.go
providers/amplitude/utils.go
test/amplitude/connector.go
test/amplitude/metadata/main.go
test/amplitude/read/main.go

* This is not covered in this PR for simplicity

[CON-2246] feat(amplitude): add ListMetadata + Read

---

providers/salesforce/internal/crm/custom/payload.go

This just adds quotes to the default string field so that salesforce doesn't confuse the value for a reference

fix: Add quotes to Salesforce metadata default value field

---

providers/linkedIn.go
providers/linkedin/connector.go

by convention, we don't capitalize the metadata keys

fix: use non-capital provider metadata for LinkedIn connector

---

providers/calendly.go
providers/calendly/authmetadata.go
providers/calendly/authmetadatamodel.go
providers/calendly/connector.go
providers/calendly/handlers.go
test/calendly/auth-metadata/main.go
test/zoom/metadata/metadata.go

This adds these metadata to the calendly connector:
- userURI 
- orgURI
these will be used in most of the calls when reading different calendly objects, as will be shown in the read connector PR. This is possible as one account can only be associated with 1 organization at a time. [Link](https://community.calendly.com/how-do-i-40/one-user-multiple-organizations-1514)
Ideas have been taken from [here](https://github.com/amp-labs/connectors/pull/1871)
Live tests:

feat: Add UserURI and OrgURI metadata in calendly connector

---

providers/calendly/connector.go
providers/calendly/handlers.go
providers/calendly/support.go
test/calendly/write/main.go
test/zoom/metadata/metadata.go

[CON-1478] feat: add calendly write connector

---

providers/amplitude.go

[CON-2250] feat(amplitude): enable Read + Write support
